### ISSUE TITLE
XDMP-VALIDATEMISSINGATTR when using field values query

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#103]
This is probably user head gap, given that I've been having a very hard time making sense of the jsDoc for valuesBuilder. When I try to specify a field index, I get back XDMP-VALIDATEMISSINGATTR. 

My db includes a field (and field range index) on a field named 'questionId'. I was trying to use it like this:
```javascript
var marklogic = require('marklogic');
var my = require('./my-connection.js');

var db = marklogic.createDatabaseClient(my.connInfo);
var vb = marklogic.valuesBuilder;

db.values.read(
  vb.fromIndexes(vb.field('questionId'))
).result(function (result) {
  console.log(JSON.stringify(result, null, 2));
}, function(error) {
  console.log(JSON.stringify(error, null, 2));
});
```
The result of running this script is:
```json
{
  "message": "query values: response with invalid 400 status",
  "statusCode": 400,
  "body": {
    "errorResponse": {
      "statusCode": 400,
      "status": "Bad Request",
      "messageCode": "REST-INVALIDPARAM",
      "message": "REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: Invalid combined search\nRESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Operation results in invalid Options: XDMP-VALIDATEMISSINGATTR: (err:XQDY0027) validate strict { $opt } -- Missing required attribute: Found () but required (@name & @collation?) at /search:search/search:options/search:values/search:field using schema \"search.xsd\"()(@name & @collation?)/search:search/search:options/search:values/search:field\"search.xsd\""
    }
  }
}
```
When I dump out what's created by vb.fromIndexes, it looks like this:
```
{"fromIndexesClause":[{"field":"questionId"}]}
```
I thought maybe it was because I wasn't calling where(), but I don't want a qualifying query, and when I tried adding one, it didn't help.

The generated options look like this:

{ values: [ {name: 'structuredef', style: 'consistent', field: 'questionId'} ] }

I think that's wrong. In XML, the field specifier has a name attr, and I believe JSON has a corresponding property name. At least, I convinced myself of that once upon a time:

http://docs.marklogic.com/guide/rest-dev/appendixa#id_24153

I tried to convince myself of this by building a correct REST call by hand, but I think I'm too tired because I can't get it to work, either. It's getting a different error, though, that I think is me being stupid. I'll post a followup if I unravel it.

**Comment by MayankBhatnagar89** [comment]
Test added to regression under test-complete/nodejs-documents-values.js

Thanks,
Mayank
