### ISSUE TITLE
defaultGraph is false after writing to the default graph

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#104]
This might be user error, given that you have a test that does almost exactly the same thing and that is apparently passing. The difference between what I did and what test-basic/graphs.js does is the test streams the data from a file and I did, um, something weird:

I cobbled the triples up from an array of strings because I wanted the script not to rely on a separate file, I wanted it to look readable, and I know some of the triples formats are line break sensitive (but was too lazy to figure out if turtle is one of them. Otherwise know as "tech writers do the damndest things".

When I run the script, it does The Right Thing wrt to the database, but the response that comes back sets defaultGraph to false, which is not correct.
```javascript
var marklogic = require('marklogic');
var my = require('./my-connection.js');

var db = marklogic.createDatabaseClient(my.connInfo);

var triples = [
  '@prefix foaf: <http://xmlns.com/foaf/0.1/> .',
  '@prefix ppl:  <http://people.org/> .',
  'ppl:person1 foaf:knows ppl:person2 .',
  'ppl:person1 foaf:knows ppl:person3 .',
  'ppl:person2 foaf:knows ppl:person3 .',
  'ppl:person1 a ppl:Person ;',
  '    foaf:name "Person 1" .',
  'ppl:person2 a ppl:Person ;',
  '    foaf:name "Person 2" .',
  'ppl:person3 a ppl:Person ;',
  '    foaf:name "Person 3" .',
];

db.graphs.write({contentType: 'text/turtle', data: triples.join('\n')}).result(
    function(response) { 
      if (response.defaultGraph) {
        console.log("Loaded into default graph"); 
      } else {
        console.log("Loaded into graph " + response.graph); 
      };
    },
    function(error) { console.log(JSON.stringify(error)); }
);
```
This emits "Loaded into graph undefined". When I dumped out the response, it is just {"defaultGraph": false}. It is actually loading the triples into the default graph, though.

Originally, I called db.graphs.write('text/turtle', triples.join('\n')), but that caused an error, so I fell back on calling it using an object. This bit of chicanery suggests the problem is me, not you, but I can't see what's wrong. Here's the error I was getting originally:
```
http.js:851
    throw new TypeError('first argument must be a string or Buffer');
          ^
TypeError: first argument must be a string or Buffer
    at ClientRequest.OutgoingMessage.write (http.js:851:11)
    at Operation.singleRequester (F:\javascript\my-project\node_modules\marklogic\lib\mlrest.js:358:15)
    at authenticatedRequest (F:\javascript\my-project\node_modules\marklogic\lib\mlrest.js:336:15)
    at ClientRequest.challengeResponder (F:\javascript\my-project\node_modules\marklogic\lib\mlrest.js:308:7)
    at ClientRequest.g (events.js:180:16)
    at ClientRequest.EventEmitter.emit (events.js:95:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (http.js:1688:21)
    at HTTPParser.parserOnHeadersComplete [as onHeadersComplete] (http.js:121:23)
    at Socket.socketOnData [as ondata] (http.js:1583:20)
    at TCP.onread (net.js:527:27)
```

**Comment by gvaidees** [comment]
Added test for this issue. Shipping it
