### ISSUE TITLE
unable to retrieve snippets without documents

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#105]
Erik, if you'd rather this go into the RFEtrack, close this and I'll file it over there instead.

I think a common use case for snippets is to retrieve just the snippets. However, the Node.js API currently does not enable you to do so, as far as I can tell.

`qb.slice(0)` and `qb.slice(0, qb.snippet())` don't return documents or snippets.
`qb.slice(N,M,qb.snippet())` or `qb.slice(qb.snippet())` return both documents and snippets.

I rather expected `qb.slice(0, qb.snippet())` to return just snippets, but even if it did, it wouldn't be sufficient because there would still be no way to retrieve just snippets for specific slices.

I figured this is an 8.0-2 thing, at best, but there's no milestone for post-8.0-1 yet, so I'll leave that bit in your capable hands.

**Comment by MayankBhatnagar89** [comment]
Test added to regression  under test-complete/nodejs-documents-query.js
