### ISSUE TITLE
unable to supply suggest bindings only through suggestBindings

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#107]
I cannot use just the suggestBindings clause to add bindings.to suggestions. For example, a call like this:
```
db.documents.suggest('doc', 
    qb.where(qb.directory('/suggest/', true)),
    qb.suggestBindings(
        qb.range('name', qb.bindDefault()))
  )
```
Produces the following error: `Cannot read property 'constraint' of undefined`

You can get around this (and are probably intended to do so) by including the bindings in a qb.parsedFrom('',...) in the qualifying query instead of the overrides.

**Comment by ayuwono** [comment]
Verified passed, added test on nodejs-documents-suggest.js
