### ISSUE TITLE
db.resources rejects non-default response status code

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#108]
I have an extension that sets the response code from get to 201, just to show you can. When I invoke it using the Node.js API, I get the following rude response:
```json
{
  "message": "js-example: response with invalid 201 status",
  "statusCode": 201
}
```
If I set the code to 200, it returns the data I expect. The handler shouldn't be so uptight about the response status code.

**Comment by gvaidees** [comment]
Thanks Kim for the code. I have added this to regression.
