### ISSUE TITLE
Extensions: JSON input docs and multi-valued getting corrupted

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#109]
I'm hoping this is just me using db.resources wrong. I apologize in advance that all the blather below is probably going to make your head hurt, but stick with me. :)

I am trying to use Node.js replicate this form of curl call, using the extension from issue #108 and a body that contains 2 parts.

curl --anyauth --user user:password -X PUT -i --data-binary @./sjs-ext-body
 -H "Content-type: multipart/mixed; boundary=BOUNDARY" 
 http://myhost:8000/v1/resources/js-example?rs:basename=one&rs:basename=two

The problem is that both my param values and my input documents hit the extension in a bit of a mess. The param values get concatenated into {params:{basename:'one,two'}} instead being an array, and the documents turn into binary. The latter might be brought to you by the Letter W, as in Windows. I have a Windows client and Linux server.

Hopefully you'll just tell me I'm doin' it wrong. Here's the script I used to invoke the put. It barfs with a 400 error because it's not able to use toObject on the input docs.
```javascript
var marklogic = require('marklogic');
var my = require('./my-connection.js');
var db = marklogic.createDatabaseClient(my.connInfo);

db.resources.put({
  name: 'js-example', 
  params: {
    basename: ['one', 'two']},
  documents: [
    { contentType: 'application/json',
    content: {key1:'value1'} },
    { contentType: 'application/json',
    content: {key2:'value2'} },
  ]
}).result(function(response) {
  console.log(response);
}, function(error) {
  console.log(JSON.stringify(error, null, 2));
});
```
To probe the problem, I changed my extension to just dump out its inputs so I could see what was going on, like this:
```javascript
function put(context, params, input) {
  context.outputTypes = ["application/json"];
  return {context: context, params: params, input: input};
}
```
When I invoke it with curl, I get this output. (Never mind that one of the docs is XML here - I was too lazy to regen my multipart body. All that matters is that the docs look like what I fed in.)
```json
{  "context": {
    "acceptTypes": [ ],
    "inputBoundary": "BOUNDARY",
    "inputTypes": [ "application/json", "application/xml" ],
    "outputTypes": [ "application\/json" ]
  },
  "params": { "basename": [ "one", "two" ] },
  "input": [ 
    { "key": "some json content" },
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<root>some xml content<\/root>"
  ]
}
```
When I invoke the same impl with the Node.js script, I get this output. Dude, where's my content?? :) Looks like my original input as bytes. I smell binary documents... 
```javascript
{ context:
   { acceptTypes: [ 'application/json' ],
     inputBoundary: 'MLBOUND_1422662400000',
     inputTypes: [ 'application/json', 'application/json' ],
     outputTypes: [ 'application/json' ] },
  params: { basename: 'one,two' },
  input:
   [ '7b226b657931223a2276616c756531227d0d0a',
     '7b226b657932223a2276616c756532227d0d0a' ] }
```
I fell back on a single input document and `xdmp.log(input.documentFormat)`, which indeed reports JSON in the curl invocation and BINARY in the Node.js invocation. When I log `input` directly along with its doc type, it looks like there might be a stray CRLF hanging around. With curl you get this: 
```
2014-12-31 21:00:38.762 Info: App-Services: {"key":"value"}
2014-12-31 21:00:38.762 Info: App-Services: JSON
```
With Node, you get this. Notice the extra "blank" line:
```
2014-12-31 20:59:10.019 Info: App-Services: {"key":"value"}
2014-12-31 20:59:10.019 Info: App-Services:
2014-12-31 20:59:10.019 Info: App-Services: BINARY
```

**Comment by ehennum** [comment]
As in Kim's example, a request to a resource service should be able to set a parameter to an array of values and send an array of documents.

**Comment by gvaidees** [comment]
Thanks @kcoleman-marklogic for the example code
