### ISSUE TITLE
page length defaults categories to include collections

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#110]

**Comment by ehennum** [comment]
Specifying both the start and length in the .slice() clause should not change the default categories from content.

**Comment by gvaidees** [comment]
Added coverage in nodejs-documents-extract.js. In 'extract with include-with-ancestors' I added asserts such as - 

```javascript
      response[0].category.should.equal('content');
      response[1].category.should.equal('content');
```

Erik,

Please confirm this is sufficient. Marking as ship

**Comment by MayankBhatnagar89** [comment]
Documents was having collections , hence added a new test as nodejs-issue-110.js
