### ISSUE TITLE
Cannot specify a values transform w/o a full slice specification

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#111]
If I want to use a transform with a values query, I have to create a complete slice definition (start, length, transform). I cannot just add a transform or even just a transform and a start position. Possibly this is WAI, but if so, it's seems a somewhat inconvenient and awkward, IMO. Why can't I use a transform with the page length default, for example?

I tried all the following variants, but only the first of these results in invocation of my transform:
```javascript
    .slice(1, 10, vb.transform('js-query-transform'))

    .slice(vb.transform('js-query-transform'))
    .slice(0, vb.transform('js-query-transform'))
    .slice(1, vb.transform('js-query-transform'))
    .slice({start: 1, transform: vb.transform('js-query-transform')})
```
This probably applies to `queryBuilder.slice ` as well, but I didn't happen to try it there.

**Comment by ehennum** [comment]
The .slice() clause should be able to take a .transform() invocation without the paging parameters.

**Comment by MayankBhatnagar89** [comment]
Tests added to regression under test test-complete/nodejs-transform-javascript.js
