### ISSUE TITLE
default queries to unfiltered

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#112]
Because the query builder for the Node.js API generates query options, it can't rely on the default query options maintained by the REST API.

Thus, the query builder must generate the unfiltered option by default.

**Comment by ehennum** [comment]
If the query doesn't have a .withOptions{search:['filtered']} clause, the query defaults to unfiltered.

**Comment by MayankBhatnagar89** [comment]
Test added in regression under nodejs-documents-query.js
