### ISSUE TITLE
Filtered search returns snippets when they are not asked for

### ISSUE THREAD

**Issue by gvaidees** [marklogic/node-client-api#116]
To fix the failing 'should do extract with include' test in test-complete/nodejs-documents-extract.js, I added code to get filtered results. After doing so, the response contains snippets when that was not requested. Here is the query based on nodejs-documents-extract.js

```javascript
it('should do extract with include', function(done){
    db.documents.query(
      q.where(
        q.word('id', '**26', q.termOptions('wildcarded'))
      ).
      slice(1, 10,
        q.extract({
          selected:'include',
          paths:[
            '/node("id")'
          ]
        })
      ).withOptions({search: ['filtered']}) 
    ).result(function(response) {
      console.log(response);

```

Response looks like - 

```
[{ 'snippet-format': 'snippet',
    total: 1,
    start: 1,
    'page-length': 10,
    results: [ [Object] ] },
  { uri: '/test/query/matchList/doc5.json',
    category: 'content',
    format: 'json',
    contentType: 'application/json',
    contentLength: '86',
    content:
     { context: 'fn:doc("/test/query/matchList/doc5.json")',
       extracted: [Object] } } ]
```

Note snippets are being returned

**{ 'snippet-format': 'snippet',
    total: 1,
    start: 1,
    'page-length': 10,
    results: [ [Object] ] 
 },**

**Comment by ehennum** [comment]
Was inferring response return for all withOptions clause flags.  Now should do so only for the flags that require a response:  debug, metrics, queryPlan, and similarDocs

**Comment by gvaidees** [comment]
@ehennum ,

Should we be testing all options and make sure response contains the right properties or do you think what we have now is enough

**Comment by gvaidees** [comment]
I see this issue fixed. Output is as follows - 

```
[ { uri: '/test/query/matchList/doc5.json',
    category: 'content',
    format: 'json',
    contentType: 'application/json',
    contentLength: '86',
    content:
     { context: 'fn:doc("/test/query/matchList/doc5.json")',
       extracted: [Object] } } ]
```

**Comment by ehennum** [comment]
A spot check of one flag that requires options (such as similarDocs) and one that doesn't (such as search) would be sufficient.

Also, thanks for the rapid turnaround on confirming the fix.

**Comment by gvaidees** [comment]
Thanks. I will add a task for that. This issue is closed
