### ISSUE TITLE
SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol error while executing ssl test

### ISSUE THREAD

**Issue by MayankBhatnagar89** [marklogic/node-client-api#118]
Code : 
*******************************************************************************************
var should = require('should');
var testconfig = require('../etc/test-config-qa.js');
var marklogic = require('../');

var db = marklogic.createDatabaseClient(testconfig.restWriterConnection);
var dbReader = marklogic.createDatabaseClient(testconfig.restReaderConnection);
var dbSsl = marklogic.createDatabaseClient(testconfig.restSslConnection);

describe('SSL Test', function() {
  
  var docuri = '/foo/bar/test1.json'; 
  var docuri2 = '/foo/bar/test2.json'; 
 
  before(function(done) {
    this.timeout(3000);
    dbSsl.documents.write({
      uri: docuri,
      collections: ['coll0', 'coll1'],
      contentType: 'application/json',
      quality: 10,
      permissions: [
        {'role-name':'app-user', capabilities:['read']},
        {'role-name':'app-builder', capabilities:['read', 'update']}
      ],
      properties: {prop1:'foo', prop2:25},
      content: {id:12, name:'Jason'}
    }, {
      uri: docuri2,
      collections: ['coll0', 'coll1'],
      contentType: 'application/json',
      quality: 10,
      permissions: [
        {'role-name':'app-user', capabilities:['read']},
        {'role-name':'app-builder', capabilities:['read', 'update']}
      ],
      properties: {prop1:'bar', prop2:33},
      content: {id:245, name:'Paul'}
    }).result(function(response){done();}, done);
  });

  it('should read the document content name', function(done) {
    dbSsl.documents.read({uris: docuri}).result(function(documents) {
      var document = documents[0];
      document.content.name.should.equal('Jason');
      done();
    }, done);
  });
  
});
*******************************************************************************************

Error : 
*******************************************************************************************
<testcase classname="SSL Test" name="&quot;before all&quot; hook" time="0.035" message="140060866328352:error:140770FC::../deps/openssl/openssl/ssl/s23_clnt.c:795:
"><failure classname="SSL Test" name="&quot;before all&quot; hook" time="0.035" message="140060866328352:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:795:
"><![CDATA[Error: 140060866328352:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:../deps/openssl/openssl/ssl/s23_clnt.c:795:

    at SlabBuffer.use (tls.js:234:18)
    at CleartextStream.read [as _read] (tls.js:454:29)
    at CleartextStream.Readable.read (_stream_readable.js:340:10)
    at EncryptedStream.write [as _write] (tls.js:368:25)
    at doWrite (_stream_writable.js:225:10)
    at writeOrBuffer (_stream_writable.js:215:5)
    at EncryptedStream.Writable.write (_stream_writable.js:182:11)
    at write (_stream_readable.js:601:24)
    at flow (_stream_readable.js:610:7)
    at Socket.pipeOnReadable (_stream_readable.js:642:5)
    at Socket.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:426:10)
    at emitReadable (_stream_readable.js:422:5)
    at readableAddChunk (_stream_readable.js:165:9)
    at Socket.Readable.push (_stream_readable.js:127:10)
    at TCP.onread (net.js:528:21)]]></failure></testcase>
*******************************************************************************************

The code is failing in the before method only. Please look into it

**Comment by ehennum** [comment]
Can you provide the test setup that create the REST server for testconfig.restSslConnection ?

**Comment by ehennum** [comment]
I had no problem executing write documents using basic SSL authentication.  The steps:

1.  Create an SSL certificate template in MarkLogic server
2.  Configure the REST server to use the SSL certificate template, basic authentication, and to no require a client certificate.
3.  Configure the client connection properties with ssl: true, rejectUnauthorized: false, and authType: 'BASIC'

That procedure worked without issue for me.

We should also test with the server requiring a client certificate and the client supplying a certificate.
See http://nodejs.org/api/https.html#https_https_request_options_callback

**Comment by MayankBhatnagar89** [comment]
Seems like Node.js test environment set up issue , because it is not creating the SSL certificate  template. Will work on the setup

**Comment by MayankBhatnagar89** [comment]
The issue has been resolved with a different setup for ssl connection which is working fine now, hence closing this Issue.
