### ISSUE TITLE
unable to specify range requests for binary documents

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#121]
There doesn't appear to be a way to stream binaries out of the db via range requests. That is, the node.js equivalent of what is described here:

http://docs.marklogic.com/guide/rest-dev/documents#id_52962

Erik indicated this is an oversight,so this is our gentle reminder to add this capability to the API.

**Comment by ehennum** [comment]
Per the specification, you can specify range:[from, to] when requesting a single binary document.

The end of the range is optional.  The end is also exclusive as with a JavaScript slice instead of inclusive as with an HTTP range.

**Comment by ayuwono** [comment]
Added test nodejs-documents-binary-range.js to cover binary range and negative tests
