### ISSUE TITLE
Is there a way to for query by example to filter only on root level object properties?

### ISSUE THREAD

**Issue by dorlandode** [marklogic/node-client-api#124]
Assuming I have an object structured as below, is there a way to force query by example to filter off only the root level property:

``` javascript
{
     "hidden": false,
      "children: [
             {"hidden": true}
      ] 
}
```

The point being that I only what to look at the first "hidden" property, not the "hidden" property in the children objects.

Looking at a "query by example" example:

``` javascript
"title": {
  "$value": "Tom Sawyer",
  "$exact": false
}
```

Is there a way to do something like:

``` javascript
"title": {
  "$value": "Tom Sawyer",
  "$exact": false,
 "$greedy": false
}
```

OR

``` javascript
"$.title": {
  "$value": "Tom Sawyer",
  "$exact": false,
}
```

 Where the `$.title` is a json path matching the exact path of what I want to filter by.

Where greedy would tell it I don't want it look at any matching property in the document, but rather I want it restricted to the first match.  I seems odd that I can provide an object path to a property deeper in the document, but not at the root of the document.

Or is there way to use a path range index in a query by example query?

**Comment by ehennum** [comment]
As you hint, the best way to solve this problem that I know about is to use a path, either with a range index or field.

At present, QBE doesn't support path range indexes or fields, so that would require an RFE (Request For Enhancement).  

The QueryBuilder does, however, support fields and path range indexes.
