### ISSUE TITLE
How to only return snippet with results, that has the highlights etc, and not include the documents?

### ISSUE THREAD

**Issue by mstellwa** [marklogic/node-client-api#127]
I am trying to get only the snippet, not the documents, back as the result using queryBuilder but I want to have the results (that has the highlights etc) included.

Using slice(0) with the following code:
db.documents.query(
      qb.where(
        qb.parsedFrom(qry)
      ).slice(0)
      ).result(function(results) {
            callback(results);
        }); 

Will get me the following result:
[
  {
    "snippet-format": "snippet",
    "total": 3,
    "start": 1,
    "page-length": 0,
    "results": [],
    "qtext": "sweden AND germany",
    "metrics": {
      "query-resolution-time": "PT0.003513S",
      "facet-resolution-time": "PT0.000071S",
      "snippet-resolution-time": "PT0S",
      "total-time": "PT0.12378S"
    }
  }
]

Using .slice(qb.snippet()) will give me the result but also the documents:
[
  {
    "snippet-format": "snippet",
    "total": 3,
    "start": 1,
    "page-length": 10,
    "results": [
      {
        "index": 1,
        "uri": "/laureate/187.xml",
        "path": "fn:doc(\"/laureate/187.xml\")",
        "score": 55424,
        "confidence": 0.4705933,
        "fitness": 0.7494136,
        "href": "/v1/documents?uri=%2Flaureate%2F187.xml",
        "mimetype": "application/xml",
        "format": "xml",
        "matches": [
          {
            "path": "fn:doc(\"/laureate/187.xml\")/*:laureate/*:bornCountry",
            "match-text": [
              {
                "highlight": "Germany"
              }
            ]
          },
          {
            "path": "fn:doc(\"/laureate/187.xml\")/*:laureate/*:diedCountry",
            "match-text": [
              {
                "highlight": "Sweden"
              }
            ]
          },
          {
            "path": "fn:doc(\"/laureate/187.xml\")/*:laureate/*:country",
            "match-text": [
              {
                "highlight": "Sweden"
              }
            ]
          }
        ]
      },
      {
        "index": 2,
        "uri": "/laureate/201.xml",
        "path": "fn:doc(\"/laureate/201.xml\")",
        "score": 51584,
        "confidence": 0.4539984,
        "fitness": 0.7229864,
        "href": "/v1/documents?uri=%2Flaureate%2F201.xml",
        "mimetype": "application/xml",
        "format": "xml",
        "matches": [
          {
            "path": "fn:doc(\"/laureate/201.xml\")/*:laureate/*:diedCountry",
            "match-text": [
              "West ",
              {
                "highlight": "Germany"
              },
              " (now ",
              {
                "highlight": "Germany"
              },
              ")"
            ]
          },
          {
            "path": "fn:doc(\"/laureate/201.xml\")/*:laureate/*:country",
            "match-text": [
              {
                "highlight": "Sweden"
              }
            ]
          }
        ]
      },
      {
        "index": 3,
        "uri": "/laureate/640.xml",
        "path": "fn:doc(\"/laureate/640.xml\")",
        "score": 45056,
        "confidence": 0.4243001,
        "fitness": 0.6756923,
        "href": "/v1/documents?uri=%2Flaureate%2F640.xml",
        "mimetype": "application/xml",
        "format": "xml",
        "matches": [
          {
            "path": "fn:doc(\"/laureate/640.xml\")/*:laureate/*:bornCountry",
            "match-text": [
              {
                "highlight": "Germany"
              }
            ]
          },
          {
            "path": "fn:doc(\"/laureate/640.xml\")/*:laureate/*:diedCountry",
            "match-text": [
              {
                "highlight": "Sweden"
              }
            ]
          }
        ]
      }
    ],
    "qtext": "sweden AND germany"
  },
  {
    "uri": "/laureate/187.xml",
    "category": "content",
    "format": "xml",
    "contentType": "application/xml",
    "contentLength": "733",
    "content": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<laureate xmlns=\"http://marklogic.com/swe/nobel-prize\"><id>187</id><firstname>Hans Karl August Simon</firstname><surname>von Euler-Chelpin</surname><born>1873-02-15</born><died>1964-11-06</died><bornCountry>Germany</bornCountry><bornCountryCode>DE</bornCountryCode><bornCity>Augsburg</bornCity><diedCountry>Sweden</diedCountry><diedCountryCode>SE</diedCountryCode><diedCity>Stockholm</diedCity><gender>male</gender><year>1929</year><category>chemistry</category><overallMotivation/><share>2</share><motivation>\"for their investigations on the fermentation of sugar and fermentative enzymes\"</motivation><name>Stockholm University</name><city>Stockholm</city><country>Sweden</country></laureate>"
  },
  {
    "uri": "/laureate/201.xml",
    "category": "content",
    "format": "xml",
    "contentType": "application/xml",
    "contentLength": "765",
    "content": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<laureate xmlns=\"http://marklogic.com/swe/nobel-prize\"><id>201</id><firstname>George</firstname><surname>de Hevesy</surname><born>1885-08-01</born><died>1966-07-05</died><bornCountry>Austria-Hungary (now Hungary)</bornCountry><bornCountryCode>HU</bornCountryCode><bornCity>Budapest</bornCity><diedCountry>West Germany (now Germany)</diedCountry><diedCountryCode>DE</diedCountryCode><diedCity>Freiburg im Breisgau</diedCity><gender>male</gender><year>1943</year><category>chemistry</category><overallMotivation/><share>1</share><motivation>\"for his work on the use of isotopes as tracers in the study of chemical processes\"</motivation><name>Stockholm University</name><city>Stockholm</city><country>Sweden</country></laureate>"
  },
  {
    "uri": "/laureate/640.xml",
    "category": "content",
    "format": "xml",
    "contentType": "application/xml",
    "contentLength": "678",
    "content": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<laureate xmlns=\"http://marklogic.com/swe/nobel-prize\"><id>640</id><firstname>Nelly</firstname><surname>Sachs</surname><born>1891-12-10</born><died>1970-05-12</died><bornCountry>Germany</bornCountry><bornCountryCode>DE</bornCountryCode><bornCity>Berlin</bornCity><diedCountry>Sweden</diedCountry><diedCountryCode>SE</diedCountryCode><diedCity>Stockholm</diedCity><gender>female</gender><year>1966</year><category>literature</category><overallMotivation/><share>2</share><motivation>\"for her outstanding lyrical and dramatic writing, which interprets Israel's destiny with touching strength\" </motivation><name/><city/><country/></laureate>"
  }
]

and using.slice(0, qb.snippet()) will give me nothing useful....
[
  {
    "snippet-format": "snippet",
    "start": 1,
    "page-length": 0,
    "results": [],
    "qtext": "sweden AND germany"
  }
]

Have I missed something here?

/Mats

**Comment by kcoleman-marklogic** [comment]
Assuming you're on the develop branch, try something like this:

`qb.where(...).slice(qb.snippet()).withOptions({categories: 'none'})`

On the master branch, you currently unable to retrieve just snippets; see issue #105.

**Comment by mstellwa** [comment]
That did the trick.

By the way, in the latest document build there is an example in node-dev.pdf on page 111 that shows that the results are returned when using .slice(0). 

/Mats

**Comment by kcoleman-marklogic** [comment]
Thank you for bringing that to my attention, Mats. I'll make sure it's taken care of.

**Comment by ehennum** [comment]
Closing the issue because resolved.
