### ISSUE TITLE
queryBuilder.sort() to accept a Path Range Index

### ISSUE THREAD

**Issue by tamaspiros** [marklogic/node-client-api#131]
The queryBuilder's `.sort()` method doesn't seem to accept a Path Range Index value.

Given a sample JSON document that contains the following:
```javascript
{
"name": {
"common": "Afghanistan",
"official": "Islamic Republic of Afghanistan"
},
"currency": [
"AFN"
],
"callingCode": [
"93"
]
}
```

A Path Range Index was also created in the admin interface with the path of '/name/common'.

The following query from node.js results in a <i>Possibly unhandled Error. query documents: response with invalid 400 status</i> message:

```javascript
db.documents.query(
  qb.where().orderBy(qb.sort('/name/common'))
).result()
```

Is this the expected behaviour?

**Comment by ehennum** [comment]
You can omit the function that specifies the kind of index only if the index is on a single JSON property. In other words, the code above is specifying a sort on a JSON property named '/name/common' (which is a legal property name, though strongly discouraged).

Try specifying a path index using the qb.pathIndex() function:

db.documents.query(
  qb.where().orderBy(qb.sort(qb.pathIndex*'/name/common')))
).result()

**Comment by tamaspiros** [comment]
Thanks Erik.
```javascript
db.documents.query(
  qb.where().orderBy(qb.sort(qb.pathIndex('/name/common')))
)
.result()
.then(function(documents) {
  console.log(documents);
})
.catch(function(error) {
  console.log(error);
});
```

logs the following error:
```
{ [Error: query documents: response with invalid 400 status]
  message: 'query documents: response with invalid 400 status',
  statusCode: 400,
  body:
   { errorResponse:
      { statusCode: 400,
        status: 'Bad Request',
        messageCode: 'REST-INVALIDPARAM',
        message: 'REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: Invalid combined search\nRESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Operation results in invalid Options: XDMP-VALIDATEUNEXPECTED: (err:XQDY0027) validate strict { $opt } -- Invalid node: Found search:path-index but expected ((((search:element)|search:attribute)|search:field|search:json-property)|search:score|search:annotation)* at /search:search/search:options/search:sort-order/search:path-index using schema "search.xsd"search:path-index((((search:element)|search:attribute)|search:field|search:json-property)|search:score|search:annotation)*/search:search/search:options/search:sort-order/search:path-index"search.xsd"An <element>, <json-property>, <field>, <path-index> or <score> specification is required on <sort-order>.' } } }
```

**Comment by ehennum** [comment]
The Search API has a schema bug -- the implementation supports JSON properties, XML elements and attributes, fields, and path indexes, but the schema doesn't support path indexes.  Please file a bug in the internal bug tracker against the Search API.  In the meantime, you should be able to turn off validation on the REST API:

http://docs.marklogic.com/guide/rest-dev/service#id_61169

**Comment by tamaspiros** [comment]
Bug #32236 has been opened - thanks
