### ISSUE TITLE
test on Node.js 0.12 and io.js

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#132]
Now that Node.js 0.12 and io.js 1.1.0 are available, the next release of the API should test in these environments as well.

**Comment by ayuwono** [comment]
Steps to upgrade node on *nix:
1) sudo npm install n
2) sudo n 0.12.0

**Comment by ayuwono** [comment]
test-basic and test-complete are running fine on node version 0.12.0 on both linux and windows

**Comment by ayuwono** [comment]
Instruction to install iojs:
http://jonathanmh.com/installing-io-js-ubuntu-digital-ocean-droplet/

1) wget https://iojs.org/dist/v1.5.1/iojs-v1.5.1-linux-x64.tar.gz
2) tar zxf iojs-v1.5.1-linux-x64.tar.gz
3) cd iojs-v1.5.1-linux-x64
4) cp bin/* /usr/bin (as root user)

Then modify package.json to use iojs engine version 1.5.1
  "engines": {
    "iojs": "1.5.1"
  },

Then run npm install

**Comment by ayuwono** [comment]
iojs v1.5.1 is working fine on test-basic and test-complete on linux

**Comment by ehennum** [comment]
Excellent.  Thanks for confirming that.

**Comment by ayuwono** [comment]
iojs v1.5.1 is working fine on test-basic and test-complete on windows
