### ISSUE TITLE
Query option is throwing unknown option "view"

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#134]
This is a regression issue starting on 02/11
query:
    db.documents.query(
      q.where(
        q.directory('/test/query/matchDir/')
        ).
      withOptions({queryPlan: true,
                   metrics: true,
                   debug: true,
                   weight: 2.3,
                   similarDocs: true,
                   view: "none",
                   categories: ['permissions']})).
      result(function(response) {
        response.length.should.equal(5);
        response[1].permissions.should.be.ok;
        response[0].results[0].content.should.containEql('similar');
        //console.log(JSON.stringify(response, null, 4));
        done();
      }, function(error) {
        console.log(JSON.stringify(error, null, 2));
        done();
      });

<testcase classname="document query options test" name="should do document query with options: categories = permissions and similarDocs = true" time="0" message="unknown option view"><failure classnam
e="document query options test" name="should do document query with options: categories = permissions and similarDocs = true" time="0" message="unknown option view"><![CDATA[Error: unknown option view

    at QueryBuilder.withOptions (/space/SVN_HOME/HEAD/qa/node-client-api/lib/query-builder.js:4714:15)
    at Context.&lt;anonymous&gt; (/space/SVN_HOME/HEAD/qa/node-client-api/test-complete/nodejs-documents-query-options.js:151:7)
    at Test.Runnable.run (/usr/lib/node_modules/mocha/lib/runnable.js:196:15)
    at Runner.runTest (/usr/lib/node_modules/mocha/lib/runner.js:374:10)
    at /usr/lib/node_modules/mocha/lib/runner.js:452:12
    at next (/usr/lib/node_modules/mocha/lib/runner.js:299:14)
    at /usr/lib/node_modules/mocha/lib/runner.js:309:7
    at next (/usr/lib/node_modules/mocha/lib/runner.js:247:23)
    at Object._onImmediate (/usr/lib/node_modules/mocha/lib/runner.js:276:5)
    at processImmediate [as _immediateCallback] (timers.js:330:15)]]></failure></testcase>

**Comment by ehennum** [comment]
The withOptions clause doesn't support the view option.  Specifying the view would be redundant, given that the specified options already indicate what to return.

For instance, in the test case, the queryPlan, metrics, debug, and similarDoc options indicate that a search summary should be provided, which a view of 'none' would contradict.

I have improved error checking in the query builder, so it's good that this is now being reported as an error.

This test case should be revised not to set the view.

**Comment by ayuwono** [comment]
Fixed test case on nodejs-documents-query-options.js
