### ISSUE TITLE
properties fragment query instead of properties query

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#135]
The Search API and cts:search() take a properties fragment query, but the Node.js API is passing a properties query.

**Comment by ehennum** [comment]
The qb.properties() test in test-complete/nodejs-documents-query-2.js should change to qb.propertiesFragment()

**Comment by ayuwono** [comment]
Verified and the qb.properties() test in test-complete/nodejs-documents-query-2.js is changed to qb.propertiesFragment()
