### ISSUE TITLE
bad link in jsdoc index page

### ISSUE THREAD

**Issue by dsokolsky** [marklogic/node-client-api#138]
From @dmcassel:

There's an incorrect link on this page: http://docs.marklogic.com/jsdoc/index.html
 
•         http://developer.marklogic.com/features/node-api
should be
 
•         http://developer.marklogic.com/features/node-client-api
 
From @dsokolsky:  I would recommend just removing the link to the new features, as that does not seem that appropriate to this page.  Or else replace it with the right one.

**Comment by ehennum** [comment]
Dave already submitted a pull request to fix the bad link.  The page should be fine now.

**Comment by MayankBhatnagar89** [comment]
Hi Erik,

I just verified the issue and found that the page : http://docs.marklogic.com/jsdoc/index.html is still having uri :  http://developer.marklogic.com/features/node-api and it is non functional as clicking on it is throwing 404 error.

However Uri : http://developer.marklogic.com/features/node-client-api is functional but haven't mentioned on page : http://docs.marklogic.com/jsdoc/index.html 

Thanks,
Mayank

**Comment by kcoleman-marklogic** [comment]
Mayank, docs.marklogic.com is only updated when there is a new release of MarkLogic. The right place to verify this is pubs.marklogic.com (where you will find it is, indeed, corrected): http://pubs.marklogic.com:8011/jsdoc/index.html.

Erik, if you want the fix live prior to 8.0-2, you'll have to ask Danny to do a special doc push.

**Comment by ehennum** [comment]
Thanks for confirming, Kim, shipping because it is fixed in the staged doc.

**Comment by ehennum** [comment]
closing because shipped
