### ISSUE TITLE
Question: Can I pass structured JSON to the a queryBuilder?

### ISSUE THREAD

**Issue by clockworked247** [marklogic/node-client-api#139]
If I have the following JSON:

query: { and-query: { queries: [{range-constraint-query: {constraint-name: "tag", value: "testing"}}]} }

Is there a simple way to pass that to queryBuilder and it would "just work"?  QueryByExample seems closest to that, but not quite.  

The alternative seems to be that I would need to traverse the object and generate the queryBuilder specifics depending on what sort of queries and/or queries I come across.

Thanks.

**Comment by ehennum** [comment]
You can't pass a JSON query to the query builder.  The expected model of use is to build up the query in code.

You can pass a JSON combined query definition to the db.documents.query() function.  Please see:

http://docs.marklogic.com/jsdoc/documents.html#query
http://docs.marklogic.com/jsdoc/documents.html#CombinedQueryDefinition

**Comment by clockworked247** [comment]
Great, thanks @ehennum
