### ISSUE TITLE
Document Express set-up

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#140]
[Express](http://expressjs.com) is the most common HTTP server framework. We should document how you'd set up MarkLogic as a backing store for and Express (4) app. This should include:
- Configuration and reuse of database connection
- Mapping application users/roles to database roles)
- [Session storage](withjam/connect-marklogic)
- Wiring up a search box input with a [string query](http://docs.marklogic.com/jsdoc/queryBuilder.html#parsedFrom)

**Comment by jmakeig** [comment]
Any additional input @withjam, @dmcassel, @laurelnaiad?

**Comment by ayuwono** [comment]
I'm playing around with node-express-marklogic right now. I'm able to setup express, connecting it with marklogic. I'm on the point where I can load documents using marklogic through express now

**Comment by dmcassel** [comment]
+1 on documenting this. Might be worthwhile to adopt/enhance/whatever the [connect-marklogic](https://github.com/withjam/connect-marklogic) project as part of the session management.

**Comment by laurelnaiad** [comment]
`connect-marklogic` is looking like a good ingredient, yes. We'll be digging into that area very soon in Samplestack.

**Comment by ayuwono** [comment]
Here is the simple project and examples to setup MarkLogic+Node+Express: https://github.com/ayuwono/ml-node-express

**Comment by ehennum** [comment]
Hi, Kim:  Just assigning to solicit your perspective on this documentation RFE.

For that matter, should we leapfrog Express at this point and go straight to Koa?

**Comment by kcoleman-marklogic** [comment]
This strikes me as a developer.marklogic.com article rather than something for, say, the Node.js Developers Guide, but perhaps I don't understand how this fits in with the rest of our toys.

**Comment by jmakeig** [comment]
As @kcoleman-marklogic interprets, "document integration" doesn't mean in the official product docs. A recipe on [developer.marklogic.com](developer.marklogic.com), a GitHub wiki page, or another repo would all be fine implementations. Koa would be good too, but would complement, not supplant Express.

**Comment by kcoleman-marklogic** [comment]
So, who should this be assigned to?

**Comment by georgeajit** [comment]
Outside the scope of Node API.
