### ISSUE TITLE
Docs unclear on difference between client.documents.read and client.read

### ISSUE THREAD

**Issue by withjam** [marklogic/node-client-api#141]
I think there is a statement in the docs that is backwards.  In the section about managing collections it says the following:

DatabaseClient.read: Read one or more JavaScript objects from the database by URI. Unlike DatabaseClient.documents.read, this method does not return document descriptors. Rather, it returns just the document content, in the same order as the input URIs.

It seems to be the other way around from what I can tell.  Databaseclient.documents.read returns the full document contents, while DatabaseClient.read returns only the descriptors.   

This is on this page of the docs:

http://docs.marklogic.com/guide/node-dev/documents#id_22398

**Comment by ehennum** [comment]
The documentation is right. If DatabaseClient.read() should return the content.

**Comment by ehennum** [comment]
Matt, I'm not able to reproduce this issue on develop, and we do have a unit test for the db.read() shortcut:

https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-quick.js#L103

Can you provide more detail about how to reproduce the issue?  Is there any chance you're writing a document descriptor with the db.write() shortcut (in which case the descriptor would be saved as content)?

FWIW, I did discover there's a bug with double encoding of the defaulted / directory so the generated path of a db.write() shortcut starts with "%2F" -- but that's likely unrelated.

**Comment by kcoleman-marklogic** [comment]
I see it on both branches using the following example. I still haven't tried upgrading my server yet, though, so let me try that and report back.
```javascript
var marklogic = require('marklogic');
var my = require('./my-connection.js');
var db = marklogic.createDatabaseClient(my.connInfo);

db.read('example.json').result(
    function(documentsa) {
      for (var i in documentsa)
        console.log(JSON.stringify(documentsa[i], null, 2));
    }, 
    function(error) {
      console.log(JSON.stringify(error));
    }
);

db.documents.read('example.json').result(
    function(documentsb) {
      for (var i in documentsb)
        console.log(JSON.stringify(documentsb[i], null, 2));
    }, 
    function(error) {
      console.log(JSON.stringify(error));
    }
);
```
When I run that script, I get the following:
```
[
  {
    "uri": "example.json",
    "category": [
      "content"
    ],
    "format": "json",
    "contentType": "application/json"
  }
]
[
  {
    "content": {
      "a": "one",
      "b": "two"
    },
    "uri": "example.json",
    "category": [
      "content"
    ],
    "format": "json",
    "contentType": "application/json"
  }
]
```

**Comment by ehennum** [comment]
Can you provide the code that writes example.json?

**Comment by kcoleman-marklogic** [comment]
I just picked a random document that was lying about in my db, but evidence suggests I created it with the following server-side JS:
```
declareUpdate();
var anObj = {a: 'one', b: 'two'};
xdmp.documentInsert('example.json', anObj);
```

**Comment by kcoleman-marklogic** [comment]
Upgraded server (clean install) to latest nightly and used the above SJS in QC to insert the document.  Got the same results. 

Last thing I'm going to try is blowing away my project node_modules dir and reinstalling the API. My project is very old, so maybe it has strange archaeological artifacts in it.

**Comment by ehennum** [comment]
Thanks for the info -- I'm seeing it too, looking into why the unit test is happy.

**Comment by ehennum** [comment]
The bugs exhibits when the read() is on a single document -- the unit test reads two documents.

**Comment by ehennum** [comment]
This bug was probably introduced by the optimization that skips multipart/mixed response processing when reading a single document.

**Comment by ehennum** [comment]
Regression tests could be a single document write and single document read using the db.createCollection(), db.writeCollection(), and db.read() shortcut functions.

**Comment by withjam** [comment]
Ah, that explains it then.  My use case was also looking up a single document.  Thanks for the follow up info.

**Comment by ayuwono** [comment]
Added tests for single document read and writeCollection on nodejs-documents-quick.js
