### ISSUE TITLE
drain after end event on underlying response as well as multipart finish event

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#143]
The Dicer multipart parser seems to have an elusive bug under load in stress testing where it fails to fire the finish event.  The issue can only be reproduced after a long period under load.

As a workaround, it may be possible to listen for the end event on the underlying HTTP response stream as well as the finish event on the multipart parser.

**Comment by ehennum** [comment]
should be no regressions due to this fix

**Comment by jmakeig** [comment]
Have/should you file an issue with Dicer?

**Comment by ehennum** [comment]
It's hard to reproduce the issue -- it occurs rarely during a stress run.  If I could isolate the cause, I would submit a pull request.

**Comment by ehennum** [comment]
One footnote:  it's possible the root cause is in the StreamSearch dependency of Dicer.

**Comment by ayuwono** [comment]
There is no issue on regression, giving back to Erik as he wants to investigate more on the stress test side

**Comment by ehennum** [comment]
I believe I've isolated the Dicer bug -- testing a fix so I can submit a pull request.

**Comment by ehennum** [comment]
Pull request submitted to Dicer with proposed fix and test.

**Comment by jmakeig** [comment]
You are the man.

**Comment by ehennum** [comment]
Passed a stress test without issues.  

The test environment must upgrade (via npm install) to use Dicer 0.2.4 (the point release incorporating the fix).

If removing the workaround causes no regressions, please ship the issue.

**Comment by ayuwono** [comment]
No regression after Dicer is upgraded to 0.2.4
