### ISSUE TITLE
Method fn.distinctValues() failing in eval on an array

### ISSUE THREAD

**Issue by MayankBhatnagar89** [marklogic/node-client-api#148]
Code : 
***********************************************************
 it('should do javascript eval to call on array', function(done){
    var src = 'var mycars = ["volvo", "nissan", "honda", "volvo", "HONDA"];' +
              'fn.distinctValues(mycars);'
    dbEval.eval(src).
    result(function(values) {
      console.log(values[0].value);
      values[0].value.length.should.equal(4);
      done();
    }, done);
  });

***********************************************************

Should return 4 but returning 5 values.

**Comment by ehennum** [comment]
Please file this as an internal bug on the JavaScript server implementation in BugTrack.

In QConsole, JavaScript and XQuery return different results:

fn.distinctValues(["volvo", "nissan", "honda", "volvo", "HONDA"])

fn:distinct-values(("volvo", "nissan", "honda", "volvo", "HONDA"))

**Comment by MayankBhatnagar89** [comment]
Logged Bug:32680 in Bugtrack under Javascript server implementation for the same. Hence closing this issue now.
