### ISSUE TITLE
accept category of none as array item or string

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#151]
Currently, a category of 'none' is accepted only as a string, but other categories are accepted as array items or strings

**Comment by ehennum** [comment]
Either withOptions({categories: 'none'}) or withOptions({categories: ['none']}) should suppress the documents.

**Comment by ayuwono** [comment]
Hi Mayank, please add this scenario and also the tests around it. Please make sure add the corresponding xml test on scripts/tests harness, and add it to the suite

**Comment by MayankBhatnagar89** [comment]
Added test nodejs-issue-115.js to the repository and regression.
