### ISSUE TITLE
Query for single document invokes error callback [404] if not found

### ISSUE THREAD

**Issue by withjam** [marklogic/node-client-api#153]
This took me by surprise and may be a bug.  When querying by URI for a document that did not exist, rather than get an empty result in the success callback, the API instead invokes the error callback.  I've since modified my code to both check for empty results and read the status code of the error callback, but it seems like it should not require checking in the error callback in this case.

**Comment by ehennum** [comment]
Were you using the documents.query() or documents.read() function?  I'm guessing documents.read()

**Comment by withjam** [comment]
Sorry, should've included some code.  Yes, I am using documents.read.  here is my snippet:

    this.db.documents
      .read(getDocumentUri(sid, this.baseUri))
      .result(function(docs) {
        if (docs && docs.length) {
          debug('returning session document %j', docs[0]);
          callback(null, docs[0].content.session);
        } else {
          callback();
        }
      })
      .catch(function(err) {
        if (err.statusCode && err.statusCode === 404) {
          // don't throw an error, session not found
          callback();
        } else {
          debug('error getting session', err);
          callback(err);
        }
      });

**Comment by ehennum** [comment]
Thanks, Matt, for the additional detail.

Aries, we should consider adding a similar regression test that requests the content (not metadata) for a single document that doesn't exist and receives an empty array.

**Comment by ehennum** [comment]
The content array regression caused by the previous numbskull fix should be gone now.

See above for a suggested regression test.

**Comment by ayuwono** [comment]
Instead of returning an empty array, this is the result when reading non-existent document, and also when requesting the content from a document that doesn't exist.

[
  {
    "content": null,
    "uri": "/test/crud/thisdocumentisnotexist.json",
    "category": [
      "content"
    ],
    "format": "json",
    "contentType": "application/json"
  }
]

**Comment by ehennum** [comment]
Thanks for catching that mistake in the implementation.  It should be an empty array now.

**Comment by ayuwono** [comment]
Verified passed and added tests to nodejs-documents-crud.js
