### ISSUE TITLE
Setting transaction timeLimit is not working

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#156]
After setting the transaction timeLimit to 1 ms, and reading the time-limit value on the transaction status, it's returning 600 instead of 1. Verified on REST API that it's working fine

  // Set transaction time limit to be 1 second
  it('should commit the write document', function(done) {
    db.transactions.open({transactionName: "nodeTransaction", "timeLimit": 1}).result().
    then(function(response) {
      tid = response.txid;
      return db.documents.write({
        txid: tid,
        uri: '/test/transaction/doc1.json',
        contentType: 'application/json',
        content: {firstname: "John", lastname: "Doe", txKey: tid}
      }).result(function(response) {done();}, done);
    })
  });

  // Read about transaction status
  it('should read transaction status', function(done) {
    db.transactions.read(tid).result(function(response) {
      response['transaction-status']['transaction-name'].should.equal('nodeTransaction');
      response['transaction-status']['time-limit'].should.equal('1');

      done();
    }, done);
  });

<testcase classname="Document transaction test" name="should read transaction status" time="0" message="expected '600' to be '1'"><failure classname="Document transaction test" name="should read transaction status" time="0" message="expected '600' to be '1'"><![CDATA[AssertionError: expected '600' to be '1'

**Comment by ehennum** [comment]
I'm not able to reproduce this issue.  I executed the following code:

  var tid = 0;
  db.transactions.open({transactionName: "testTransaction", timeLimit: 1})
  .result(function(response) {
    console.log(JSON.stringify(response));
    tid = response.txid;
    return db.transactions.read(tid).result();
    })
  .then(function(response) {
    console.log(JSON.stringify(response));
    return db.transactions.rollback(tid).result();
    })
  .catch(function(error) {
    console.log(error);
    });

and see the following response:

{"transaction-status":{"host":{"host-id":"7930918965031655651","host-name":"localhost.localdomain"},"server":{"server-id":"16732949767967762807","server-name":"unittest-nodeapi"},"database":{"database-id":"4119333449986927428","database-name":"unittest-nodeapi"},"transaction-id":"7255832875114662346","transaction-name":"testTransaction","transaction-mode":"update","transaction-timestamp":"0","transaction-state":"idle","canceled":"false","start-time":"2015-03-19T11:30:34-07:00","time-limit":"1","max-time-limit":"3600","join-size":"0","user":"14103995686357427740","admin":"false"}}

Debug logging also shows that the parameter is being provided:

    /v1/transactions?name=testTransaction&timeLimit=1

Is it possible the read test is getting the status for a different transaction?

**Comment by ayuwono** [comment]
Hi Erik, this code returns timeLimit = 600 although I set it to 1 when I open the transaction. The different is I use the transaction id for document write before reading the transaction status

var tid = 0;
db.transactions.open({transactionName: "testTransaction", timeLimit: 1})
.result(function(response) {
  console.log(JSON.stringify(response, null, 2));
  tid = response.txid;
  return db.documents.write({
    txid: tid,
    uri: '/test/transaction/doc1.json',
    contentType: 'application/json',
    content: {firstname: 'John', lastname: 'Doe', txKey: tid}
  }).result();
})
.then(function(response) {
  console.log(JSON.stringify(response, null, 2));
  return db.transactions.read(tid).result();
})
.then(function(response) {
  console.log(JSON.stringify(response, null, 2));
  return db.transactions.rollback(tid).result();
})
.catch(function(error) {
  console.log(error);
});

Result:
{
  "txid": "6129098586367786767"
}
{
  "documents": [
    {
      "uri": "/test/transaction/doc1.json",
      "contentType": null
    }
  ]
}
{
  "transaction-status": {
    "host": {
      "host-id": "8058552232680913170",
      "host-name": "ayuwono-z620.marklogic.com"
    },
    "server": {
      "server-id": "16941984731415105324",
      "server-name": "node-client-api-rest-server"
    },
    "database": {
      "database-id": "4180619797282920141",
      "database-name": "node-client-api-rest-server"
    },
    "transaction-id": "6129098586367786767",
    "transaction-name": "testTransaction",
    "transaction-mode": "update",
    "transaction-timestamp": "0",
    "transaction-state": "idle",
    "canceled": "false",
    "start-time": "2015-03-19T14:37:53-07:00",
    "time-limit": "600",
    "max-time-limit": "3600",
    "join-size": "0",
    "user": "14103995686357427740",
    "admin": "false"
  }
}

**Comment by ayuwono** [comment]
Related to bug 32779

**Comment by ehennum** [comment]
Thanks for isolating that and tracking it down.

**Comment by ayuwono** [comment]
Not related to 32779 but to 32826

**Comment by ayuwono** [comment]
Bug 32826 is shipped
