### ISSUE TITLE
eval function only executes against the Documents database

### ISSUE THREAD

**Issue by lonhutt** [marklogic/node-client-api#158]
regardless of what's fed to the createDatabaseConfig function any execution of the eval function will only be run against the Documents DB.

I put together the following script to help reproduce the problem:

```javascript
var marklogic = require("marklogic");
var util = require('util');

var db = marklogic.createDatabaseClient({
  host: 'localhost',
  port: '8000',
  database: 'Meters',
  user: 'admin',
  password: 'admin'
});

db.eval('fn.doc()').result(function(resp){
	console.log(resp[0].value.toString());
});
```
I am running this on ML 8.0-1.1 on OSX

**Comment by ehennum** [comment]
Thanks, Lon, for catching this problem.

The regression test, Aries, might be an eval to the Documents database and then to the Modules database with an expression that yields the database name so the database name can be confirmed in the Mocha should assertion within the callback, as in:

db.eval('xdmp.databaseName(xdmp.database());').result(...);

**Comment by ayuwono** [comment]
Verified and added tests to nodejs-javascript-eval.js
