### ISSUE TITLE
Role-based security using a single connection

### ISSUE THREAD

**Issue by withjam** [marklogic/node-client-api#159]
Not sure how to title this, but would like support for passing user credentials into an existing connection.  Prior to the Node API we would proxy requests via Node to MarkLogic's REST API.  Each request was modified to pass in an auth header based on the currently logged in user so that it would apply that user's roles.  The pattern looked something like this:

(guest user in UI) AUTH: default ML user [typically just a rest-reader] -> proxy -> ML
(user log in attempt) AUTH: user credentials -> proxy -> ML
(successful login) AUTH: user credentials -> proxy to lookup user profile ->  ML
(subsequent requests from that session) AUTH: user credentials -> proxy -> ML

With the Node API, a connection is instead established as a privileged user and that connection is held at the app level.  When an authentication request is received, it should apply some business logic at the Node layer and decide if the user is allowed.  From that point on, it would be nice to pass in that user's credentials (or a token if easier) whenever subsequent requests are made from that same session so that any ML operations are done AS that user instead of as the privileged user of the connection.

I believe this is somewhat of a unique pattern for MarkLogic because of our security model.  I've not done such a thing with other solutions so I'm not sure of the best way to handle it.  The only thing I can think of is passing in a user and password as options to each dbClient operation.   But I don't know how costly or simple such an implementation that would be. 

Any suggestions or recommendations either as a best practice or enhancement request?

**Comment by ehennum** [comment]
If I understand correctly, today you would need to create a separate connection for each user.  I can see that, with a large number of different users, that's not desirable.

One possibility would be to keep a hash of authenticated users at the Node.js layer so we could reuse the DIGEST nonce in subsequent requests, but that's a premature speculation.  I expect Justin will want to drill down with you to understand the specifics of the requirement including the proxying.

**Comment by joemfb** [comment]
FYI, @withjam's use case is implemented in https://github.com/marklogic/slush-marklogic-node/blob/master/app/templates/server.js.

I've used a variation of that, where I had a default user, and default privileged-user (for conditional, privileged requests), and then the option to authenticate as an arbitrary user. An enhancement that would cover all these use cases would be to allow individual requests to be run as a different user (analogous to `su $USER -c $COMMAND` in *nix systems). I don't think it would need to be stateful (i.e., run all future requests as `$USER`).

For comparison PostgreSQL allows user to statefully modify the connection user/privileged:

- http://www.postgresql.org/docs/current/static/sql-set-role.html
- http://www.postgresql.org/docs/current/static/sql-set-session-authorization.html

**Comment by withjam** [comment]
Keeping a connection per user doesn't sound like something that would scale well, but maybe that assumption is something worth testing.  Holding onto a nonce per session seems like more trivial overhead.  That sounds like an interesting option to me.

**Comment by ehennum** [comment]
@joemfb  -- thanks for the link and additional input.

@withjam -- each client object has a separate connection pool, so keeping the nonce per user would much lighter weight. Of course, we also need to think through the SSL implications.

**Comment by jmakeig** [comment]
I think SAML authentication is how we’d handle the general case here. Closing in favor of #513.
