### ISSUE TITLE
Verbose & confusing error when expanded tree cache is full

### ISSUE THREAD

**Issue by csreddy** [marklogic/node-client-api#161]
This is probably not a node client bug. I'm not sure if you can change this at node layer. So feel free to close this. 
I get this error message when the search result is too big
The message is particularly confusing because it contains many error codes ````XDMP-EXPNTREECACHEFULL````, ````REST-UNSUPPORTEDPARAM````, ````REST-UNACCEPTABLETYPE```` etc
Here's the message I see for ````error.body.errorResponse.message```` in the client
````XDMP-EXPNTREECACHEFULL: let $rule := conf:get-search-query-request-rule() let $headers := eput:get-request-headers() let $accept := eput:get-accept-types($headers) let $method := eput:get-request-method($headers) let $params-in := eput:get-request-params($rule, $method, $headers) let $env := eput:response-callback-map(eput:response-type-callback#1) let $params := eput:check-param-names($rule, $env, $params-in, $method, "^(trans:)") return (logger:dump-request-environment((sut:log-effective-options#1, searchmodq:log-cts-query#1), $params-in), if (fn:empty($accept)) then () else if ($accept = ("application/json", "text/json", "application/xml", "text/xml")) then if (map:contains($params, "category")) then fn:error((), "REST-UNSUPPORTEDPARAM", "Can use the 'category' parameter only with multipart/mixed accep...") else let $view := map:get($params, "view") return if (fn:not($view eq "none")) then () else fn:error((), "REST-UNSUPPORTEDPARAM", "Can use the 'none' value for the 'view' parameter only with mult...") else if (fn:starts-with(fn:head($accept), "multipart/mixed")) then map:put($env, "add-header", eput:add-response-header#2) else fn:error((), "REST-UNACCEPTABLETYPE", fn:string-join($accept, ", ")), if ($method eq "GET") then let $response := searchmodq:search-get($headers, $params, $env) let $has-matches := map:get($env, "has-matches") return if (fn:exists($response)) then $response else if ($has-matches) then () else xdmp:set-response-code(404, "Not Found") else if ($method eq "POST") then let $response := searchmodq:search-post($headers, $params, $env, xdmp:get-request-body(eput:get-content-format($headers, $params))) let $has-matches := map:get($env, "has-matches") return if (fn:exists($response)) then $response else if ($has-matches) then () else xdmp:set-response-code(404, "Not Found") else fn:error((), "REST-UNSUPPORTEDMETHOD", $method)) -- Expanded tree cache full on host engrlab-128-048.engrlab.marklogic.com . See the MarkLogic server error log for further detail.````

**Comment by ehennum** [comment]
Hi, Sudhakar -- as you suspected, error message mapping is an issue on the REST API level, so the bug should be filed on the internal bug tracking system with information about how to reproduce the problem.

**Comment by csreddy** [comment]
Alright thanks Erik
