### ISSUE TITLE
Adding process.env.NODE_ENV = 'development' throws Promise.then() warning

### ISSUE THREAD

**Issue by tamaspiros** [marklogic/node-client-api#162]
Adding `process.env.NODE_ENV = 'development';` to a node.js application causes a warning similar to this one appearing:

Warning: .then() only accepts functions but was passed: [object Undefined], [object Undefined]
    at Operation.operationResultPromise (/Users/tamaspiros/Desktop/projects/marklogic/node_modules/marklogic/lib/mlrest.js:1571:18)
    at Object.callBackMethod [as result] (/Users/tamaspiros/Desktop/projects/marklogic/node_modules/marklogic/lib/mlutil.js:132:17)
    at selectOneDocument (/Users/tamaspiros/Desktop/projects/marklogic/app.js:14:33)
    at Object.<anonymous> (/Users/tamaspiros/Desktop/projects/marklogic/app.js:25:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

Regardless of this warning the data is still returned. You can test this by running the following sample code:

    var marklogic = require('marklogic');
    var connection = {
      host: 'localhost',
      port: XXXX, //port
      user: 'admin',
      password: 'admin'
    };
    var db = marklogic.createDatabaseClient(connection);
    var selectOneDocument = function() {
      var uri = XXX; //replace with VALID URI
      return db.documents.read(uri).result();
    };
    var resolve = function(document) {
      console.log(document);
    };
    var reject = function(error) {
      console.log(error);
    }
    selectOneDocument().then(resolve, reject);

Modifying the code to the following yields no warnings:

    var resolve = function(document) {
      console.log(document);
    };

    var reject = function(error) {
      console.log(error);
    }

    var selectOneDocument = function() {
      var uri = 'XXXX'; //URI
      db.documents.read(uri).result(resolve, reject);
    };

    selectOneDocument();

This behaviour has been noticed after upgrading the nodejs-client-api from v1.0.1 to v1.0.2

**Comment by ehennum** [comment]
Thanks for finding this issue and isolating it to NODE_ENV.  

It appears that NODE_ENV of develop turns on debugging in Bluebird:

https://github.com/petkaantonov/bluebird/blob/master/src/debuggability.js#L12

I'm wondering if the promise success and failure functions get used in the standard flow of control but not in the debugging flow of control (accounting for the observed behaviour of success with logged errors).

We are extending Bluebird (per Bluebird recommendations):

https://github.com/marklogic/node-client-api/blob/develop/lib/bluebird-plus.js

I'm wondering if Bluebird debugging doesn't like extensions.

**Comment by tamaspiros** [comment]
I have done some additional debugging/testing and this is what I found:

- I have added two console.log statements just before this line https://github.com/marklogic/node-client-api/blob/master/lib/mlrest.js#L1571
`console.log(fullfilled);`
`console.log(rejected);`

 and those return `undefined`

- I have replaced the bluebird dependency inside the node-client-api and found that the warning started to show up at version 2.9.5

- Both v2.9.4 and v2.9.5 return `undefined` for the previously mentioned console.log statements, however the diff between the bluebird versions show that a warning function was added to the library: https://github.com/petkaantonov/bluebird/compare/v2.9.4...v2.9.5

Therefore I am guessing that this 'error' was always there except due to an update to the bluebird library it is now displayed.

I am still wondering however why both `console.log()` statements yield `undefined` when the resolve/reject functions are passed to the `.then()` method instead of `.result()` and yields `[Function]` when `.result()` is being used.

**Comment by ehennum** [comment]
The result() function was passing through the success and failure functions to the Promises library whether defined or not. That is allowed by the standard:

https://promisesaplus.com/#point-23

Despite the alarming stacktrace, Bluebird was only emitting a debug warning when the process development flag was set.

Still, better to avoid the warning, so the result() function now passes the success and failure functions only when defined.

A good regression test might do the following:

1.  Set the process development flag before requiring any modules:

    process.env.NODE_ENV = 'development';

2.  call result().then(...) on any request (which should no longer emit a warning with this fie)
3.  set the produces development flag to undefined so it doesn't affect subsequent tests

**Comment by ayuwono** [comment]
Verified passed, added nodejs-process-env.js test
