### ISSUE TITLE
stream chunking fails for very large documents

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#163]
Reported in:

http://stackoverflow.com/questions/29691353/read-the-large-document-using-marklogic-nodejs-api

**Comment by ehennum** [comment]
A regression test could use a large document such as the concatenated plays of shakespeare (without the DTD and XML prolog and with a root element containing all of the PLAY elements).

**Comment by ayuwono** [comment]
Verified passed and added test: nodejs-documents-write-large.js
