### ISSUE TITLE
Inconsistent property names across apis

### ISSUE THREAD

**Issue by csreddy** [marklogic/node-client-api#166]
While the ```db.documents.read()``` takes object with property ```uris``` , for example  ``` db.documents.read({uris: [uri1, uri2]}``` but ```db.documents.remove()``` takes ```uri``` as the property. ex: ```db.documents.remove({uri: [uri1, uri2]}``` Need to be consistent across different apis which take array of uris. I think ```uris``` should be the correct name. I noticed this difference only between read() & remove() but could be prevalent in other areas as well

**Comment by ehennum** [comment]
Hi, Sudhakar:  The difference was deliberate.  In the initial release, db.documents.remove() could only take a single URI.  In the impending release, db.documents.remove() can take multiple uris, so the plural form is supported.
