### ISSUE TITLE
db.documents.remove() response: removed is always true

### ISSUE THREAD

**Issue by dmcassel** [marklogic/node-client-api#169]
Given a delete request: 

    db.documents.remove(
      '/foo.json'
    ).result()
      .then(function(response) {
        console.log('Document ' + response.uri + ' was ' + (response.removed ? '' : 'not ') + 'removed.' );
      })
      .catch(function(error) {
        console.log('Failed to delete document: ' + error);
      });

The response object provides the URI (a string) and a removed property (boolean). The removed property is true whether the document existed at the time of the delete request or not. If the request to delete the document failed, I'd expect that to go to the catch, so I'm not sure what removed is telling me. Bug?

**Comment by kcoleman-marklogic** [comment]
I believe this is WAI. Delete never "fails" because a document doesn't exist. It's an idempotent operation. It's just like in REST and Java. I'm not saying you're wrong to question the value of the returned info, though. :)

**Comment by dmcassel** [comment]
Related: the Guide says that .remove()'s response will have a property called "exists" rather than "removed". The API docs says the [removeResult](http://docs.marklogic.com/jsdoc/documents.html#removeResult) gets a "sparse document descriptor". The DocumentDescriptor documentation doesn't list either "exists" or "removed".

**Comment by dmcassel** [comment]
Makes sense, @kcoleman-marklogic. Might be move valuable to return "existed", indicating the previous state.

**Comment by ehennum** [comment]
As Kim points out, the REST API doesn't distinguish between non-existent and successfully deleted documents because the delete operation is supposed to be idempotent.

The exists property is consistent with the probe() request.  Changing it now would create a backward incompatibility.

**Comment by dmcassel** [comment]
Works for me.
