### ISSUE TITLE
score() function not setting search options

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#172]
The QueryBuilder score() function should be able to specify the scoring method, which should be implemented by setting the search options when the request is made.

Currently, the scoring method is emitted as textual content for the score, which is invalid for the schema.

The workaround is to set the score in the search options instead using the withOptions() clause

**Comment by ehennum** [comment]
qb.score('logtfidf' | 'logtf' | 'simple' | 'random' | 'zero') should set the score method (prepending 'score-') in the search:search-options.

Unit tests are in test-basic/query-builder.js and test-basic/documents-query.js

**Comment by MayankBhatnagar89** [comment]
qb.score('logtfidf' | 'logtf' | 'simple' | 'random' | 'zero') is working as expected with every argument.
I have added test in nodejs-documents-query-facet.js and they are running fine, hence shipping this issue. 
https://github.com/marklogic/node-client-api/commit/dd4e887bed24ec1b2289633d166ea8e7e18c51f1
