### ISSUE TITLE
an error without an error callback emits a spurious Bluebird error

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#173]
The spurious error is:

node_modules/bluebird/js/main/async.js:36
        fn = function () { throw arg; };

The root error is still reported.  In addition, the application should provide an error callback for better error reporting.

A quick search shows that the request module found a configure solution:

https://github.com/request/request-promise/commit/bc6080e501a406eb03ec779dd50458cde1bce7aa

But more investigation is needed.

**Comment by georgeajit** [comment]
Decided to replace Bluebird with native V8 promises.
