### ISSUE TITLE
REGR: SPARQL query against the merged graph failing 

### ISSUE THREAD

**Issue by MayankBhatnagar89** [marklogic/node-client-api#174]
Build : MarkLogic-8.0-20150623

Test : nodejs-graphs-merge.xml

Code : 
********************************************************
var should = require('should');
var fs = require('fs');
var valcheck = require('core-util-is');
var testconfig = require('../etc/test-config-qa.js');
var marklogic = require('../');
var q = marklogic.queryBuilder;
var db = marklogic.createDatabaseClient(testconfig.restWriterConnection);

describe('merge graph test', function(){
  var graphUri   = 'marklogic.com/merge/people';
  var graphUriInv   = 'marklogic.com/invalid';
  var graphPath1  = './node-client-api/test-complete/data/people3.ttl';
  var graphPath2  = './node-client-api/test-complete/data/people4.ttl';
  var sparqlPath = './node-client-api/test-complete/data/people.rq';
  it('should run a SPARQL query against the merged graph', function(done){
    this.timeout(10000);
    db.graphs.sparql('application/sparql-results+json', fs.createReadStream(sparqlPath)).
    result(function(response){
      response.should.have.property('head');
      response.head.should.have.property('vars');
      response.head.vars.length.should.equal(2);
      response.head.vars[0].should.equal('personName1');
      response.head.vars[1].should.equal('personName2');
      response.should.have.property('results');
      response.results.should.have.property('bindings');
      var strResponse = JSON.stringify(response);
      //console.log(strResponse);
      strResponse.should.containEql('Person 2');
      strResponse.should.containEql('Person 12');
      done();
    }, done);
  });

  it('should delete the merged graph', function(done){
    this.timeout(10000);
    db.graphs.remove(graphUri).
    result(function(response){
      done();
    }, done);
  });
});
******************************************************************************

Expected output of SPARQL query : 
******************************************************************************
{"results":{"bindings":[{"personName1":{"value":"Person 9","type":"literal","lang":"http://www.w3.org/2001/XMLSchema#string"},"personName2":{"value":"Person 12","type":"literal","lang":"http://www.w3.org/2001/XMLSchema#string"}},{"personName1":{"value":"Person 1","type":"literal","lang":"http://www.w3.org/2001/XMLSchema#string"},"personName2":{"value":"Person 2","type":"literal","lang":"http://www.w3.org/2001/XMLSchema#string"}}]},"head":{"vars":["personName1","personName2"]}}
******************************************************************************

Actual Output : 
******************************************************************************
{"results":{"bindings":[]},"head":{"vars":["s","p","o","g"]}}
******************************************************************************

**Comment by ehennum** [comment]
Possibly the result of work on the SPARQL REST API endpoint?

**Comment by grechaw** [comment]
I think I understand how this runs a query.
It could be an issue with loading data, or with the query.  I'll see whether I can reproduce this empty result using the query.  
Watching the logs whilst running this test will also be interesting.  I may come asking node questions.

**Comment by grechaw** [comment]
Hi Mayank, I got this running.  If this is the output (and it is) then has the issue gone away?  It's quite possible that you hit an issue that has since been resolved.

```
cgreer@cgreer-laptop:~/source$ mocha node-client-api/test-complete/nodejs-graphs-merge


  merge graph test
    ✓ should write the first graph (556ms)
    ✓ should merge the graph (382ms)
    ✓ should check the merged graph
    ✓ should list the merged graph
    ✓ should run a SPARQL query against the merged graph (1423ms)
    ✓ should delete the merged graph


  6 passing (2s)
```

**Comment by MayankBhatnagar89** [comment]
Agreed Charles , the issue is no more producible and the test is running fine on all platforms.
Hence closing this bug.
