### ISSUE TITLE
qb.near doesn't give the right result

### ISSUE THREAD

**Issue by tamaspiros** [marklogic/node-client-api#175]
Observed in:
- node-client-api v1.0.2 / v1.0.3
- marklogic v 8.0-3

I have issues running a qb.near() search as it doesn't seem to be returning the expected results.

Given the following sample document in the database:

`{ "text": "MarkLogic Server is an enterprise-class database." }`

and the following application code:

```javascript
'use strict';
var marklogic  = require('marklogic');
var connection = {
  host: 'localhost',
  port: 7050,
  user: 'admin',
  password: 'admin'
};
var db = marklogic.createDatabaseClient(connection);
var qb = marklogic.queryBuilder;

db.documents.query(
  qb.near(
    qb.term('marklogic'),
    qb.term('database'), 1
  )
).result().then(function(response) {
  console.log(response);
});
```

I'd expect the above code to return 0 results as the term marklogic is not 1 term away from database. However the test document is being returned. I have tried a few combinations but none of them seemed to work and they have all returned the test document:

```javascript
db.documents.query(
  qb.near([
    qb.term('marklogic'),
    qb.term('database')], 1
  )
)
```

```javascript
db.documents.query(
  qb.where(
    qb.near(
      qb.term('marklogic'),
      qb.term('database'), 1
    )
  )
)
```

```javascript
db.documents.query(
  qb.where(
    qb.near([
      qb.term('marklogic'),
      qb.term('database')], 1
    )
  )
)
```

**Comment by ayuwono** [comment]
If we use filtered on search options, it will return 0 doc. If we change the distance to 6, it will return the test doc

'use strict';
var marklogic  = require('../');
var connection = {
  host: 'localhost',
  port: 7050,
  user: 'admin',
  password: 'admin'
};
var db = marklogic.createDatabaseClient(connection);
var qb = marklogic.queryBuilder;

db.documents.query(
  qb.where(
    qb.near(
      qb.term('marklogic'),
      qb.term('database'), 1
    )
  ).withOptions({search:['filtered']})
).result().then(function(response) {
  console.log(response);
});

**Comment by ehennum** [comment]
As a footnote on the sensible comment by Aries, indexing word positions is necessary for determining near based on the indexes instead of during filtering (the http://docs.marklogic.com/cts:near-query page has more)

**Comment by tamaspiros** [comment]
@ayuwono that works - thank you!
