### ISSUE TITLE
Geolocation facet does not work at all

### ISSUE THREAD

**Issue by victorbalan** [marklogic/node-client-api#176]
Marklogic version: 8.0-2
Node api version: 1.0.3

I have created all the possible geolocation indexes and the code i tried is.

```javascript
qb.facet("count", qb.property("geolocation"))

qb.facet("count", qb.geoPropertyPair("geolocation", "lat", "lng"))

qb.facet("count", qb.geoProperty("geolocation"))

qb.facet("count", qb.geoElement("geolocation"))
```

Stackoverflow question answered by @ehennum  stating the bug: [http://stackoverflow.com/questions/30645397/marklogicnodejs-api-facet-query-by-geolocation]

**Comment by ehennum** [comment]
As noted in the StackOverflow response, the bug is in the REST API.

**Comment by ehennum** [comment]
The fix for the REST API was checked in under internal bug 33964.

**Comment by ehennum** [comment]
The unit test confirmed that geospatial facets works for a simple JSON point.  It might be useful to add a few other kinds of JSON geospatial facets to the complete regression.

**Comment by MayankBhatnagar89** [comment]
Tests added to regression under : https://github.com/marklogic/node-client-api/commit/15e18dd2e3a3f0a73f66f4405d38e823b629861e
