### ISSUE TITLE
Document streaming behavior

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#178]
Which requests stream under which conditions?

**Comment by kcoleman-marklogic** [comment]
Pushing out since I have no info with which to fulfill this task. I have a query out to Sam and Erik, and will pull it back in to 8.0-4 if I can get what I need in time. Setting to 9.0-1 since there is currently no 8.0-5 milestone.

**Comment by kcoleman-marklogic** [comment]
Mike, if you get time during the 9.0-2 cycle, please let me know what I should say about this in the documentation. Or defer it to 9.0-3. This is a doc issue, so it's not tied to the 9.0-2 freeze date.

If you need more details on the question being answered, please ask Justin.

**Comment by georgeajit** [comment]
Node developers know that a readable stream means we are streaming. Closing the issue.
