### ISSUE TITLE
Document connection pooling behavior and configuration

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#179]
How does connection pooling work? What are its defaults? What are the levers available to modify its behavior?

**Comment by kcoleman-marklogic** [comment]
Pushing out since I have no info with which to fulfill this task. I have a query out to Sam and Erik, and will pull it back in to 8.0-4 if I can get what I need in time. Setting to 9.0-1 since there is currently no 8.0-5 milestone.
