### ISSUE TITLE
Support XML QBE as string

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#180]
The REST API added support for posting a QBE multipart under bug 33745.  The Node.js API can now take advantage of that capability.

**Comment by ehennum** [comment]
The checkin added two tests to test-basic/documents-query.js to verify that byExample() can take either an XML QBE as a string or a JavaScript QBE with a $format property of 'xml'

**Comment by MayankBhatnagar89** [comment]
I have written few tests in nodejs-documents-qbe.js and have added it to regression 
Link:  https://github.com/marklogic/node-client-api/commit/1a6e520123a6d12b088ce6a433fd9b5629cd40ba
