### ISSUE TITLE
validate and execute QBE

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#181]
In the REST API, QBE can support a request that validates the query first and then executes the query.  That's useful during development.

The Node.js API should expose this capability.

**Comment by ehennum** [comment]
See the "should report an invalid query" test in test-basic/documents-query.js for an example of checking an invalid query.  

A valid query should generate the same output with the $validate: true property (but run a little slower).

**Comment by MayankBhatnagar89** [comment]
Verified and added test to regression under test : nodejs-documents-qbe.js
https://github.com/marklogic/node-client-api/commit/e56337f4ac86bd6372b531bfd3f75af2ed6f82c5
