### ISSUE TITLE
Patch builder conveniences for patching metadata 

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#182]
The Java API has convenience methods to make it easy to patch metadata.

The Node.js API should provide similar conveniences.

**Comment by ehennum** [comment]
The interface as exercised by the unit test:

      db.documents.patch({uri:uri2, categories:['metadata'], operations:[
          p.collections.add('collection2/ADDED'),
          p.collections.remove('collection2/0'),
          p.permissions.add(
              {'role-name':'app-user', capabilities:['read']}
              ),
          p.permissions.replace(
              {'role-name':'app-builder', capabilities:['read', 'update']}
              ),
          p.permissions.remove('manage-user'),
          p.properties.add('propertyADDED', 'property value ADDED'),
          p.properties.replace('property1', 'property value MODIFIED'),
          p.properties.remove('property0'),
          p.quality.set(2)
          ]})

Other than edge cases, I'm not sure there's a whole lot more to cover.

**Comment by ehennum** [comment]
Added support for the following shortcuts for consistency with similar operations:

          p.permissions.add('app-user', 'read'),
          p.permissions.replace('app-builder', ['read', 'update']),

The permissions.add() and permissions.replace() functions continue to support the 'role-name' and 'capabilities' named parameters as an alternative as show in the comment for the original check-in.

Also added client-side validation on the capabilities.

**Comment by MayankBhatnagar89** [comment]
Verified and added test to regression : https://github.com/marklogic/node-client-api/commit/75900eed7db8bf0a46df1829b475bdd55ae25835
