### ISSUE TITLE
opt-in flag on root object for zero-based slices

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#183]
The query and values builders have a slice method that's one-based for consistency with paging in the Search API.

There is, however, a more important precedent in Array.prototype.slice()

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/slice

To support migration toward consistency in MarkLogic 8.0-4, the marklogic object should add a config({slice: 'array'|'legacy'}) method for opting into slice consistent with Array.  Then, in MarkLogic 9,  the default should become 'array' but the config() method should support opting into legacy slice.

**Comment by ehennum** [comment]
test-basic/query-builder.js has a unit test for array-compatible slice() for queries.

A good regression test would set an equivalent array-compatible slice() for values on the marklogic require object.

**Comment by MayankBhatnagar89** [comment]
Automation addted to test : nodejs-documents-query-slice.js 

https://github.com/marklogic/node-client-api/commit/2705ccbb1cb6fd18f24097419ae0c5f937c40cbd

Thanks,
Mayank
