### ISSUE TITLE
Support for "collection" parameter on search endpoints?

### ISSUE THREAD

**Issue by malteseduck** [marklogic/node-client-api#184]
In the REST API documentation for both /v1/qbe and /v1/search there is the option of passing a "collection" parameter (or multiple) to limit the results to the specified collection(s).  If I am using QueryBuilder I can use qb.collection() to specify collections.  If I am using qb.byExample() I am not able to do this, nor can I seem to find a way to pass the collection in so it can be passed along to the endpoint.  

I notice in documents.js that queryDocumentsImpl() accepts a collectionParam, but it is hard-coded to null.  Plus, it only accepts one value, where the endpoint accepts many.  

Were there any plans to expose this ability to pass collections, or is there already a way to do this for QBE and I have missed it?  Not a major issue since we can do it with QueryBuilder, just wanted to point it out, thanks.

**Comment by malteseduck** [comment]
I see qb.queryCollection() now - but it still only takes one parameter?  Or can multiple be passed?

**Comment by ehennum** [comment]
Hi, Chris:  Thanks for raising the issue about the current limitations.  

I'm thinking that the right solution would be for the where() clause to accept zero-or-one query string, zero-or-one QBE, and zero-or-more query-builder built queries.  Would that meet your requirements?

If so, it will require an enhancement to the REST API.

On the other question, qb.queryCollection() should take one-or-more URIs.

**Comment by malteseduck** [comment]
If I understand your proposal, I would be able to do a query similar to this:

db.documents.query(
    qb.where(
        qb.parsedFrom('big AND mean'),
        qb.byExample({ type: 'dog' }),
        qb.collection('animals'),
        qb.value('color': 'black')
    )
).result(....);

?  If so that would be useful so we can have a little more flexibility when building queries.  I am trying to see if qb.queryCollection() does what we need it to do and gives us both the simplicity and flexibility we need.  If it is easy to add the functionality for combining queries then it definitely is more flexible, though, so might be nice to add.  There may be other cases we run into later on as we use this more and having the flexibility there would be good.  If it is a pain in the rear then don't add it yet on our account.

As far as qb.queryCollection(), I noticed here:

https://github.com/marklogic/node-client-api/blob/develop/lib/documents.js#L1474

that it only sets up one parameter to the endpoint string for the request, but even before then:

https://github.com/marklogic/node-client-api/blob/develop/lib/marklogic.js#L410

it checks to make sure the passed collection is just a string, and it doesn't seem to take an array (I double-checked on the develop branch because master was similar and I wanted to make sure you hadn't already "fixed' it). Am I misinterpreting what this code is doing?  The REST API already supports  multiple collections, so is this just an oversight in the client code?

**Comment by ehennum** [comment]
Yes, that's the proposal -- thanks for intuiting.  It will require some rewiring on the REST API, so the fix would have to catch a server release train.
 
Sorry, I misread the previous question as about qb.collection() instead of db.queryCollection().  

The db.*Collection() functions all take a single collection, which is intended to serve as the moral equivalent of a table for adopters who are getting started. We don't plan to support multiple collections in those calls because we want to keep that level of the interface simple.

**Comment by malteseduck** [comment]
Ok, that makes sense.  It would be nice to have the flexibility to mix up the types of queries, so if you could add that it would be nice.

Thanks.

**Comment by ehennum** [comment]
Footnote on the thread:  the issue is now tracked on the REST API as internal bug 34889

**Comment by ehennum** [comment]
Implemented in the REST API for 9.0-3, so this feature can be supported in the Node.js API thereafter.
