### ISSUE TITLE
can't combine explicit snippet and extract (regression)

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#186]
The fix that added an option for zero-based indexing introduced a regression by limiting the slice() clause to 3 arguments (which is correct for values but not documents).

**Comment by ehennum** [comment]
A good regression test would confirm that a documents slice() clause can list snippet, extract, and transform definitions.

We might already have such a test.

**Comment by MayankBhatnagar89** [comment]
The test to keep check on the code is in 
test-complete/nodejs-documents-query-facet.js
