### ISSUE TITLE
fromIndexes() should wrap field() in range()

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#187]
Related to the fix for Search API bug 34955 -- the fromIndexes() clause should treat field() in the same way as element() and property() and nest the index in a range() declaration.

**Comment by ehennum** [comment]
Should not cause any regressions on tests with 

values.read(valuesBuilder.fromIndexes(valuesBuilder.field('A_FIELD_WITH_A_RANGE_INDEX')))

**Comment by MayankBhatnagar89** [comment]
I have verified the bug and have added test to regression : https://github.com/marklogic/node-client-api/commit/98e21616090ddc4b6b004b009c4d2251d86232a3
