### ISSUE TITLE
total is missing when qb.where(...).slice(0,0,qb.snippet())

### ISSUE THREAD

**Issue by brightgarden** [marklogic/node-client-api#189]
### Description

When the query parameter "view=results" is passed along with a query parameter "pageLength=0" the response is missing the "total" property (possible bug in REST-API?).

This happens if you set the pageLength to zero, but specify qb.snippet().

### Node Code

    qb.where(
      qb.parsedFrom("Australia")
    )
    .slice(1,0, 
      qb.snippet()
    )
    .withOptions({ categories: "none" })

### Possible solution
What if the [condition adding the "view=results" with the snippet](https://github.com/marklogic/node-client-api/blob/master/lib/documents.js#L1624-L1628) could be predicated on pageLength > 0. Alternatively, narrow the condition to "view=results" only if the pageLength > 0.

      if (pageLength > 0 && !valcheck.isNullOrUndefined(transformResults)) {
        searchOptions['transform-results'] = transformResults;
        searchOptions['return-results']    = true;
        view = 'results';
      }

As it happens, according to my tests against the REST-API (MarkLogic 8.0-3), adding the transform-result and return-result to the request body don't matter. But if pageLength=0 and view=results, the response is not very useful:

    {
	    "snippet-format": "snippet",
	    "start": 1,
	    "page-length": 0,
	    "results": [],
	    "qtext": "Australia"
    }

Merely removing the "view=results" from the query parameters yields this, which is much better:

    {
	    "snippet-format": "snippet",
	    "total": 87,
	    "start": 1,
	    "page-length": 0,
	    "results": [],
	    "qtext": "Australia",
	    "metrics": {
		    "query-resolution-time": "PT0.037698S",
		    "snippet-resolution-time": "PT0S",
		    "total-time": "PT0.03821S"
	    }
    }

I would suggest updating documentation to tell developers not to combine a 0-length page with a snippet transform, but humans are notoriously difficult to program and buggy to boot.

### Side question: 
Why do metrics come back even if you don't ask for them (although sometimes they don't come back at all, so you should ask for them anyway)?

#### Just so you know...
This issue isn't blocking me, but it tripped me up, and probably would be nice to future developers if they didn't have to deal with always having to do the precheck in their own code to add or omit the qb.snippet() if the pageLength requested happened to be zero or not. Most online examples show the code being passed in as parameters like this:

    qb.slice(1, 10, qb.snippet());

It isn't obvious that you can pass it in as an array:

    var sliceOptions = [pageStart, pageLength];
    if (pageLength > 0) {
        sliceOptions.push(qb.snippet());
    }
    var query = qb.where(...).slice(sliceOptions);

**Comment by ehennum** [comment]
Setting the page length to zero returns no document results. 

That's useful to get facets or to get the total estimate when the documents aren't needed.

When there are no document results, however, there is nothing to snippet, so an application shouldn't request snippets when setting the page length to zero. 

When paging over a document result set, the page start changes (typically incrementing by the page length), but the page length typically stays the same.  It's not clear why an application would encounter a zero page length inadvertently unless taking input from the end user, but in that case, the application should check that the page length is greater than zero.

Unless I misunderstand, it is a bug (the total should not be affected by requesting snippets) but one that only affects people while experimenting.  A real application would never need to workaround this bug. 

It's possible to turn off metrics using the withOptions() clause.  Some views also suppress metrics.

In general in the Node.js API, any function that takes a list of arguments also takes a single array with all of the arguments.

"humans are notoriously difficult to program and buggy to boot" -- this is a quotable quote.

**Comment by brightgarden** [comment]
You wrote
> Unless I misunderstand, it is a bug (the total should not be affected by requesting snippets) but one that only affects people while experimenting. A real application would never need to workaround this bug.

I agree. It is a bug. It wasted some of my time. And I am not experimenting. I am writing a real application, and currently, I am working around this bug.

I am curious to know if you think this is a bug on the REST-API side, or the Node Client side?

**Comment by ehennum** [comment]
Sorry, I'm not sure I understand about the workaround.

Snippeting and a zero page length are contradictory instructions. As you note, the fix will be to "tell developers not to combine a 0-length page with a snippet transform." The standard way for an API to tell a developer about a programming issue (as opposed to a runtime operational issue) is to throw an error. Requesting snippeting with a zero page length is similar to requesting a negative page length in that the request can never be executed without ignoring part of the input. 

It is a programming issue instead of a runtime operational issue because the developer either supplies the page length or, if getting the page length from some other source, should check that the page length is greater than zero.  If the developer is getting the page length from some other source and is not checking the page length, the developer is vulnerable to other issues like a negative page length.

The bug is that the error isn't being thrown.

**Comment by ehennum** [comment]
A regression test might combined a slice() with zero page length with snippets or extract.

**Comment by MayankBhatnagar89** [comment]
Test has been added to regression under test nodejs-documents-query.js : https://github.com/marklogic/node-client-api/commit/19fbc4efb0abac28f52bc561dfa448c65fdfe9d1
