### ISSUE TITLE
Score value returned in search

### ISSUE THREAD

**Issue by tpiros** [marklogic/node-client-api#190]
I'd like to see a feature whereby I could extract the score value from the search results in an easier fashion. At the moment the only way (as far as I know) to retrieve the score value for documents is to add the `.withOptions({ debug: true })` method to `qb.where()`.

Imagine a scenario where we have the following code:

``` javascript
var search = function(req, res) {
  var searchQuery = req.params.searchQuery;
  db.documents.query(
    qb.where(
      qb.collection('character'),
      qb.parsedFrom(searchQuery)
    ).withOptions({ debug: true })
  ).result().then(function(response) {
    console.log(response);
    res.json(response);
  }).catch(function(error) {
    console.log(error);
  });
};
```

Let's assume that executing a the following search 'term1 AND term2' would produce two results. The `response` in the code above would now have 3 objects. 1 object containing debug information about the search (including the score in the `results` array) and the other 2 objects would contain information about the actual documents (including their content). There's no easy way to display a property of these documents along with their score values at the moment.

Probably the best way to do this - albeit I'm not sure if it's possible at all - would be to have an extra options for `withOptions` categories such as: `.withOptions({ categories: ['content', 'score'] })` which could produce:

``` javascript
{ uri: '/character/lukeskywalker.json',
    category: 'content',
    format: 'json',
    contentType: 'application/json',
    contentLength: '837',
    score: 123456,
    content:
     { name: 'Luke Skywalker' }
}
```

**Comment by ehennum** [comment]
Reassessment of the document envelope might be best to take up as part of a general comparison with JSearch after 8.0-4

**Comment by tamaspiros** [comment]
Are there any updates regarding this now that 8.0-4 and JSearch are both available? I also have a few other suggestions for search which I'm happy to discuss.

**Comment by tpiros** [comment]
Just checking in to see if this will be added anytime soon.

**Comment by tpiros** [comment]
I am going through my old open issues - should I close this one off or would there be any potential updates to this?

**Comment by ehennum** [comment]
It's still a good request.  Basically, the idea is to have a knob to put the metadata in the descriptor rather than have an initial summary object.

**Comment by georgeajit** [comment]
Closing the issue to keep API stable.
