### ISSUE TITLE
RFE: Ability to set the "label" on a range constraint bucket

### ISSUE THREAD

**Issue by brightgarden** [marklogic/node-client-api#191]
I believe this is a Request for Enhancement...
### Desire:

I would like to be able to set the "name" and "label" of a bucket separately, which the REST-API supports ([see this example](https://docs.marklogic.com/guide/rest-dev/appendixa#id_64714) in the Rest Developer's Application Guide).
### Preferred solution:

Let me set the facet bucket using a json object (as one option). For instance, an "advanced" way would be to know exactly how to configure the bucket, and pass in the json for it that includes the name, label, lt, ge, and anything else that might be desired by the "power" user. 
### Workaround:

Using just the [NodeJs Api Client](https://github.com/marklogic/node-client-api/blob/master/lib/query-builder.js#L4019-L4020), the "name" is automatically assigned to both the "name" and the "label" of the constraint, so in order to use a different label, I have to iterate over the buckets and set the label manually (either in the queryBuilder's calculateClause, or after the facet result comes back (by changing the "value")).

**Comment by ehennum** [comment]
The concern about label is whether it mixes view concerns with the model concerns.  Regardless, thanks for the RFE.

**Comment by brightgarden** [comment]
Hmm... Possibly. I think what I really want is greater control over the response bucket's "value" property (which appears to be mapped from the "label" property in the request).

In fact, I don't think I even need the "name" in the response at all. I may just set the label value to the name property in the request and call it a day.
