### ISSUE TITLE
optional termOptions parameter for QueryBuilder term() function

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#193]
The qb.term() function should accept an optional qb.termOptions() parameter (as should the Search API, for that matter).

**Comment by ehennum** [comment]
See also internal bug 35245 for the fix to the Search API.

A possible regression test might pass an option such as:

qb.where(
        qb.term("SOME_TERM", qb.termOptions('stemmed'))
        )

**Comment by MayankBhatnagar89** [comment]
Test has been added to regression under https://github.com/marklogic/node-client-api/commit/76b9e35886cb232e6695e525260a7d2b972899fc
