### ISSUE TITLE
Path index values query is not returning the result (related to Bug 35160)

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#194]
1) Create a path namespace on the database:
prefix = ns1
uri = http://www.example1.com

2) Create a path range index on the database:
type = int
path = /ns1:root/ns1:popularity

3) Insert this document
xdmp:document-insert("/test/query/doc1.xml",
<root xmlns="http://www.example1.com">
  <title>Vannevar Bush</title>
  <popularity>6</popularity>
</root>,(),())

4) Run a pathIndex values query 
it('should do values on pathindex', function(done){
  db.values.read(
    t.fromIndexes(
      t.range(t.pathIndex("/ns1:root/ns1:popularity", {ns1:"http://www.example1.com"}))
    )
  ).result(function(response) {
    console.log(response);
    done();
  }, done);
});

It's not returning the result
Result:
  { 'values-response':
   { name: 'structuredef',
     metrics:
      { 'values-resolution-time': 'PT0.00036S',
        'total-time': 'PT0.001976S' } } }

**Comment by ehennum** [comment]
The issue is in the test case. The document is being created without readable permissions for rest-reader.  When a document is created without explicit permissions, the permissions default to the current user.  In QueryConsole, the user is typically admin. When I changed the document insert to provide readable permissions to rest-reader, the result was returned.

**Comment by ayuwono** [comment]
Closed for test case issue, it's working fine now

var should = require('should');

var testconfig = require('../etc/test-config-qa.js');

var marklogic = require('../');
var q = marklogic.queryBuilder;
var t = marklogic.valuesBuilder;

var db = marklogic.createDatabaseClient(testconfig.restReaderConnection);
var dbWriter = marklogic.createDatabaseClient(testconfig.restWriterConnection);
var dbAdmin = marklogic.createDatabaseClient(testconfig.restAdminConnection);

describe('Document tuples test', function(){
 before(function(done){
    this.timeout(10000);
    dbWriter.documents.write({
      uri: '/test/myns/doc1.xml',
      collections: ['myColl'],
      contentType: 'application/xml',
      content: '<root xmlns="http://www.example1.com"><popularity>5</popularity></root>'
    }).
    result(function(response){done();}, done);
  });

  it('should do values on pathindex', function(done){
    db.values.read(
      t.fromIndexes(
        t.range(t.pathIndex("/ns1:root/ns1:popularity", {ns1:"http://www.example1.com"}))
      )
    ).result(function(response) {
      console.log(JSON.stringify(response, null, 2));
      done();
    }, done);
  });

  it('should delete all documents', function(done){
    dbAdmin.documents.removeAll({
      all: true
    }).
    result(function(response) {
      done();
    }, done);
  });
});

Result:
{
  "values-response": {
    "name": "structuredef",
    "types": {
      "type": [
        "xs:int"
      ]
    },
    "tuple": [
      {
        "frequency": 1,
        "distinct-value": [
          "5"
        ]
      }
    ],
    "metrics": {
      "values-resolution-time": "PT0.000669S",
      "total-time": "PT0.001776S"
    }
  }
}
