### ISSUE TITLE
sparql query with invalid value on begin or end parameter is not throwing any error

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#197]
This sparql query with invalid value on begin or end parameter is not throwing any error. There is no error thrown on server log

...
var myQuery = "PREFIX foaf: <http://xmlns.com/foaf/0.1/>" +
              "PREFIX ppl:  <http://people.org/>" +
              "SELECT *" +
              "WHERE { ?s foaf:knows ppl:person3 }"

db.graphs.sparql({
  contentType: 'application/sparql-results+json',
  query: myQuery,
  begin: -1,
  end: 10
}).
result(function(response){
...

The graph file is under /test-complete/data/people.ttl

**Comment by ehennum** [comment]
Thanks for catching that.

**Comment by kkanthet** [comment]
Verified that -ve values on begin or end throws error
