### ISSUE TITLE
Unable to list uncommitted graph using transaction id

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#198]
db.transactions.open({transactionName: 'sparqlTransaction', timeLimit: 30})
.result(function(response) {
  console.log('Opening transaction 1');
  console.log(JSON.stringify(response, null, 2));
  tid = response.txid;
  return db.graphs.write({
    txid: tid,
    uri: graphUri,
    contentType: 'text/turtle',
    data: fs.createReadStream(graphPath)
  }).result();
})
.then(function(response) {
//list the uncommitted graph
console.log(JSON.stringify(response, null, 2));
return db.graphs.list({txid: tid}).result();
...

It will return: list graphs: cannot process response with 406 status

On the server log, it will throw this error:
2015-09-14 11:16:48.371 Info: node-client-api-rest-server: Status 500: REST-UNACCEPTABLETYPE: (err:FOER0000) No acceptable content type: None of the requested types [object Object] can be provided

The same error is thrown when we use valid contentType parameter
db.graphs.list({txid: tid, contentType: 'text/uri-list'})

**Comment by ehennum** [comment]
named parameters were not properly handled for graph list -- should be correct now

**Comment by ayuwono** [comment]
Verified passed and added test to nodejs-graphs-transaction.js
