### ISSUE TITLE
Unable to write a graph that has a hash sign (#) on the iri

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#199]
Unable to write a graph that has a hash sign (#) on the iri

db.graphs.write({uri: 'http://marklogic.com/negative/two/people#sem', ...})

It will throw this error:
{ [Error: write graph: cannot process response with 400 status (on graph http://marklogic.com/negative/two/people#sem)]
  message: 'write graph: cannot process response with 400 status (on graph http://marklogic.com/negative/two/people#sem)',
  statusCode: 400 }

There is no error thrown on Server log

**Comment by ehennum** [comment]
Should be working now

**Comment by ayuwono** [comment]
Verified passed and adding test
