### ISSUE TITLE
When usingDefaultGraph is set to true, the inserted graph doesn't become the default graph

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#200]
When usingDefaultGraph is set to true, the inserted graph doesn't become the default graph   

var myData = "CREATE GRAPH <http://marklogic.com/semantics#default-graph> ;"
   db.graphs.sparqlUpdate({
     data: myData,
     usingNamedGraph: false,
     usingDefaultGraph: true
   }).
   result(function(response){

Result:
{
  "defaultGraph": false,
  "graph": null,
  "graphType": "inline"
}

**Comment by grechaw** [comment]
responded in BT

**Comment by ehennum** [comment]
Should set the graph type to default in the response.

**Comment by ayuwono** [comment]
Verified passed and adding test
