### ISSUE TITLE
sparqlUpdate cannot pass an IRI datatype as a parameter on binding

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#202]
This might be related to issue#199

It seems that the binding value is not taking the hash sign (#) if we want to pass an IRI datatype as a parameter on sparqlUpdate

var myData = "PREFIX bb: <http://marklogic.com/baseball/players#>\n" +
             "INSERT\n" +
             "{\n" +
             "  GRAPH <http://marklogic.com/sparqlupdate/baseball>\n" +
             "  {\n" +
             "    ?playertoken bb:id ?id .\n" +
             "    ?playertoken bb:lastname ?lastname .\n" +
             "    ?playertoken bb:firstname ?firstname .\n" +
             "    ?playertoken bb:position ?position .\n" +
             "    ?playertoken bb:number ?number .\n" +
             "    ?playertoken bb:team ?team .\n" +
             "  }\n" +
             "}\n" +
             "WHERE {}"
db.graphs.sparqlUpdate({
  data: myData,
  bindings: {
    'playertoken': 'http://marklogic.com/baseball/players#417',
    'id': 417,
    'lastname': {value: 'Doolittle', type:'string'},
    'firstname' : 'Sean',
    'position': 'pitcher',
    'number': {value: 62, type:'integer'},
    'team': 'Giants'
  }
}).
result(function(response){
...

This will throw an error:
[Error: SPARQL graph update: cannot process response with 400 status (on inline graphs)]
message: 'SPARQL graph update: cannot process response with 400 status (on inline graphs)',
statusCode: 400 }

There is no error thrown on the Server log

Passing 
bindings: {playertoken: 'bb:417'} is also not working

**Comment by ehennum** [comment]
Should be working now.

**Comment by ayuwono** [comment]
Verified passed, adding automation test
