### ISSUE TITLE
defaultRulesets parameter is not passed correctly

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#203]
When using defaultRulesets parameter, sparqlUpdate is throwing an error "Endpoint does not support query parameter"

var myData = "PREFIX bb: <http://marklogic.com/baseball/players#>\n" +
             "INSERT DATA\n" +
             "{\n" +
             "  GRAPH <http://marklogic.com/sparqlupdate/baseball>" +
             "  {\n" +
             "    bb:345 bb:id 345 .\n" +
             "  }\n" +
             "}"
db.graphs.sparqlUpdate({
  data: myData,
  defaultRulesets: 'exclude'
}).
result(function(response){
...

Error:
body:
 { errorResponse:
    { statusCode: 400,
      status: 'Bad Request',
      messageCode: 'REST-UNSUPPORTEDPARAM',
      message: 'REST-UNSUPPORTEDPARAM: (err:FOER0000) Endpoint does not support query parameter: invalid parameters: defaultRulesets for request' } } }

Access log:
127.0.0.1 - rest-writer [17/Sep/2015:13:26:21 -0700] "POST /v1/graphs/sparql?defaultRulesets=exclude HTTP/1.1" 400 241 - -

**Comment by ehennum** [comment]
The parameter error should be gone.  I had to put the prefix and graph URI within angle brackets

**Comment by ayuwono** [comment]
Verified passed and adding the test
