### ISSUE TITLE
When using optimizeLevel parameter, sparqlUpdate is throwing an error "Endpoint does not support query parameter"

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#204]
When using optimizeLevel parameter, sparqlUpdate is throwing an error "Endpoint does not support query parameter"

I think it's related to issue #203 that just fixed

var myData = "PREFIX bb: <http://marklogic.com/baseball/players#>\n" +
"INSERT DATA\n" +
"{\n" +
" GRAPH <http://marklogic.com/sparqlupdate/baseball>" +
" {\n" +
" bb:345 bb:id 345 .\n" +
" }\n" +
"}"
db.graphs.sparqlUpdate({
data: myData,
optimizeLevel: 0
}).
result(function(response){
...

Error:
{ [Error: SPARQL graph update: cannot process response with 400 status (on inline graphs)]
  message: 'SPARQL graph update: cannot process response with 400 status (on inline graphs)',
  statusCode: 400,
  body:
   { errorResponse:
      { statusCode: 400,
        status: 'Bad Request',
        messageCode: 'REST-UNSUPPORTEDPARAM',
        message: 'REST-UNSUPPORTEDPARAM: (err:FOER0000) Endpoint does not support query parameter: invalid parameters: optimizeLevel for request' } } }

Access log:
127.0.0.1 - rest-writer [17/Sep/2015:14:36:53 -0700] "POST /v1/graphs/sparql?using-named-graph-uri=true&optimizeLevel=0 HTTP/1.1" 400 239 - -

**Comment by ehennum** [comment]
Another bad mapping from the Node.js parameter name and the URI parameter name.  Thanks for catching that.

**Comment by ayuwono** [comment]
Verified passed and adding the test
