### ISSUE TITLE
Invalid json format returned for describe query 

### ISSUE THREAD

**Issue by kkanthet** [marklogic/node-client-api#206]
the following code snippet returned the correct results for s describe query but not a valid JSON format when I parse the results, response.results in undefined because of the "sem:" in the bindings  array 

```
   var myQuery = "PREFIX foaf: <http://xmlns.com/foaf/0.1/>" +
            "PREFIX ppl:  <http://people.org/>" +
            "describe <http://people.org/person11>"
        db.graphs.sparql({
            contentType: 'application/sparql-results+json',
            query: myQuery
        }).
            result(function(response){
                console.log(response.results.bindings);
                response.should.equal('{"head":{"vars":[]},"results":{"bindings":[sem:triple(sem:iri("http://people.org/person11"), sem:iri("http://www.w3.org/1999/02/22-rdf-syntax-ns#type"), sem:iri("http://people.org/Person")),' +
                    'sem:triple(sem:iri("http://people.org/person11"), sem:iri("http://xmlns.com/foaf/0.1/name"), "Person 11")]}}');
                done();
            });

**Comment by ehennum** [comment]
Charles, it seems to me that the REST API is not returning valid JSON. Here's what I see:

{"head":{"vars":[]},"results":{"bindings":[sem:triple(sem:iri("http://people.org/person11"), sem:iri("http://www.w3.org/1999/02/22-rdf-syntax-ns#type"), sem:iri("http://people.org/Person")),sem:triple(sem:iri("http://people.org/person11"), sem:iri("http://xmlns.com/foaf/0.1/name"), "Person 11")]}}

There is a secondary bug in that the Node.js API should parse any JSON response to JavaScript, but, as Kiran points out, that would break in this case.

**Comment by grechaw** [comment]
Hi Kiran, this may be considered a bug for a negative condition, but there is an error in your call.
the content-type I'm surprised is working- for a query it should be application/sparql-query

If you use an appropriate accept: header, say, application/n-triples, then this query will work properly.  Snelson is going to add a builtin in 8.0-5 timeframe that will help me parse queries more effectively without accept headers.  I still may be able to help this, but I don't think it's for 8.0-4, provided the right accept header gives you what you need.

**Comment by ehennum** [comment]
Thanks, Charles, for clarifying.  Kiran, if the test case specifies the correct mime type but the Node.js client doesn't send the mime type as an accept header, that would be a grievous bug on the Node.js API.

**Comment by ayuwono** [comment]
Hi Charles,

Correct me if I'm wrong, from the documentation: http://pubs.marklogic.com:8011/guide/semantics/REST#id_54258
it is said that the content-type is 'application/sparql-results+json' for a DESCRIBE query

An additional issue, if you use 'application/sparql-results+xml' on Node, it will return 406 status code

**Comment by kcoleman-marklogic** [comment]
That table covers Accept header MIME types, not the input content-type. That is, it is telling you what the MIME type of the results will be, not the MIME type of the input.

I believe the input is always going to be either application/sparql-query or application/sparql-update, depending on whether you're doing a query or an update. 

It does kinda raise a question about the Node.js interface in my mind, though: 

Why should the caller have to specify the input Content-type at all? Wouldn't it make more sense to make the interface distinguish between query and update and fill the Content-type in appropriately?

**Comment by grechaw** [comment]
" it is said that the content-type is 'application/sparql-results+json' for a DESCRIBE query"

that's the content-type header in the response, not in the request.

**Comment by kkanthet** [comment]
Work with contentType rdf+json , Charles looking into documentation bug.
