### ISSUE TITLE
SPARQL query and graphs.read with 'application/n-triples' contentType is returning a buffer string instead of triples

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#207]
1) Insert this graph:
@prefix ad: <http://marklogicsparql.com/addressbook#> .
@prefix id:  <http://marklogicsparql.com/id#> .
@prefix rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs:    <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ml: <http://marklogicsparql.com/> .

id:1111 ad:firstName "John" .
id:1111 ad:lastName  "Snelson" .
id:1111 ml:worksOn ml:Inference .
id:1111 ml:worksFor ml:MarkLogic .
id:1111 a ml:LeadEngineer .

id:2222 ad:firstName "Aries" .
id:2222 ad:lastName  "Li" .
id:2222 ml:worksOn   ml:SparqlUpdate .
id:2222 ml:worksFor ml:MarkLogic .
id:2222 a ml:SeniorEngineer .

ml:LeadEngineer rdfs:subClassOf  ml:Engineer .
ml:SeniorEngineer rdfs:subClassOf  ml:Engineer .
ml:Engineer rdfs:subClassOf ml:Employee .
ml:Employee rdfs:subClassOf ml:Person .

2) Run a sparql query with 'application/n-triples' as the contentType. 
var myQuery = "DESCRIBE <http://marklogicsparql.com/id#1111>"
db.graphs.sparql({
  contentType: 'application/n-triples',
  query: myQuery
}).
result(function(response){

It will return:
<Buffer 3c 68 74 74 70 3a 2f 2f 6d 61 72 6b 6c 6f 67 69 63 73 70 61 72

On REST-API, the same sparql query with 'application/n-triples' content-type will return the triples

xquery version "1.0-ml";
declare namespace http = "xdmp:http";
let $sparql := 'DESCRIBE <http://marklogicsparql.com/id#1111>'
let $uri := "http://localhost:8015/v1/graphs/sparql?query=" || encode-for-uri($sparql)
let $response :=
xdmp:http-get($uri,
                <options xmlns="xdmp:http">
                <authentication method="digest">
                <username>admin</username>
                <password>admin</password>
                </authentication>
                <headers>
                  <accept>application/n-triples</accept>
                </headers>
                </options>)
        return $response

Result:
<http://marklogicsparql.com/id#1111> <http://marklogicsparql.com/worksOn> <http://marklogicsparql.com/Inference> .
<http://marklogicsparql.com/id#1111> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://marklogicsparql.com/LeadEngineer> .
<http://marklogicsparql.com/id#1111> <http://marklogicsparql.com/worksFor> <http://marklogicsparql.com/MarkLogic> .
<http://marklogicsparql.com/id#1111> <http://marklogicsparql.com/addressbook#firstName> "John" .
<http://marklogicsparql.com/id#1111> <http://marklogicsparql.com/addressbook#lastName> "Snelson" .

The same behavior is occurring on graphs.read too

**Comment by ehennum** [comment]
There is no standard JavaScript object representation of n-triples.

Try the toString('utf8') method on the response buffer object:

https://nodejs.org/api/buffer.html#buffer_buf_tostring_encoding_start_end

We could convert the triples from a buffer to a string by default, but that would be an unnecessary and unwanted expense for the usual use case of sending triples to a file, web service or other sink.

**Comment by ehennum** [comment]
On reflection, taking this back.  Streaming is the recommended approach for optimal performance and throughput.

The Promise should parse application/n-triples, application/n-quads, or application/trig as a UTF string.

**Comment by ehennum** [comment]
result() for graph read or sparql query should return a string for application/n-triples, application/n-quads, or application/trig

**Comment by ayuwono** [comment]
Verified passed and added tests on nodejs-graphs.content-type.js

**Comment by ayuwono** [comment]
Opening this issue again as read with 'application/trig' is producing 406 error code
cannot process response with 406 status

Server log:
2015-09-23 11:24:52.934 Info: node-client-api-rest-server: Status 500: REST-UNACCEPTABLETYPE: (err:FOER0000) No acceptable content type: None of the requested types application/trig can be provided

**Comment by ehennum** [comment]
Hi, Charles:  Is application/trig a supported type for graph read and SPARQL query?  Thanks.

**Comment by grechaw** [comment]
Not for either no.

**Comment by ehennum** [comment]
Footnote:  the existing documentation for the semantic REST endpoints seems to imply support for trig by linking without caveat to:

http://docs.marklogic.com/guide/semantics/loading#id_70682

**Comment by kcoleman-marklogic** [comment]
The /v1/graphs/sparql documentation doesn't link to that topic. It links to this one, which is much more specific and does not indicate you can fetch results as TriG. 

http://pubs.marklogic.com:8011/guide/semantics/REST#id_81353

(At least it does at the moment - been too much motion in that space recently for me to say how it was even as recently as a few days ago, I fear.)

I don't have a clue about the GET /v1/graphs formats. I didn't know the write and read aren't symmetric. Will suggest to Jane to follow up with Charles.

**Comment by ehennum** [comment]
Kiran, no changes to the implementation are needed because the Node.js API leaves it to the REST API to validate the passthrough payloads and their mime types.

Please remove the tests for application/trig from SPARQL query and graph read.

**Comment by dsokolsky** [comment]
Is this bug supposed to be in test?

**Comment by kkanthet** [comment]
Update to the tests are done, just left it open to track followup of Jane with Charles. Shipping it
