### ISSUE TITLE
Unable to read a graph that has '#' on the uri

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#208]
This is another '#' encoding bug

1) Insert a graph with a '#' on the uri:
http://marklogic.com/graphs/content#type

2) Read the graph
db.graphs.read({contentType: 'application/rdf+json', uri: graphUri}).
result(function(response){
...

It will throw a 400 error:
cannot process response with 400 status (on graph http://marklogic.com/graphs/content#type)

There is no error thrown on the server

Access log:
127.0.0.1 - rest-writer [21/Sep/2015:15:01:21 -0700] "GET /v1/graphs?graph=http://marklogic.com/graphs/content#type HTTP/1.1" 400 0 - -

**Comment by ehennum** [comment]
Can you provide more specific code for step 1 so there's no ambiguity about reproducing the problem? Thanks.

**Comment by ayuwono** [comment]
var graphUri = 'http://marklogic.com/graphs/content#type';
var graphPath = './node-client-api/test-complete/data/mlgraph.ttl';
db.graphs.write({uri: graphUri, contentType: 'text/turtle', data: fs.createReadStream(graphPath)}).
result(function(response){
...

The graph could be any turtle graph, but you can use this:

@prefix ad: http://marklogicsparql.com/addressbook# .
@prefix id: http://marklogicsparql.com/id# .
@prefix rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns# .
@prefix rdfs: http://www.w3.org/2000/01/rdf-schema# .
@prefix ml: http://marklogicsparql.com/ .

id:1111 ad:firstName "John" .
id:1111 ad:lastName "Snelson" .
id:1111 ml:worksOn ml:Inference .
id:1111 ml:worksFor ml:MarkLogic .
id:1111 a ml:LeadEngineer .

id:2222 ad:firstName "Aries" .
id:2222 ad:lastName "Li" .
id:2222 ml:worksOn ml:SparqlUpdate .
id:2222 ml:worksFor ml:MarkLogic .
id:2222 a ml:SeniorEngineer .

ml:LeadEngineer rdfs:subClassOf ml:Engineer .
ml:SeniorEngineer rdfs:subClassOf ml:Engineer .
ml:Engineer rdfs:subClassOf ml:Employee .
ml:Employee rdfs:subClassOf ml:Person .

**Comment by ayuwono** [comment]
It's also failing to probe and to remove a graph that has # on the uri too

var graphUri = 'http://marklogic.com/graphs/content#type';
// Probe
db.graphs.probe(graphUri).
result(function(response){
...

//Remove
db.graphs.remove(graphUri).
result(function(response){
...

**Comment by ehennum** [comment]
Sorry about the assign, it is indeed an encoding issue in the client API.

**Comment by ehennum** [comment]
Should be working now. Some other modules outside of the graphs area were also not using encodeURIComponent() correctly, which this commit also fixes. That shouldn't cause any regressions on positive tests that were working but could conceivably cause regressions on negative tests that should have been positive tests.

**Comment by kkanthet** [comment]
verified , we are able to read from graph with URI containing #
