### ISSUE TITLE
specifying namedGraphs, or defaultGraphs params in graphs.sparql returns empty results

### ISSUE THREAD

**Issue by kkanthet** [marklogic/node-client-api#209]
Write triples into a named graph and query using graphs.sparql by specifying namesGraphs:'namedGraph' , returns empty results.
Same query without  those params returns correct results.

```javascript
 it('should write named graph ', function(done){
        this.timeout(10000);
        db.graphs.write('http://marklogic.com/Graph1','text/turtle', fs.createReadStream(ttlfile)).
            result(function(response){
                //console.log(JSON.stringify(response, null, 2));
                console.log(response);
                response.defaultGraph.should.equal(false);
                response.graph.should.equal('http://marklogic.com/Graph1');
                response.graphType.should.equal('named');
                done();
            }, done);
    });


 it('should run SPARQL CONSTRUCT query  on namedGraphs ', function(done){
        this.timeout(10000);
        var myQuery ="PREFIX  bb: <http://marklogic.com/baseball/players#> CONSTRUCT { ?ID ?p \"coach\" .}" +
            " WHERE { ?ID ?p \"coach\" . ?ID bb:firstname ?firstname . Values ?firstname {\"Gene\"}}";
        db.graphs.sparql({
            namedGraphs: 'http://marklogic.com/Graph1',
            contentType: 'application/rdf+json',
            query: myQuery
        }).
            result(function(response){
                console.log(response);
                response.should.have.property('http://marklogic.com/baseball/players#158');
                done();
            }, done);
    });

**Comment by ehennum** [comment]
Hi, Charles -- it's not clear to me what's wrong in how the Node.js API is invoking the REST API.

Here's the query from the POST payload:

    PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    CONSTRUCT { ?s foaf:name "Person 1" .}
    WHERE { ?s foaf:name "Person 1" .}

As Kiran notes, without the named-graph-uri parameter, it is matching one triple.  

{ 'http://people.org/person1': { 'http://xmlns.com/foaf/0.1/name': [ [Object] ] } }

Here's the access log entry:

rest-writer [21/Sep/2015:21:47:52 -0400] "POST /v1/graphs/sparql HTTP/1.1" 200

With the named-graph-uri parameter, it fails to match:

rest-writer [21/Sep/2015:21:47:43 -0400] "POST /v1/graphs/sparql?named-graph-uri=http%3A%2F%2Fmarklogic.com%2FGraph1 HTTP/1.1" 200

Reading the default graph, it is empty.  Reading the unencoded named graph uri above returns triples including the target triple.

Any idea what might be going on?

**Comment by grechaw** [comment]
Alas, I do know what's going on, and it's just plain confusing.
 
named-graph-uri parameter only applies when there is a GRAPH keyword somewhere in the query. So I think that this query is what you want:
 
 PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    CONSTRUCT { ?s foaf:name "Person 1" .}
    WHERE { GRAPH ?g {?s foaf:name "Person 1" .}}
  
 
named-graph-uri plus this query should be equivalent to
 
 PREFIX foaf: <http://xmlns.com/foaf/0.1/>
    CONSTRUCT { ?s foaf:name "Person 1" .}
FROM NAMED <namedGraph>
    WHERE { GRAPH ?g { ?s foaf:name "Person 1" .}} 


There are eaxmples for named graphs in the semantics REST tests for guidance

**Comment by kkanthet** [comment]
Thank You Charles. Works after specifying GRAPH within the query
