### ISSUE TITLE
Module doesn't exit with empty query results

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#21]
What's the expected behavior of the `db.query().stream()` when there are no matches? I'm getting a `null` return passed to the `data` event handler, but my program (as run from the terminal) never exits. I have to `^c` to terminate. I see `null` on the command line from the log statement, but something gets stuck there. If there is data in the data handler, it exits as I'd expect. (It's definitely not dropping into the error handler for any reason.)

```javascript
// Client: OS X 10.9.4
// Server: MarkLogic 8.0-20140724, CentOS 6.4
// node --version : v0.10.29
// git log -n 1 develop : commit a85ffeea09ebad80b1b9c58f7e69d6e33c884f3d

var marklogic = require("marklogic")
var conn =  {
 host: "host",
 port: 8000,
 user: "reader",
 password: "********",
 authType: "DIGEST"
}
var db = marklogic.createDatabaseClient(conn)
var q = marklogic.queryBuilder

db.query(
 q.where(
   q.byExample(
     {
       gender: "maleasdf" // Doesn't match anything
     }   
   )
 )
)
.stream().
 on("data", function(document) {
   console.log(document);
 }).
 on("error", function(error) {
   console.log(error)
 })
```

**Comment by ayuwono** [comment]
Closing backlog issue, the issue has regression test
