### ISSUE TITLE
<page-length> in options.xml

### ISSUE THREAD

**Issue by tamaspiros** [marklogic/node-client-api#210]
I have a question about the options XML document in the modules DB in conjunction with the Node.js Client API's `.slice()` method. Here's my setup:

- REST API instance running on port 5010
- Content DB has 12 documents
- Modules DB has an updated options.xml file that looks like this:

```xml
<options xmlns="http://marklogic.com/appservices/search">
<search-option>unfiltered</search-option>
<quality-weight>0</quality-weight>
<page-length>20</page-length>
</options>
```

As you can see I added the page-length option. However, this is the result that I get in Node.js:

```javascript
var marklogic  = require('marklogic');
var connection = {
  host: 'localhost',
  port: 5010,
  user: 'admin',
  password: 'admin'
};

var db = marklogic.createDatabaseClient(connection);
var qb = marklogic.queryBuilder;
var pb = marklogic.patchBuilder;

db.documents.query(
  qb.where(
    qb.collection('hotel')
  )
).result().then(function(result) {
  console.log(result.length);
});
```

The `result.length` statement returns 10, regardless of the `<page-length>` node in my options document.

The question is: Do I need to modify the page-length using `.slice()` as well? Am I wrong in thinking that adding that property should increase the number of documents returned per page?

Thanks

**Comment by ehennum** [comment]
The Node.js API doesn't use query options persisted in the modules database. 

Instead, the API generates query options to send with the request.

Is there a reason that it's problematic to maintain the default page length in the Node.js tier?

**Comment by tamaspiros** [comment]
No, not at all. I was just wondering if I'm doing something wrong / it's a bug / it's a feature :)

Thanks!
