### ISSUE TITLE
Removing graph using transaction id is throwing 404 error

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#213]
Removing graph using transaction id is throwing 404 error. On the example of chained promises below, let's say that the graph is exist on the database with uri = graphUri

var graphUri = '/tx/some/graphuri';
...
     return db.transactions.open({transactionName: 'sparqlTransaction3', timeLimit: 60}).result();
   })
   .then(function(response) {
     console.log('Open transaction 3');
     console.log(JSON.stringify(response, null, 2));
     tid3 = response.txid;
     return db.graphs.remove({uri: graphUri, txid: tid3}).result();
   })
   .catch(function(error) {
     console.log(error);
     done();
   }, done);

Error thrown:
{ [Error: remove graph: cannot process response with 404 status]
  message: 'remove graph: cannot process response with 404 status',
  statusCode: 404,
  body:
   { errorResponse:
      { statusCode: 404,
        status: 'Not Found',
        messageCode: 'RESTAPI-NODOCUMENT',
        message: 'RESTAPI-NODOCUMENT: (err:FOER0000) Resource or document does not exist:  category: Graphstore message: URI not found [object Object]' } } }

Access log:
127.0.0.1 - rest-writer [23/Sep/2015:14:10:53 -0700] "DELETE /v1/graphs?graph=%5Bobject%20Object%5D HTTP/1.1" 404 240 - -

There is no error on the Server log

**Comment by ehennum** [comment]
graphs.remove() and graphs.probe() should both support named parameters now.

**Comment by ayuwono** [comment]
Verified passed and added test on nodejs-graphs-transaction-remove.js
