### ISSUE TITLE
specifying null within ruleset[] throws "The ruleset file cannot be found: null" error

### ISSUE THREAD

**Issue by kkanthet** [marklogic/node-client-api#214]
Below code snippet throws error when you specifu null as ruleset within the array,
However if i specify :: rulesets:null  it ignores the parameter and works as expected

REST call are as below
rulesets:['equivalentClass.rules', null] :: POST /v1/graphs/sparql?named-graph-uri=http%3A%2F%2Fmarklogic.com%2Fdirgraph1&ruleset=equivalentClass.rules&ruleset=null&default-rulesets=include

rulesets:null :: "POST /v1/graphs/sparql?named-graph-uri=http%3A%2F%2Fmarklogic.com%2Fdirgraph1&default-rulesets=include

```javascript
it('should run SPARQL SELECT Query With DefaultRuleset include and one of the rulesets set to null ', function(done){
        this.timeout(10000);
        var myQuery = " SELECT  (count (?s)  as ?totalcount) WHERE {GRAPH ?g { ?s ?p ?o .}}";
        db.graphs.sparql({
            contentType: 'application/json',
            rulesets:['equivalentClass.rules', null],
            defaultRulesets: 'include',
            namedGraphs: 'http://marklogic.com/dirgraph1',
            query: myQuery
        }).
            result(function(response){
                console.log(JSON.stringify(response));
                response.results.bindings[0].should.have.property('totalcount');
                response.results.bindings[0].totalcount.value.should.equal('15');

                done();
            }, done);
    });

**Comment by ehennum** [comment]
Null is never a valid item in any array accepted by the Node.js API.  I don't think that's useful to test. If you disagree, please reopen.

**Comment by kkanthet** [comment]
Would be nice to handle,  but not critical. will mark it as 'will not fix'
