### ISSUE TITLE
sparql returns empty results/false when passing  defaultGraphs: 'http://marklogic.com/semantics#default-graph'

### ISSUE THREAD

**Issue by kkanthet** [marklogic/node-client-api#215]
When we pass  defaultGraphs: 'http://marklogic.com/semantics#default-graph'  in sparql the query returns empty results/False
Removing the defaultGraphs options returns correct result.

REST call from access Log::
POST /v1/graphs/sparql?default-graph-uri=http%3A%2F%2Fmarklogic.com%2Fsemantics%23default-graph

```javascript
 it('should write the default graph', function (done) {
        this.timeout(10000);
        db.graphs.write('text/turtle', fs.createReadStream('./node-client-api/test-complete/data/people.ttl')).
            result(function (response) {
                //console.log(JSON.stringify(response, null, 2));
                response.defaultGraph.should.equal(true);
                done();
            }, done);
    });

    it('should read the default graph', function (done) {
        this.timeout(10000);
        db.graphs.read('text/turtle').
            result(function (response) {
                response.should.containEql('@prefix foaf:');
                done();
            }, done);
    });

//TODO: Update after issue  #208 is fixed

    it('should run SPARQL ASK query', function (done) {
        this.timeout(10000);
        var myQuery = "PREFIX foaf: <http://xmlns.com/foaf/0.1/>" +
            "PREFIX ppl:  <http://people.org/>" +
            "ASK WHERE {Graph ?g  { ?s foaf:knows ppl:person3 }}";
        db.graphs.sparql({
            defaultGraphs: 'http://marklogic.com/semantics#default-graph',
            contentType: 'application/json',
            query: myQuery
        }).
            result(function (response) {
                console.log(JSON.stringify(response));
                response.boolean.should.equal(true);
                done();
            });
    });

**Comment by ehennum** [comment]
Hi, Charles:  might I ask you to cast your expert eye on this one?

This query happily returns true in QueryConsole:

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ppl:  <http://people.org/>
ASK WHERE {Graph ?g  { ?s foaf:knows ppl:person3 }}

If I put the same query in a file, however, a curl command equivalent to the Node.js API request above returns false just like the Node.js request:

curl -i --anyauth -u rest-reader:x -X POST -d @/tmp/test.rq -H "accept: application/json" -H "content-type: application/sparql-query" "http://localhost:8015/v1/graphs/sparql?default-graph-uri=http%3A%2F%2Fmarklogic.com%2Fsemantics%23default-graph"

My understanding is that the default graph is identified by the following URI:

    http://marklogic.com/semantics#default-graph

Does the REST API support explicitly setting the default graph for a query to the URI for the default graph? Or is something else going on?

**Comment by grechaw** [comment]
i need to ponder and tinker.

**Comment by grechaw** [comment]
Hi @kkanthet I'd like to triage this out of 8.0-4 if possible.  I've got one other bug under investigaion.  While you consider this, I"ll be on that other one, but I suspect that fixing this will have slight blast radius.

**Comment by grechaw** [comment]
On second thought.

setup
```
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ppl: <http://people.org/>
  
  INSERT DATA
{
 <me> foaf:knows ppl:person3 
}
```

```
sem:sparql('PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ppl: <http://people.org/>
ASK WHERE {Graph ?g { ?s foaf:knows ppl:person3 }}', (), "default-graph=http://marklogic.com/semantics#default-graph"),

(: false -- Graph ?g pattern does not match default graph  :)

sem:sparql('PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ppl: <http://people.org/>
ASK WHERE {Graph ?g { ?s foaf:knows ppl:person3 }}', (), "named-graph=http://marklogic.com/semantics#default-graph"),

(: true :) 

sem:sparql('PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ppl: <http://people.org/>
ASK WHERE {Graph ?g { ?s foaf:knows ppl:person3 }}', ()),

(: true, union of all graphs :)


sem:sparql('PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ppl: <http://people.org/>
ASK WHERE { ?s foaf:knows ppl:person3 }', (), "default-graph=http://marklogic.com/semantics#default-graph"),

(: true :)
sem:sparql('PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ppl: <http://people.org/>
ASK WHERE { ?s foaf:knows ppl:person3 }', (), "named-graph=http://marklogic.com/semantics#default-graph")

(: false -- no graph ?g pattern to match :)
```

**Comment by grechaw** [comment]
So Erik, I think this is not  a bug -- do you agree?

**Comment by ehennum** [comment]
Thanks, Charles, for clarifying on the relation between the options parameter and the graph binding.

Kiran, would you agree this is a test case error?

**Comment by kkanthet** [comment]
Thank You Charles And Erik for clarification , Updated Tests and verified it works as Expected..
