### ISSUE TITLE
Add TypeScript bindings

### ISSUE THREAD

**Issue by christyharagan** [marklogic/node-client-api#217]
TypeScript bindings would enable TypeScript developers to consume this package and leverage a fully typed API. Since these are just bindings, no actual code changes are required.

I have already created these bindings here: [marklogic-node-typescript-definitions](https://github.com/christyharagan/marklogic-node-typescript-definitions).

I did so by essentially extracting the jsdoc from the code. Subsequently, maintenance of these definition files would be reduced to similarly ensuring any jsdoc updates are reflected in the definition files themselves.

If there is interest, I can create a pull request for these definition files for easy consumption.

**Comment by ehennum** [comment]
Thanks, Christy, for the concrete proposal.

If I understand correctly (ignorant of TypeScript here), the TypeScript interface declarations could be backed by the JavaScript implementations and thus TypeScript use of the API could coexist with direct JavaScript use of the API.

If so, the main downside would be the extra cost of maintaining the TypeScript interface declarations and especially the duplication of jsdoc. On the other hand, defining a formally typed interface would be a solid design practice.

One related factor to consider is the potential impact of ES6 features on the design of the Node.js API with the upgrade to Node.js 4. If ES6 suggests enhancements to the design, maybe the time to add a TypeScript interface is after the refresh.

I'm queuing this issue up for Justin to consider from the PM perspective.

**Comment by millturnK** [comment]
As a developer using Typescript, I am most grateful for the MarkLogic types definitions. Thanks Christy!

**Comment by georgeajit** [comment]
Will not be working on this.
