### ISSUE TITLE
qb.facet(aPathIndex) throws 'could not default constraint name' error

### ISSUE THREAD

**Issue by brightgarden** [marklogic/node-client-api#218]
Hello,

I was trying to generate a facet using a path range index, and discovered that this was impossible with the current release.

I coded a work-around for the moment, and noticed that the [development branch here](https://github.com/marklogic/node-client-api/blob/develop/lib/query-builder.js#L4241-L4242) shows that this problem has been addressed, but not in a manner that is not optimal to me.

- The ideal solution (from my point of view) is to allow me to specify the constraint name (it is essentially the "label" of the facet when it returns in the response). 
- The next best solution (which is how I coded my work around) is to use the path itself, which can be easily matched up with the original path that was used to create the facet specification for the query.

I can see why the second solution above is non-optimal if characters in a path expression will cause problems for the rest-api.

The current implementation (linked above) changes a path that looks like `/foo/bar/baz` to `path_foo_bar_baz`.

Once this code is released, I will be able to use it (since it will no longer throw the error), but will likely have to always capture the results of the call in order to change the constraint name to one that I prefer:

```
  var pathExpression = "/foo/bar/baz";
  var pathIndex = qb.pathIndex(pathExpression);
  var facetWrapper = qb.facet(pathIndex, facetOptions);
  facetWrapper.name = pathExpression;
  calculateArgs.push(facetWrapper); 
 . . . more facets . . .
  query.calculate(calculateArgs);
```

I already do this elsewhere because I need to come back through any bucketed facets [to modify the label since it isn't possible to specify the label on the call via `qb.bucket`](https://github.com/marklogic/node-client-api/issues/191). 

__Make facetWrapper a little smarter?__
Just as a suggestion, perhaps instead of making [facetWrapper](https://github.com/marklogic/node-client-api/blob/develop/lib/query-builder.js#L3828) a plain object, it can have a prototype method to set the name so that we can do something like this:

```
qb.facet(pathIndex, facetOptions).name("preferred-name"); // returns facetWrapper
```

For that matter, you could just make facetWrapper the object that does everything fluently:

```
qb.facet(__aConstraintName)
  .pathIndex(__aPathExpression, __optionalNamespaces) // removes json-property and adds path-index
  .facetOptions(__arrayOfOptions)
  .validate(); // throws error if incomplete
```

__anyhow ...__
I was just wanting to help make the api a little easier to use without having to do these little hacks in order to take advantage of the functionality available in the REST-API. Thanks.

**Comment by ehennum** [comment]
Hi, Brightgarden:

Thanks for the thoughtful input (and for noticing the commit that fixes this issue).

You should already be able to provide the name as the optional first argument when creating a facet, as in:

    qb.facet("preferred-name", pathIndex, facetOptions)

If that's not working as documented at the following page, it's a bug:

http://docs.marklogic.com/jsdoc/queryBuilder.html#facet

Regarding the fluents on the index creation, we decided to limit the fluents to the top level of the query builder because the where() clause takes a query tree. From our perspective, we thought there would be too many idioms if we switched from a chained fluent idiom to a composed tree idiom and back to the chained fluent idiom.

We do of course want to remove the need for any hacks, so identifying potential issues like this is very welcome.

Hoping that helps.

**Comment by brightgarden** [comment]
Thank you for the reference to the jsdoc. It works as documented.

Although, it may be useful to change the error message from `could not default constraint name` to `consider passing in a constraint name as a first parameter` -- because once you release your new code, new developers may never figure out that you can pass it in as the first parameter (of course, this would only apply to new index types that throw that same error).
