### ISSUE TITLE
query result read stream does not end

### ISSUE THREAD

**Issue by csreddy** [marklogic/node-client-api#219]
The query result stream seems to get stuck and never emits  `end` event. I can see all the documents being processed correctly in `data` callback but stream does not end. I have to retry couple of times to return results, sometimes it works in one try and sometime it takes couple of times. 

The equivalent `.result()` version works just fine

tried on latest official and on develop branch, same issues on both

```javascript
db.documents.read({
                    uris: uris, // array of 11 uris,
                    transform: ['all-transforms'] // no issues with transforms script as i can see all documents in *data* callback
                })
              .stream()
              .on('data', function(document) {
                        var content = (!_.isObject(document.content)) ? JSON.parse(document.content) : document.content;
                        if (!_.isNull(content) || content.length > 0) {
                            diffsOnEachPlatform[content[0].platform.name] = _.pluck(content, 'name');
                        }
                    })
              .on('error', function(error) {
                        console.error(error);
                    })
              .on('end', function() {
                      // control never gets here, it often takes multiple tries to work
                        console.log(diffsOnEachPlatform);
                    });
```

**Comment by ehennum** [comment]
Hi, Sudhakar:

I'm puzzled, because there are examples, unit tests, and regression tests for .on('end').

How does this case differ?  Can you provide a way to reproduce the issue outside of the specific environment?

The release is impending, so the sooner we can isolate the issue, the better.

Thanks for looking into it.

**Comment by csreddy** [comment]
Here's the test that demo's the bug. It sometimes runs successfully but sometimes fails because the mocha timeout caused due to the stream not ending

note: Don't change the db connection details

```javascript
it('should end the stream after processing all documents', function(done) {
		
		var db = marklogic.createDatabaseClient({
        host:     'staging-bugtrack.marklogic.com',
        port:     8006,
        user:     'admin',
        password: 'admin',
		authType: 'DIGEST'
		});
		var processedUris = [];
		db.documents.read({
			uris: ['/b4_0/2010-01-12/linux-32-rh4/platform-diffs.xml',
				'/b4_0/2010-01-12/linux-64-rh4-cluster/platform-diffs.xml',
				'/b4_0/2010-01-12/linux-64-rh5v-cluster/platform-diffs.xml',
				'/b4_0/2010-01-12/linux-64-rh5v/platform-diffs.xml',
				'/b4_0/2010-01-12/solaris-32-sol9-cluster/platform-diffs.xml',
				'/b4_0/2010-01-12/solaris-32-sol9/platform-diffs.xml',
				'/b4_0/2010-01-12/solaris-64-sol10-cluster/platform-diffs.xml',
				'/b4_0/2010-01-12/winnt-32-w2k3/platform-diffs.xml',
				'/b4_0/2010-01-12/winnt-64-w2k3-cluster/platform-diffs.xml',
				'/b4_0/2010-01-12/winnt-64-w2k3/platform-diffs.xml',
				'/b4_0/2010-01-12/winnt-64-w2k8sp/platform-diffs.xml'
			],
		}).stream()
			.on('data', function(document) {
				console.log(document.uri)
				processedUris.push(document.uri)
			})
			.on('error', function(error) {
				console.error(error);
				done(error);
			})
			.on('end', function() {
				console.log(processedUris)
				done();
			});
	})
```

**Comment by ehennum** [comment]
Hi, Sudhakar:

Regarding:

"but sometimes fails because of the mocha timeout caused due to the stream not ending"

How have you determined that the end event is not firing instead of Mocha not waiting long enough time for the end event to fire?  

We've seen case of Mocha giving up too soon for a long-running or large tasks or due to network issues.

Have you tried running mocha with  --no-timeouts or increasing the timeout, as in:

  describe('...', function(){
    this.timeout(5000);

Do you ever see the same issue outside of Mocha?

Thanks for looking into it,

**Comment by csreddy** [comment]
I found this issue in my app. The http call which is hooked to this controller code gets stuck and does not return the response, even console.log() in `end` callback is not printed but all documents in `data` is getting streamed properly, hence my assessment that stream does not end.

 I tried mocha with 5000ms and 10,000ms timeout but it still timesout

**Comment by ehennum** [comment]
Can you provide a more complete reproduction case? We have tests with the same shape as the code above, so that code alone is not sufficient to reproduce the problem.

**Comment by csreddy** [comment]
The test provides the isolated env for you, I'm not sure what else I can do. I'm slightly suspecting that the size of the documents returned may have some impact on it, the existing tests might not be exactly same in that sense. I'll be happy to show in person if that'll make things clearer.

**Comment by ehennum** [comment]
Did you try the mocha test with the --no-timeouts argument?

If the size of the documents simply means that the response takes longer, no change to the Node API will reduce that time.

**Comment by csreddy** [comment]
Yes i tried and mocha still timesout

**Comment by ehennum** [comment]
I modified the example to remove mocha from the equation:

	 var db = marklogic.createDatabaseClient({
	        host:     'staging-bugtrack.marklogic.com',
	        port:     8006,
	        user:     'admin',
	        password: 'admin',
	        authType: 'DIGEST'
	        });
	        var processedUris = [];
	        db.documents.read({
	            uris: ['/b4_0/2010-01-12/linux-32-rh4/platform-diffs.xml',
	                '/b4_0/2010-01-12/linux-64-rh4-cluster/platform-diffs.xml',
	                '/b4_0/2010-01-12/linux-64-rh5v-cluster/platform-diffs.xml',
	                '/b4_0/2010-01-12/linux-64-rh5v/platform-diffs.xml',
	                '/b4_0/2010-01-12/solaris-32-sol9-cluster/platform-diffs.xml',
	                '/b4_0/2010-01-12/solaris-32-sol9/platform-diffs.xml',
	                '/b4_0/2010-01-12/solaris-64-sol10-cluster/platform-diffs.xml',
	                '/b4_0/2010-01-12/winnt-32-w2k3/platform-diffs.xml',
	                '/b4_0/2010-01-12/winnt-64-w2k3-cluster/platform-diffs.xml',
	                '/b4_0/2010-01-12/winnt-64-w2k3/platform-diffs.xml',
	                '/b4_0/2010-01-12/winnt-64-w2k8sp/platform-diffs.xml'
	            ],
	        }).stream()
	            .on('data', function(document) {
	                console.log(document.uri);
	                processedUris.push(document.uri);
	            })
	            .on('error', function(error) {
	                console.error(error);
	                done(error);
	            })
	            .on('end', function() {
	                console.log('done '+processedUris.length);
	                console.log(processedUris);
	            });

I get the following output:

/b4_0/2010-01-12/linux-32-rh4/platform-diffs.xml
/b4_0/2010-01-12/winnt-64-w2k8sp/platform-diffs.xml
/b4_0/2010-01-12/linux-64-rh4-cluster/platform-diffs.xml
/b4_0/2010-01-12/linux-64-rh5v-cluster/platform-diffs.xml
/b4_0/2010-01-12/solaris-32-sol9/platform-diffs.xml
/b4_0/2010-01-12/solaris-32-sol9-cluster/platform-diffs.xml
/b4_0/2010-01-12/winnt-32-w2k3/platform-diffs.xml
/b4_0/2010-01-12/linux-64-rh5v/platform-diffs.xml
/b4_0/2010-01-12/winnt-64-w2k3-cluster/platform-diffs.xml
/b4_0/2010-01-12/winnt-64-w2k3/platform-diffs.xml
/b4_0/2010-01-12/solaris-64-sol10-cluster/platform-diffs.xml
done 11
[ '/b4_0/2010-01-12/linux-32-rh4/platform-diffs.xml',
  '/b4_0/2010-01-12/winnt-64-w2k8sp/platform-diffs.xml',
  '/b4_0/2010-01-12/linux-64-rh4-cluster/platform-diffs.xml',
  '/b4_0/2010-01-12/linux-64-rh5v-cluster/platform-diffs.xml',
  '/b4_0/2010-01-12/solaris-32-sol9/platform-diffs.xml',
  '/b4_0/2010-01-12/solaris-32-sol9-cluster/platform-diffs.xml',
  '/b4_0/2010-01-12/winnt-32-w2k3/platform-diffs.xml',
  '/b4_0/2010-01-12/linux-64-rh5v/platform-diffs.xml',
  '/b4_0/2010-01-12/winnt-64-w2k3-cluster/platform-diffs.xml',
  '/b4_0/2010-01-12/winnt-64-w2k3/platform-diffs.xml',
  '/b4_0/2010-01-12/solaris-64-sol10-cluster/platform-diffs.xml' ]

If you run my code, do you see the same output.

**Comment by csreddy** [comment]
hmm..Ya i see the same output, does not hang, works fine

**Comment by ehennum** [comment]
Thanks for checking it out.  It looks like there's a Mocha issue.  If you agree, please close this bug.

**Comment by csreddy** [comment]
well, the request was timing out in my app too, not just in mocha. not sure what's wrong. Thanks for looking into it
