### ISSUE TITLE
Missing JSDoc for quality builder or range requests

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#225]
A couple features we've added this year didn't get corresponding JSDoc:

We added some metadata patch builder helpers. One, patchBuilderQuality, is documented as an interface, but no methods are documented. At minimum, it looks like it has a set() method that should be exposed.

The fix for Issue #121 added support for range requests when reading a single binary document, but it is not exposed anywhere in the JSDoc. Presumably, it shows up as a "range" property on the input object descriptor, but IDK if it is also supposed to show up as a possible positional parameter or not.

Tagged for 8.0-4 because there's no tag for 8.0-5. I assume you'll defer or not, as needed, Erik.

**Comment by ehennum** [comment]
Should be good now -- thanks for identifying it.

**Comment by kcoleman-marklogic** [comment]
I looked at your change request, and thought it looked fine, but I'll give it a last once over tomorrow, once it is on pubs.

**Comment by kcoleman-marklogic** [comment]
You're going to hate me for this, but...patchBuilderQuality is wrong. The method name is just "set", not "setQuality". Or at least, that's what works for me. 

Now that I look more closely at the rest of the JSDoc for these interfaces, they all seem wrong in the JSDoc. I'm sorry I didn't notice that before. I'd been just using the test (nodejs-documents-patch-metadata.js) as reference and only noticed the missing JSDoc for quality because it wasn't included in the test.

Am I just using it wrong? Here's the example I wrote a week or so ago, based on what I saw in the tests. It does not work if I try to use the names you have in the JSDoc for all these interfaces.
```javascript
var pb = marklogic.patchBuilder;
  return db.documents.patch({
    uri: response.documents[0].uri, 
    categories: [ "metadata" ],
    operations: [
      // Add a collection
      pb.collections.add('INSERTED'),

      // Remove a collection
      pb.collections.remove('initial1'),

      // Add a capability to a role
      pb.permissions.replace(
          {'role-name': 'app-user', 
           capabilities: ['read','update']}),

      // Add a property
      pb.properties.add('myProp3', 'INSERTED'),
      pb.quality.set(2)
    ]})
```

**Comment by ehennum** [comment]
Thanks for catching that -- I used the internal function names (longer for a better stack trace) instead of the short external names.

**Comment by ehennum** [comment]
Shoud be fixed now
