### ISSUE TITLE
.probe() returns error

### ISSUE THREAD

**Issue by tamaspiros** [marklogic/node-client-api#226]
The code snippet below fails with the following error message if the URI is not present in the database:

``` [Error: probe document: challenge request failed for /v1/documents?format=json&uri=%2Ftest.json (on /test.json)]
  message: 'probe document: challenge request failed for /v1/documents?format=json&uri=%2Ftest.json (on /test.json)' }```

Here's the code that I've used:

```javascript
'use strict';
var connection = {
  host: 'localhost',
  port: 8000,
  user: 'admin',
  password: 'admin'
};

var db = marklogic.createDatabaseClient(connection);
var qb = marklogic.queryBuilder;
var pb = marklogic.patchBuilder;

var uri = '/test.json';

db.documents.probe(uri).result()
.then(function(probeResponse) {
  console.log(probeResponse);
})
.catch(function(error) {
  console.log(error);
});
```

I was expecting to see `probeResponse.exists` to be `false`.

ML version: 8.0-3.2

**Comment by kcoleman-marklogic** [comment]
FWIW, I cannot reproduce this in my environment on 8.0-4. That almost sounds like an auth failure. Are you able to successfully make other requests with that connection?

**Comment by tamaspiros** [comment]
Yes - If I have the /test.json file in the DB I get the proper `probeResponse` object back, no problem. If I clear the DB, I get the above error.

**Comment by tamaspiros** [comment]
Very interesting - the issue was that for the App Server running on that port I've set the authentication to be 'application-level' and the default user was set to 'admin'. 

The question remains though: how come I could verify the existence of one document but when the DB was empty I saw an error?

**Comment by kcoleman-marklogic** [comment]
This is a totally uninformed guess:

When the probe fails, a 404 is returned by the REST API. Perhaps there's something about app level security that causes it to mask 404's behind a different kind of error. IDK why it would, though.

**Comment by ehennum** [comment]
The REST API doesn't play well with application-level security, which requires sessions.  Please use digest or basic+SSL instead.
