### ISSUE TITLE
debug info is returned even when debug flag is set to false

### ISSUE THREAD

**Issue by csreddy** [marklogic/node-client-api#227]
Pardon me if i'm doing something wrong here. I expect debug data not to be returned when `debug` flag is set to false. When I remove `withOptions`, only then it would not return debug data, the boolean flag does not seem to take effect.

``` javascript
var marklogic = require('marklogic');

var db = marklogic.createDatabaseClient({
    host: 'staging-bugtrack.marklogic.com',
    port: 8006,
    user: 'admin',
    password: 'admin',
    authType: 'DIGEST'
});
var q = marklogic.queryBuilder;

var processedUris = [];

db.documents.query(q.where(
        q.directory('/b8_0/2015-11-01/', true)
    ).slice(1, 1)
    .withOptions({
        debug: false,
        queryPlan: false,
        metrics: false
   })
)
    .stream()
    .on('data', function(document) {
        console.log(document);
        processedUris.push(document.uri);
    })
    .on('error', function(error) {
        console.error(error);
        // done(error);
    })
    .on('end', function() {
        console.log('done ' + processedUris.length);
        console.log(processedUris);
    });
```

**Comment by wooldridge** [comment]
I can reproduce.

Debugging info looks like the following:
```
{ 'snippet-format': 'snippet',
  total: 1,
  start: 1,
  'page-length': 1,
  results: 
   [ { index: 1,
       uri: '/mike.json',
       path: 'fn:doc("/mike.json")',
       score: 2048,
       confidence: 0,
       fitness: 0.2357023,
       href: '/v1/documents?uri=%2Fmike.json',
       mimetype: 'application/json',
       format: 'json',
       matches: [Object] } ] }
```
1. withOptions debug false
```
    .withOptions({
        debug: false,
        queryPlan: false,
        metrics: false
   })
```
operation.requestBody:
```
    { search: 
   { options: 
      { 'search-option': [Object],
        debug: false,
        'return-plan': false,
        'return-metrics': false },
     query: { queries: [Object] } } }
```
** Debugging info returned **

2. withOptions debug true
```
    .withOptions({
        debug: true,
        queryPlan: false,
        metrics: false
   })
```
operation.requestBody:
```
{ search: 
   { options: 
      { 'search-option': [Object],
        debug: true,
        'return-plan': false,
        'return-metrics': false },
     query: { queries: [Object] } } }
```
** Debugging info returned **

3. withOptions NOT INCLUDED

operation.requestBody:
```
{ search: 
   { options: { 'search-option': [Object] },
     query: { queries: [Object] } } }
```
** Debugging info NOT returned **

**Comment by wooldridge** [comment]
Here's a curl version:
```
curl -X "POST" --anyauth -u admin:admin -H "Content-Type:application/json" -d @q.json 'http://localhost:8000/v1/search?format=json&category=content&start=1&pageLength=1&view=results'
```
With q.json:
```
{
  "search": {
    "options": {
      "search-option": [
        "unfiltered"
      ],
      "debug": false,
      "return-plan": false,
      "return-metrics": false
    },
    "query": {
      "queries": [
        {
          "term-query": {
            "text": [
              "Mike"
            ]
          }
        }
      ]
    }
  }
}
```
@ehennum, with the above payload (`"debug": false`), should I expect to see debugging info (i.e., `'snippet-format'` and the like) returned? In this case, I am seeing it.

**Comment by ehennum** [comment]
The difference above is the difference between requesting a search summary or requesting just the documents.  A request for snippets, facets, or metrics requires a search summary.

The debug flag controls whether or not the search summary reports the cts.query that was executed.  One way to see the difference is to run a search:search() query (using elements) in QueryConsole, with both true and false values. 
 
    xquery version "1.0-ml";
    import module namespace search = "http://marklogic.com/appservices/search"
        at "/MarkLogic/appservices/search/search.xqy";
    search:search("check", <search:options><search:debug>true</search:debug></search:options>)

**Comment by wooldridge** [comment]
Thanks for the clarification, @ehennum. It doesn't seem to me like Sudhakar's first example above should return a summary since this doesn't ask for snippets, facets, or metrics:
```
db.documents.query(q.where(
        q.directory('/b8_0/2015-11-01/', true)
    ).slice(1, 1)
    .withOptions({
        debug: false,
        queryPlan: false,
        metrics: false
   })
)
```
Is there a way to suppress the summary via a withOptions property?

**Comment by ehennum** [comment]
If the code doesn't want the summary, it shouldn't provide withOptions().  

Turning off all of the options to suppress the summary doesn't make a lot of sense.  Just omit the options.

If you feel that it should work, it's the responsibility of the Node.js API not to send the options if it's a nullop. But, I would suggest that the Node.js API shouldn't incur that responsibility.

**Comment by wooldridge** [comment]
Thanks, @ehennum, I see your point. I think the relationship between withOptions() and the summary deserves some explanation in the jsdocs. I will do that.

**Comment by wooldridge** [comment]
Adding the following to the documentation for withOptions() to clarify when and why the summary object appears:

When the 'debug', 'metrics', 'queryPlan', or 'similarDocs' parameter is set, a search summary object will be returned along with the result documents.

**Comment by wooldridge** [comment]
@kcoleman-marklogic, please review this update to the jsdoc documentation.
