### ISSUE TITLE
400 - permission denied on update only

### ISSUE THREAD

**Issue by tamaspiros** [marklogic/node-client-api#229]
I am wondering if this is the expected behaviour or not: I have a document in the database with the following permission:

```
permissions: [
  {'role-name': username, capabilities:['update', 'read']}
],
```

where `username` gets programatically called.

The "issues" is that when I try to read a document that has this permission the `.read()` method returns a `[]`, however when I update the document using `.write()` I got a 400 - Permission denied error. I would expect the same error code when attempting to read a document for which I have no permission.

**Comment by tamaspiros** [comment]
Did anyone have a look at this please?

**Comment by ehennum** [comment]
Sorry about the slow response.  If the user should not have permission to read the document, then, yes, this is the expected response.  Documents that you don't have permission to read are treated as non-existent.  That's part of the MarkLogic security model. 

If that's not the question, does the user have either the rest-reader and rest-writer role or a role that has the rest-reader and rest-writer privileges?

**Comment by tamaspiros** [comment]
Thanks @ehennum - that makes sense. I was just expecting a 400 instead of a an empty array. :smile:
