### ISSUE TITLE
parseBindings() & calculate()

### ISSUE THREAD

**Issue by tamaspiros** [marklogic/node-client-api#230]
Is it possible to have a query where we have both parsedBindings, and calculated values for facets? I can't seem to be able to get it running:

```javascript
return db.documents.query(
  qb.where(
    qb.collection('photo'),
    qb.parsedFrom('country:"Hungary"',
      qb.parseBindings(
        qb.value('country', qb.bind('country'))
      )
    )
  )
  .calculate(
    qb.facet('country', qb.facetOptions('frequency-order', 'descending')),
    qb.facet('make', qb.facetOptions('frequency-order', 'descending')),
    qb.facet('model', qb.facetOptions('frequency-order', 'descending'))
  )
  .withOptions()
)
.result((results) => console.log(results))
.catch((error) => console.log(error));
```

returns

```
{ [Error: query documents: response with invalid 400 status]
  message: 'query documents: response with invalid 400 status',
  statusCode: 400,
  body:
   { errorResponse:
      { statusCode: 400,
        status: 'Bad Request',
        messageCode: 'REST-INVALIDPARAM',
        message: 'REST-INVALIDPARAM: (err:FOER0000) Invalid parameter: Invalid combined search\nRESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: Operation results in invalid Options: Exactly 1 <constraint> type needs to be defined at a time.' } } }
```

Basically I'd like to generate facets for my custom search as well. Am I constructing my query in the wrong way?

**Comment by ehennum** [comment]
All facet names get bound by default.  If the country facet exists, the query string should be able to bind country:"Hungary" without defining a separate country binding.

**Comment by kcoleman-marklogic** [comment]
I don't think this is covered at all in the documentation right now. It's mentioned in the jsdoc, but I think I should reiterate it. To make sure I understand what you're saying, Erik, is this correct:

Tamas could remove the qb.parseBindings call from his original example, and it would still resolve a search term like "country:hungary" correctly. 

However, if he chose not to generate facets on country (or at all), he would still need the parse binding.

Can you include both? I can well imagine wanting my query to be independent of whether or not I'm generating facets.

**Comment by tamaspiros** [comment]
@Thanks @ehennum and yes @kcoleman-marklogic I think you're right. Apologies for not responding to this earlier - it has skipped my mind.

The following implementation works perfectly:

```javascript
return db.documents.query(
  qb.where(
    qb.collection('photo'),
    qb.parsedFrom('country:"Hungary"'
    )
  )
  .calculate(
    qb.facet('country', qb.facetOptions('frequency-order', 'descending')),
    qb.facet('make', qb.facetOptions('frequency-order', 'descending')),
    qb.facet('model', qb.facetOptions('frequency-order', 'descending'))
  )
  .withOptions()
)
.result((results) => console.log(results))
.catch((error) => console.log(error));

**Comment by tamaspiros** [comment]
As mentioned in the earlier comment that solution is working so I'll close this issue.
