### ISSUE TITLE
opt into or remove deprecated interfaces

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#231]
The deprecated interfaces include the following.

document.remove() returns a response with both a uris property and a uri property.  The singular property is a legacy from when document.remove() could only remove a single document.  We should remove that property in MarkLogic 9.

In MarkLogic 8, the developer has to opt in to get a transaction object and receives a transaction id string by default.  MarkLogic 9 should reverse the default and opt in.

In MarkLogic 8, the developer has to opt in for a zero-based slice on the search response and supplies a 1-based slice by default.  MarkLogic 9 should reverse the default and opt in.

**Comment by wooldridge** [comment]
MarkLogicClient.remove() should also be addressed per the documentation:

> For backward compatibility, if a string is passed, the uri is returned as a string, but in the next major release, the uri will be return as an array with one string.

**Comment by kcoleman-marklogic** [comment]
Mike, if you find other things to remove/change besides the items called out here, please add them so that I can ensure they all make it into the release notes.

**Comment by wooldridge** [comment]
Per email discussion with @ehennum and @jmakeig, we will deprecate the transactionId string and legacy slice option in ML9 and remove those features entirely in ML10. I will add to the JSDoc regarding this in my check-in and @kcoleman-marklogic can review.

**Comment by wooldridge** [comment]
@ayuwono, these updates to address deprecated features will break tests:

- Remove() methods for documents now only return arrays of one or more URIs. So any tests that expect a string return value need to be fixed.
- The transactions.open() method now returns a full-fledged Transaction object by default instead of an object with a transactionId string. So any tests not expecting the Transaction object will need to be fixed.
- The slice() method now works in "array" mode by default. This differs from "legacy" mode in how the params work. Tests that are working with sliced results will need to have their params updated.

**Comment by ayuwono** [comment]
Changed all of the affected tests

**Comment by wooldridge** [comment]
@kcoleman-marklogic, can you review the changes to the jsdoc comments for this fix? You can see what changed here:

https://github.com/marklogic/node-client-api/pull/360/files

Namely, there are comment changes for:

DatabaseClient.remove()
queryBuilder.slice()
transactions.open()

**Comment by kcoleman-marklogic** [comment]
Bit late for me to mention this, I know, but shouldn't the slice change apply to values queries, too? It seems rather odd to only make it zero-based for search results.

**Comment by kcoleman-marklogic** [comment]
Sorry to get to this so late. Incompats always come in really late for me. The jsDoc looks OK modulo the following:

- the question above about slicing values query results (btw, to prop up my assertion, `marklogic.setSliceMode` claims it applies to both)
- if the slice change applies to both, then the values query slice jsDoc needs updating
- in `queryBuilder.slice`, this text in the description used to be a link and isn't now: module:marklogic.setSliceMode
- `transactions.open` does not make it clear what the default is, IMO

The only one of these that's important is the values slice issue.

**Comment by kcoleman-marklogic** [comment]
One other thought that drifted across my empty mind: 

I have covered these changes in the ML release notes, but should they be mentioned somewhere on GitHub? IDK what the GitHub convention is for reporting backward incompatibilities.

**Comment by wooldridge** [comment]
@ayuwono, let's chat today about possibly getting the slice update for values queries in for 2.0.0. See Kim's comment https://github.com/marklogic/node-client-api/issues/231#issuecomment-296403244.

**Comment by kcoleman-marklogic** [comment]
FWIW, here are the related release notes:

http://pubs.marklogic.com:8011/9.0/guide/relnotes/chap4#id_34190

**Comment by wooldridge** [comment]
@kcoleman-marklogic, in http://pubs.marklogic.com:8011/9.0/guide/relnotes/chap4#id_78125:

In the first code example, "PageLenth" --> "PageLength"

**Comment by wooldridge** [comment]
@kcoleman-marklogic, in https://github.com/marklogic/node-client-api/issues/231#issuecomment-296404227 you say:

> transactions.open does not make it clear what the default is, IMO

The Returns documentation for that method currently says:

"either a Transaction object (the default) or string transactionId..."

Are you referring to some other default value?

**Comment by kcoleman-marklogic** [comment]
No, sorry, I didn't read as far as the "returns" description, so I missed that. I retract my statement.

My pea brain got stuck on the function description at the top (which leads with the non-return result type) and the option description, neither of which indicate what the default is.

**Comment by kcoleman-marklogic** [comment]
I'll check the link tomorrow morning, after the next doc build. I want to make sure it works on DMC, too (it should). I'll fix that typo in the release notes before tomorrow's build, too.

**Comment by wooldridge** [comment]
@kcoleman-marklogic, thanks, I will merge that PR then now so it gets into the doc build.

**Comment by wooldridge** [comment]
@kcoleman-marklogic, regarding https://github.com/marklogic/node-client-api/issues/231#issuecomment-296455238 about documenting backwards incompatibilities, I'd like to avoid duplicating documentation so how about we link to that incompatibilities doc page from the GitHub release page? I put static text in the release draft from which we can link when we have a final URL:

https://github.com/marklogic/node-client-api/releases

@jmakeig, any thoughts on this?

**Comment by wooldridge** [comment]
@kcoleman-marklogic, regarding the slice() method for ValuesBuilder in https://github.com/marklogic/node-client-api/issues/231#issuecomment-296404227, I think you're right. But I talked to @ayuwono and we agreed that it is too late to get that into 9.0-1. Definitely put that in 9.0-2, I will file an issue.

**Comment by kcoleman-marklogic** [comment]
About slice: OK, thanks. I'll change the docs not to include value query.

About the incompats: Linking to docs.marklogic.com is OK with me, but it is really up to Justin. 

If you decide to go with it, the URLs will be exactly as now, but replace the host:port prefix docs.marklogic.com. So http://docs.marklogic.com/9.0/guide/relnotes/chap3#whatever.

**Comment by wooldridge** [comment]
@kcoleman-marklogic, thanks for the link info. I updated the release page with the appropriate docs.marklogic.com link:

https://github.com/marklogic/node-client-api/releases

**Comment by kcoleman-marklogic** [comment]
The links aren't working worth a darn on pubs, but that's on our end and nothing to do with you. Could be a problem with how we're building the JSDoc or maybe the doc app is doing something nefarious. Either way, not your problem. I'll investigate today.

**Comment by kcoleman-marklogic** [comment]
OK, I think we're good. It looks like the doc build didn't pick up your last checkin for some reason. It's kinda weird since we clone a new copy of the repo every night. Gremlins.

Anyway, I expect happy faces everywhere tomorrow.

**Comment by kcoleman-marklogic** [comment]
The build from this morning looks fine. Your links are working.

**Comment by wooldridge** [comment]
Thanks, @kcoleman-marklogic. Closing.
