### ISSUE TITLE
Update copyright date in source code

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#233]
To 2016.

**Comment by alexmilowski** [comment]
All the copyrights have been updated as of March 4th, 2016.

**Comment by ayuwono** [comment]
Please revert the change on master and make the change on develop, then we will push it to master

**Comment by kcoleman-marklogic** [comment]
The copyright still only goes to 2015 in gulp.js, which means it's going to show up that way in the generated jsdoc. I believe it needs to be fixed here:

https://github.com/marklogic/node-client-api/blob/develop/gulpfile.js#L45

**Comment by ayuwono** [comment]
Verified on gulpfile.js line 45 that it has the correct copyright:
copyright: 'Copyright 2014-2016 MarkLogic Corporation'
