### ISSUE TITLE
REGR: SPARQL DESCRIBE query returning status 406 instead of empty

### ISSUE THREAD

**Issue by MayankBhatnagar89** [marklogic/node-client-api#234]
Build : 20160302

Test name : nodejs-sparql.js

Code : 
-----------------------------------------------------
 it('should run SPARQL DESCRIBE query return empty', function (done) {
        this.timeout(10000);
        var myQuery = "describe <http://people.org/person1133423>";
        db.graphs.sparql({
            contentType: 'application/json',
            query: myQuery
        }).
            result(function (response) {
                response.results.bindings.length.should.equal(0);
                done();
            });
    });
-----------------------------------------------------

Error : 
-----------------------------------------------------
{ errorResponse:
      { statusCode: 406,
        status: 'Unacceptable Type',
        messageCode: 'REST-UNACCEPTABLETYPE',
        message: 'REST-UNACCEPTABLETYPE: (err:FOER0000) No acceptable content type: None    of the requested types application/json can be provided' 
} } }
-----------------------------------------------------

**Comment by ehennum** [comment]
See the internal comment from Charles. The test should be revised.

**Comment by ayuwono** [comment]
https://bugtrack.marklogic.com/bug/38217

**Comment by grechaw** [comment]
I'm sorry I keep getting notifications from bugtrack and editing the issues there.
I wonder whether it would be possible to 'add a github comment' from those projects in BT.

**Comment by MayankBhatnagar89** [comment]
The issue has been fixed , verified on build 20160311.
Corresponding checkins related to this issue are : 
https://github.com/marklogic/node-client-api/commit/7a2667804110ee8c63c6cb16d09f912ce3d42d2d
https://github.com/marklogic/node-client-api/commit/4832a494a79d63df5ec00dbb4540f668b406fd0a
https://github.com/marklogic/node-client-api/commit/7d0df4117a05474d6032a7a60dabd120b9381b6b

Thanks,
Mayank
