### ISSUE TITLE
jsdoc contains wrong method name for SPARQL Update ops

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#235]
The func name is wrong for graphs.sparqlUpdate. Two "sparql" methods are showing up instead of one "sparl" and one "sparqlUpdate". You can see it in this bad boy:

http://docs.marklogic.com/jsdoc/graphs.html#sparql

The problem is here:

https://github.com/marklogic/node-client-api/blob/master/lib/graphs.js#L734

It's present for both 8.0 and latest.

**Comment by ehennum** [comment]
Thanks for spotting that and identifying the miscreant line.  Should be correct now.

**Comment by kcoleman-marklogic** [comment]
Looks good now, thanks. I verified on both 8 and latest.
