### ISSUE TITLE
unable to invoke sparqlUpdate with just update string param

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#236]
This might be a jsdoc bug or user head gap, but the JSDoc for graphs.sparqlUpdate implies (well, more than implies) you can just pass a string as input: "Executes a SPARQL update against the graphs; takes a configuration object with the following named parameters or, **as a shortcut, the SPARQL update data**."

However, I find this is not so. For example, this works:
```javascript
db.graphs.sparqlUpdate({
   data: 'CREATE GRAPH <http://marklogic.com/semantics/tutorial/update> ;'
 })
```
But this does not:
```javascript
db.graphs.sparqlUpdate('CREATE GRAPH <http://marklogic.com/semantics/tutorial/update> ;')
```
The latter coughs up the following error:
```
"RESTAPI-INVALIDCONTENT: (err:FOER0000) Invalid content: No query to execute"
```

I'll tag this for 8.0-5, but it's probably too trivial to be worth worrying your pretty little head over at this point.

**Comment by kcoleman-marklogic** [comment]
For the sake of completeness, here's the whole script I was fiddling about with. I confess I was executing it against LATEST, if that matters.
```javascript
var marklogic = require('marklogic');
var my = require('./my-connection.js');

var db = marklogic.createDatabaseClient(my.connInfo);

db.graphs.sparqlUpdate('CREATE GRAPH <http://marklogic.com/semantics/tutorial/update> ;')
// db.graphs.sparqlUpdate({
//   data: 'CREATE GRAPH <http://marklogic.com/semantics/tutorial/update> ;'
// })
.result(
    function(response) { 
      console.log(JSON.stringify(response));
    },
    function(error) { console.log(JSON.stringify(error)); }
);
```

**Comment by grechaw** [comment]
I would simply double-check the content-type header and/or parameter name (if form POST)

**Comment by MayankBhatnagar89** [comment]
Verified and added test( https://github.com/marklogic/node-client-api/commit/3ee692000618127907d478b4cb0512a15283cae7  )  under test-complete/nodejs-sparql-update.js.

Verified on build MarkLogic-9.0-20160419.x86_64
