### ISSUE TITLE
REGR :  SPARQL query against the merged graph failing

### ISSUE THREAD

**Issue by MayankBhatnagar89** [marklogic/node-client-api#244]
Build : MarkLogic-9.0-20160518.x86_64

Test : nodejs-graphs-merge.js

Location : node-client-api/test-complete/nodejs-graphs-merge.js

Code : 
-------------------------------------------------
  it('should run a SPARQL query against the merged graph', function(done){
    this.timeout(20000);
    db.graphs.sparql('application/sparql-results+json', fs.createReadStream(sparqlPath)).
    result(function(response){
      //console.log(response);
      response.should.have.property('head');
      response.head.should.have.property('vars');
      response.head.vars.length.should.equal(2);
      response.head.vars[0].should.equal('personName1');
      response.head.vars[1].should.equal('personName2');
      response.should.have.property('results');
      response.results.should.have.property('bindings');
      var strResponse = JSON.stringify(response);
      strResponse.should.containEql('Person 2');
      strResponse.should.containEql('Person 12');
      done();
    }, done);
  });
-------------------------------------------------

Expected Output : 
-------------------------------------------------
{
	"head":{"vars":["personName1","personName2"]},
	"results":{
		"bindings":[
			{"personName1":{"type":"literal","value":"Person 1"},"personName2":{"type":"literal","value":"Person 12"}},
			{"personName1":{"type":"literal","value":"Person 9"},"personName2":{"type":"literal","value":"Person 12"}}
		]
	}
}
-------------------------------------------------

Actual Output : 
-------------------------------------------------
{ 
	head: { vars: [ 'personName1', 'personName2' ] },
	results: {
		bindings: [ 
			[Object], 
			[Object] 
		] 
	} 
}
-------------------------------------------------

**Comment by grechaw** [comment]
Weird regression.  If this is an upstream bug, I can help isolate and submit it.

**Comment by wooldridge** [comment]
Test depends on a triple that wasn't getting loaded because of a missing predicate.

**Comment by MayankBhatnagar89** [comment]
The issue is no more in regression. Hence shipping it.
Verified on build : MarkLogic-9.0-20160606.x86_64
