### ISSUE TITLE
Documentation for valuesBuilder.geospatial() missing

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#250]
Need to add a JSDoc "borrows" entry in values-builder.js for queryBuilder#geospatial:

http://usejsdoc.org/tags-borrows.html

https://github.com/marklogic/node-client-api/blob/master/lib/values-builder.js#L71

**Comment by wooldridge** [comment]
Also adding same "borrows" reference for the new geospatialRegion() method.

**Comment by wooldridge** [comment]
@kcoleman-marklogic, this fixes the fact that the geospatial() and geospatialRegion() methods were not showing up in the docs under the valuesBuilder namespace.

**Comment by kcoleman-marklogic** [comment]
Are you sure `geospatialRegion` should be showing up in valuesBuilder? My recollection is that you cannot do a values (or tuples) query against a region index. And, indeed, if I try to do so, I get the following error:
```
xquery version "1.0-ml";
cts:values(cts:geospatial-region-path-reference("/envelope/cts-region"))

(:
XDMP-BADREFERENCE: cts:values(cts:geospatial-region-path-reference("/envelope/cts-region",("coordinate-system=wgs84"))) -- The cts reference cannot be used in this context: cts:geospatial-region-path-reference("/envelope/cts-region",("coordinate-system=wgs84"))
:)
```
You should confirm with Jake, but I do not recall any mention of support for lexicon queries on regions in the overlapping polygon spec.

**Comment by ehennum** [comment]
That's my recollection as well -- range indexes over regions is a potential future.

**Comment by wooldridge** [comment]
Thanks @kcoleman-marklogic and @ehennum. I confirmed with Jake that the region index will not support lexicon calls in 9.0-1.
