### ISSUE TITLE
QueryBuilder.geoOptions() referenced incorrectly in ValuesBuilder

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#251]
ValuesBuilder borrows most of its methods from QueryBuilder. It incorrectly references the geoOptions() method as geoOption(), see:

https://github.com/marklogic/node-client-api/blob/master/lib/values-builder.js#L440

**Comment by wooldridge** [comment]
@kcoleman-marklogic, this fixes the fact that the geoOptions() method was not showing up in the docs under the valuesBuilder namespace.

**Comment by kcoleman-marklogic** [comment]
Looks fine to me.
