### ISSUE TITLE
replaceInsert does not work as expected when "array-node()" is used

### ISSUE THREAD

**Issue by csreddy** [marklogic/node-client-api#252]
Using v1.0.5
This does not work. Meaning it inserts a new item into the array instead of replacing existing one

```
p.replaceInsert("/array-node('users')[username eq '"+ user.username+ "']", "array-node('users')", 'last-child', user)
```

this works

```
p.replaceInsert("/users[username eq '"+ user.username+ "']", "array-node('users')", 'last-child', user)
```

my document looks something like this

```
{
    "users": [
        {
            "username": "sreddy",
            "email": "sreddy@marklogic.com",
            "name": "Sudhakar Reddy",
            "active": true
        }
    ]
}
```

**Comment by ehennum** [comment]
Hi, Sudhakar: This limitation is well known and documented. Our current mechanism for sanitizing XPaths is too limiting. A better mechanism for sanitizing XPaths would have to be implemented in the server. The Node.js API can't solve this problem.
