### ISSUE TITLE
Optic API support

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#258]
- Plan builder to express queries in JavaScript
- Interoperability with other Java builders, such as cts:query or QBE
- Efficient handling of tuple results
- Map results to JavaScript/Node types and common I/O patterns (e.g. streams)
- Performance, especially for large record sets, millions of results, rather than pages as we assume with search results

**Comment by jmakeig** [comment]
@popzip The above is place-holder. Let’s figure out specifics.

**Comment by popzip** [comment]
@jmakeig Specifics...are there more specific requirements than the above + Client PRD + Optic PRD?

**Comment by popzip** [comment]
Just wanted to check this is still a post 9.0-1 task and won't make it into EA4 @wooldridge @jmakeig @ehennum

**Comment by ehennum** [comment]
Yes, this will require code generation for the builder, and the bucket for EA4 is full.

**Comment by popzip** [comment]
Okay thanks I thought there was something about code generation and couldn't remember the implication. 

Also why is this an RFE not a task?

**Comment by grechaw** [comment]
Meaning @ehennum is there a server-side dependency still?  @wooldridge is not 100% committed for EA-4 yet, from my initial researches into client api team.

**Comment by ehennum** [comment]
Yes, as noted above, the builder is generated. That requires work outside of Node.js

**Comment by popzip** [comment]
This item is not showing up in Bugtrack, i think because of the RFE label. Can someone update that so it will replicate? to 40991 fyi

**Comment by jmakeig** [comment]
Not to get all metadata on you, @ehennum, but wouldn’t `Task` would be more appropriate than `Bug`?

**Comment by ehennum** [comment]
Done and dusted.  Taking the rest of the day off.

**Comment by MukulAmbulgekar** [comment]
Just FYI - BugTrack imports/syncs issues with RFE label as well. There was no severity label (Major) earlier hence BT sync failed for this issue. I manually synced it now - [40991](https://bugtrack.marklogic.com/40991)

**Comment by ehennum** [comment]
Even better.  (Taking the rest of the month off now.)

**Comment by wooldridge** [comment]
@ayuwono, please see the functional spec on the wiki for details.

**Comment by ayuwono** [comment]
Tests are completed and automated. Shipping this!

**Comment by ehennum** [comment]
Excellent -- thanks heaps, @ayuwono, for squaring that away
