### ISSUE TITLE
Add support for double-precision values for geospatial search

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#262]
Support double-precision floating point values that are now available in geospatial indexes.

**Comment by wooldridge** [comment]
Specifying the precision for a geospatial search involves a simple pass-through of a coordinate-system value via the geoOptions() method. Given the changes to the underlying APIs, there should now be support for the new values "wgs84/double" and "raw/double".

**Comment by kcoleman-marklogic** [comment]
Did you happen to slip in etrs89 and etrs89/double while you were at it? That's a new coordinate system we've added.

**Comment by wooldridge** [comment]
Thanks, Kim! So, the following coordinate-system values are now supported:

- raw
- wgs84
- etrs89
- raw/double
- wgs84/double
- etrs89/double

**Comment by kcoleman-marklogic** [comment]
Correct. ETRS89 was not in EA2, but it is in EA3.

**Comment by ayuwono** [comment]
Added tests on nodejs-document-query-geo-double.js
