### ISSUE TITLE
Add support for certificate-based authentication

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#264]
Support authentication based on a certificate authority (a trusted third party) to prove the validity of the public key associated with a certificate.

**Comment by wooldridge** [comment]
@ayuwono for usage examples, see:

https://github.com/wooldridge/ml-certauth

**Comment by ayuwono** [comment]
Manual test on https://github.com/wooldridge/ml-certauth is passed

**Comment by ayuwono** [comment]
Manual test is working fine
