### ISSUE TITLE
config.resources.read() returns a Buffer object instead of a string

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#269]
When reading the source code of an installed resource service extension with the following:

https://docs.marklogic.com/jsdoc/config.resources.html#read

For example:

```
    db.config.resources.read(serviceName)
      .result(function(response){
        console.log(response);
      });
```

The read() method returns source code as a Buffer object, for example:

<Buffer 2f 2f 20 47 45 54 0a 2f 2f 0a 2f 2f 20 54 68 69 73 20 66 75 6e 63 74 69 6f 6e 20 72 65 74 75 72 6e 73 20 61 20 64 6f 63 75 6d 65 6e 74 20 6e 6f 64 65 20 ...>

It should return a string. This can be achieved above like so:

```
console.log(response.toString('utf8'));
```

This may also be the case for similar methods, e.g.:

https://docs.marklogic.com/jsdoc/config.transforms.html#read

Need to investigate.

**Comment by wooldridge** [comment]
Similar issue was found in config.transforms.read(), fixes both.

**Comment by MayankBhatnagar89** [comment]
Fix works. Verified on build MarkLogic-9.0-20161101.x86_64.
Hence shipping this bug.
