### ISSUE TITLE
Wildcard search is not working on parsedFrom query

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#27]
Wildcard search is not working on parsedFrom query

Write this document:

uri: '/test/query/matchDir/doc5.json',
collections: ['matchList'],
contentType: 'application/json',
content: {
  title: 'The memex',
  popularity: 5,
  id: '0026',
  date: '2009-05-05',
  price: {
       amt: 123.45
     },
  p: 'The Memex, unfortunately, had no automated search feature
  }

Run a parsedFrom query with a wildcard on the query string

        return db.query(
                 q.where(
                   q.parsedFrom('0?26',
                     q.parseBindings(
                       q.word('id', q.bindDefault())
                     )
                   )
                 )
               ).result();

This will not return any result, it works fine on regular query builder (non parsedFrom)

**Comment by ehennum** [comment]
closed internally
