### ISSUE TITLE
Update open-source inventory

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#271]
Make sure we’ve documented third-party code and anything required to comply with its licenses.

**Comment by wooldridge** [comment]
New third-party code in ML9:

https://www.npmjs.com/package/kerberos [Apache 2.0]

**Comment by wooldridge** [comment]
@jmakeig, where do we document this? For example, I don't see the Node.js Client API dependencies listed here:

https://wiki.marklogic.com/display/PM/MarkLogic+Server+Open+Source+Inventory

**Comment by wooldridge** [comment]
We do take the DocStrap documentation template, modify it, and include the modified version in the Node.js Client API distribution. Checking with legal about how to deal with this.

**Comment by wooldridge** [comment]
Guidance from Zak: 

> To satisfy the third-party notice requirement, please add the attached NOTICE file to the root repo directory. Please also update the LICENSE file in the repo with the standardized one posted on the Wiki: https://wiki.marklogic.com/display/LEG/Open+Source.

and

> Come to think of it, let's use the SPDX link to help ensure persistent availability (the template format of this license is acceptable since we already reproduce the copyright notice in our text): https://spdx.org/licenses/MIT.html.

**Comment by wooldridge** [comment]
Files have been updated/added:

https://github.com/marklogic/node-client-api/blob/develop/LICENSE
https://github.com/marklogic/node-client-api/blob/develop/NOTICE

**Comment by wooldridge** [comment]
Content above OKed by Zak by email, closing issue.

**Comment by wooldridge** [comment]
To document current license requirements, I ran the following on this project, as recommended by @ehennum:

https://www.npmjs.com/package/license-checker

Then I attached the results to the Open Source Inventory on the wiki here:

https://wiki.marklogic.com/display/PM/MarkLogic+Server+Open+Source+Inventory+-+New
