### ISSUE TITLE
geoOptions() is not working on geospatialRegion()

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#273]
It seems that geoOptions() is not working on geospatialRegion()

This query:

```
    dbWriter.documents.query(
      q.where(
        q.geospatialRegion(
          q.geoPath('/root/item/point'),
          'contains',
          q.geoOptions('coordinate-system=wgs84'),
          q.point(0, -66.09375)
        )
      )
    )
```

Will throw this error:

```
{ [Error: query documents: response with invalid 400 status]
  message: 'query documents: response with invalid 400 status',
  statusCode: 400,
  body:
   { errorResponse:
      { statusCode: 400,
        status: 'Bad Request',
        messageCode: 'XDMP-OPTION',
        message: 'XDMP-OPTION: cts:geospatial-region-query(cts:geospatial-region-path-reference("/root/item/point",("coordinate-system=wgs84")), "contains", cts:point("0,-66.09375"), "coordinate-system=wgs84") -- Invalid option "coordinate-system=wgs84"' } } }
```

**Comment by ayuwono** [comment]
If you have region-path-index with coordinate system wgs84/double

```
<geospatial-region-path-index xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://marklogic.com/xdmp/database">
  <path-expression>/root/item/box</path-expression>
  <coordinate-system>wgs84/double</coordinate-system>
  <geohash-precision>2</geohash-precision>
  <invalid-values>ignore</invalid-values>
</geospatial-region-path-index>
```

And run the script:
```
    dbWriter.documents.query(
      q.where(
        q.geospatialRegion(
          q.geoPath('/root/item/box'),
          'contains',
          q.geoOptions('coordinate-system=wgs84/double'),
          q.polygon([q.point(-5, -70), q.point(4, -70), q.point(3, -60), q.point(-3, -65), q.point(-5, -70)])
        )
      )
    )
```

It can't find the index, because it doesn't take the geoOptions(), it's defaulting to wgs84

```
{ [Error: query documents: response with invalid 500 status]
  message: 'query documents: response with invalid 500 status',
  statusCode: 500,
  body:
   { errorResponse:
      { statusCode: 500,
        status: 'Internal Server Error',
        messageCode: 'INTERNAL ERROR',
        message: 'XDMP-GEOREGIONIDX-NOTFOUND: cts:geospatial-region-path-reference("/root/item/box", "coordinate-system=wgs84") --  /root/item/box wgs84 . See the MarkLogic server error log for further detail.' } } }

```

**Comment by ayuwono** [comment]
It seems that I put the coordinate-system in the wrong place, 

But it's still throwing the error:
XDMP-GEOREGIONIDX-NOTFOUND: cts:geospatial-region-path-reference("/root/item/box", "coordinate-system=wgs84") --  /root/item/box wgs84

```
    dbWriter.documents.query(
      q.where(
        q.geospatialRegion(
          q.geoPath('/root/item/box', q.geoOptions(['coordinate-system=wgs84/double'])),
          'contains',
          q.polygon(q.point(-5, -70), q.point(4, -70), q.point(3, -60), q.point(-3, -65), q.point(-5, -70))
        )
      )
    )
```

**Comment by kcoleman-marklogic** [comment]
Since I can't currently build the JSDoc (grrr) and can't find a func spec for the Node.js changes (double grrr), I can't check this, but it seems likely to me that `q.geoPath` is not the correct index reference constructor. 

That is almost certainly going to construct a reference to a point index, not a region index. Point indexes are the same geo indexes we've always had; region indexes are new hawtness, and they are very much different index types.

See if the API now has something like a `q.geoRegionPath` helper.

**Comment by ayuwono** [comment]
There is no such thing as geoRegionPath in the lib. The spec mentioned that it should use geoPath. I can find all the results using geoPath, but just the geoOptions that's not working

**Comment by ayuwono** [comment]
[test-setup-qa.zip](https://github.com/marklogic/node-client-api/files/415931/test-setup-qa.zip)

**Comment by ehennum** [comment]
Thanks for the setup

**Comment by ayuwono** [comment]
Unzip the file, put the setup file on etc/ folder then run node etc/test-setup-qa.js

**Comment by ehennum** [comment]
The root issue is that the options are being treated as namespaces.  A path can take a map of namespaces but also options. At present, pathIndex() and geoPath() support only the namespaces.

**Comment by ehennum** [comment]
Correction.  In the Search API, a geospatial region path take only coord, which is not modelled as a geospatial option.

**Comment by ehennum** [comment]
There was also a bug in the REST API as well.  It was not transforming coord from JSON.

**Comment by ehennum** [comment]
@ayuwono please try  q.geoPath('/root/item/box', 'wgs84/double')

@wooldridge my concern with this fix is whether using a bare string is potentially puzzling as well as limiting for future evolution of this call.  So, consider whether it might be better to wrap the parameter with a helper function in the same way as the QueryBuilder elsewhere, as in:

q.geoPath('/root/item/box', q.coord('wgs84/double'))

**Comment by kcoleman-marklogic** [comment]
If you decide to create a helper func, please consider inflicting a few extra characters on users so that the it doesn't sound like a point constructor. For example: q.coordSys, not q.coord.

Also, I'm a bit confused on one point: 

Are we saying that geo path indexes accept no options?  I would think geo point indexes (as distinct from region indexes) need to accept at least the `type` option for specifying coordinate order, even if you want to ignore the ability to override the precision implicit in the coordinate system name using the `precision` option.

**Comment by ehennum** [comment]
Good catch on the potential for misreading the name and on the options.  

@wooldridge , I'll go with qb.coordSystem as the name for now, which can be revised in the next iteration.

Let's make the options a separate bug and fix it in the next iteration.  (I wonder whether there is a need for the precision given that the precision is explicit in the coordinate system, but I'm shallow on some of the geospatial specifics.)

**Comment by kcoleman-marklogic** [comment]
On the server, the `precision` option is an override on the precision implicit in the coordinate system name. It might have more of a role server-side than client-side. I don't really know what use cases Jake had in mind when he exposed the override. I assumed you guys eyed it skeptically and decided not to include it in Search API & Friends.

**Comment by ehennum** [comment]
Okay, qb.coordSystem() has landed -- see the Query Builder unit test for same.

I'll pursue the options offline.

**Comment by ayuwono** [comment]
Verified q.coordSystem is working
Added tests: nodejs-documents-query-geo-region.js
