### ISSUE TITLE
There is no representation of cts:linestring() on Node.js Client API

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#274]
There is no representation of cts:linestring() on Node.js Client API

On xquery, we can do something like:

```
   xquery version "1.0-ml";

   let $point-index := cts:geospatial-region-path-reference("/root/item/point",("coordinate-system=wgs84"))
   let $linestring := cts:linestring((cts:point(-1,-50.9877),cts:point(83.229523,-34.453123), cts:point(-1,-54.6798)))
   let $docs :=  cts:search(fn:doc(), cts:geospatial-region-query( $point-index, "intersects", $linestring))
   return $docs
```

Tried q.linestring() or q.lineString() but both are not recognized as functions

```
    dbWriter.documents.query(
      q.where(
        q.geospatialRegion(
          q.geoPath('/root/item/box'),
          'contains',
          q.linestring([q.point(-5, -70), q.point(4, -70), q.point(3, -60), q.point(-3, -65), q.point(-5, -70)])
        )
      )
    )
```

**Comment by kcoleman-marklogic** [comment]
If you're going to jump in with both feet, cts:complex-polygon probably has no equivalent, either. The six types of geo regions ML supports are: point, linestring, box, polygon, complex polygon, and circle.

HOWEVER, historically (if structured query can be said to be old enough to refer to that way), structured query has not supported any regions except point, circle, box, and polygon. The Search schema has not, as yet, been modified to support linestring or complex-polygon. It's not in the Search Deltas spec, either.

So we might first need to settle the issue at the server level before we can say whether or not the Node.js API is missing some region helper funcs.

**Comment by ayuwono** [comment]
Yes, complex-polygon is not there. If we agree for not supporting both of them in Node.js Client API, I will skip the testing on these regions

**Comment by ehennum** [comment]
I can confirm the Search API doesn't support cts:line-string or cts:complex-polygon.

So, the Node.js API can't support them.

**Comment by ehennum** [comment]
Setting the status to closed on that basis.

**Comment by wooldridge** [comment]
Thank you @ehennum
