### ISSUE TITLE
fragmentScope() doesn't take any effect on geoSpatialRegion

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#276]
It seems that fragmentScope is not taking any effect. When I put properties as the value, it's still returning the documents although the documents don't have any properties

Shouldn't it return no document?

```
    dbWriter.documents.query(
      q.where(
        q.geospatialRegion(
          q.geoPath('/root/item/point'),
          'equals',
          q.point(0, -66.09374),
          q.geoOptions(['tolerance=1']),
          q.fragmentScope('properties')
        )
      )
    )
```

**Comment by ehennum** [comment]
Hmmm.  The Node.js API is sending the qualification to the REST API.

**Comment by ehennum** [comment]
The root cause is in the Search API.

**Comment by ehennum** [comment]
We should add tests on the Search API to confirm that the fragment scope from geospatial queries is getting passed in.  Previously, only the fragment scope from the options for geospatial queries was passed.

**Comment by ayuwono** [comment]
Added test on nodejs-documents-query-region.js
