### ISSUE TITLE
Document 9.0-ea3 changes

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#285]
- Kerberos

**Comment by wooldridge** [comment]
@jmakeig you can find info about 9.0-ea3 changes (and 9.0-ea4 changes) here:

engsvn/engweb/specifications/functional/b9_0/Nodejs_Client_API

Let me know if you need anything else from me and close this if the above is sufficient.

**Comment by gvaidees** [comment]
Can this be closed?
