### ISSUE TITLE
documentation for bitemporal capability

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#291]
Alex noticed that the bitemporal features are missing some documentation such as the temporal collection in the document descriptor in the JSDoc and in the user guide.

**Comment by wooldridge** [comment]
The temporalCollection property currently is not at the level of document descriptor, for example:

https://docs.marklogic.com/jsdoc/documents.html#write

In the REST spec, I don't see temporal-collection at the Content-Disposition level like temporal-document is for multipart writes. I'm interpreting this as temporal-collection doesn't belong in the document descriptor but rather as a URL param.

**Comment by ehennum** [comment]
As I understand it, the expectation is that most adopters will have a single temporal collection for the entire database. As a result, there's no requirement to specify different temporal collections for different documents in the same batch. In other words, the temporal collection is at the request level, not at the document level.  

I believe the specification of the temporal collection already works and requires no changes.

**Comment by wooldridge** [comment]
Great, the existing temporal collection param is documented as it should be and the new temporal document param will be documented in the document descriptor as part of #294.
