### ISSUE TITLE
Add request origination self identifier for Node.js API metrics

### ISSUE THREAD

**Issue by popzip** [marklogic/node-client-api#292]
Using Telemetry, we can track feature usage at a granular level. For example, the Optic API will be tracking # of joins. We need a way to track where a request originated when coming from the Client APIs. Each client API must include some sort of identifier that the server can use to increment the correct metric (e.g. optic-joins-javascript vs optic-joins-nodejs).

This task is not for a specific metric - just adding the Node.js identifier that can be used by feature tracking mechanism.

**Comment by popzip** [comment]
Follow-up from #258

**Comment by wooldridge** [comment]
See here: 

https://github.com/marklogic/node-client-api/issues/322
