### ISSUE TITLE
Add support for point-in-time queries

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#296]

**Comment by wooldridge** [comment]
@ayuwono, see the functional spec on the wiki for details about the methods updated.

Relevant commits: 
f7b83e7962e9a6108bfaa4fe4085af70ef553fc4
f7f8d12c218006d99f82e3f7f2a25855dc4523eb
fd60f29c99590f41ac10546e42941726ca42b355

**Comment by ayuwono** [comment]
Added tests on test-complete/nodejs-pitq-*.js
