### ISSUE TITLE
Capture stack on MarkLogic error

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#297]
The `MarkLogicError` constructor should capture the stack trace. See the [v8 guidance](https://github.com/v8/v8/wiki/Stack-Trace-API#stack-trace-collection-for-custom-exceptions).

**Comment by jmakeig** [comment]
We should get the stack trace from the **remote error** too, serialize it over the wire, and stash it in the `MarkLogicError` instance. As it is, it's difficult to figure out where errors happen on the server in custom code, like `eval` and `invoke` (and presumably resource extensions).

**Comment by jmakeig** [comment]
@wooldridge, is this still on target for 2.0.1?

**Comment by wooldridge** [comment]
@jmakeig, I'm working on it, AFAICT yes.

**Comment by jmakeig** [comment]
Splentabulous.

**Comment by wooldridge** [comment]
@jmakeig, I've added the Error.captureStackTrace() call to include stack trace information in the MarkLogicError object when the API makes calls to the MarkLogic server. This gives stack information from the API side (Node.js code), e.g.:
```
Error: write single document: cannot process response with 403 status
    at Operation.makeError (/Users/mwooldri/node-client-api/lib/operation.js:215:10)
    at Operation.isResponseStatusOkay (/Users/mwooldri/node-client-api/lib/responder.js:761:33)
    at Operation.responseDispatcher (/Users/mwooldri/node-client-api/lib/responder.js:29:29)
    at ClientRequest.callBackMethod (/Users/mwooldri/node-client-api/lib/mlutil.js:125:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```
This doesn't address the cases of eval(), etc., where there might be useful stack information for the custom code being executed on the server. Here are some examples of what gets returned currently:

Example of a JS eval() error:
```
{ statusCode: 500,
  status: 'Internal Server Error',
  messageCode: 'JS-JAVASCRIPT',
  message: 'JS-JAVASCRIPT: foo(); -- Error running JavaScript request: ReferenceError: foo is not defined',
  messageDetail: { messageTitle: 'Error running JavaScript request' } }
```
(xqueryEval() error is similar)

Example of a resource service error:
```
{ statusCode: 500,
  status: 'Internal Server Error',
  messageCode: 'INTERNAL ERROR',
  message: 'JS-JAVASCRIPT: architecture: foo(), -- Error running JavaScript request: ReferenceError: foo is not defined . See the MarkLogic server error log for further detail.' }
```
I discussed this with @ehennum. To get stack information in the above cases, server work would be needed to be done in C++. From Erik:

> These endpoints are implemented entirely in C++.  Most of the implementation is shared with the XDBC server.
> 
> The C++ code that would have to change is that endpoint code -- not the implementation of the builtin xdmp:eval() and xdmp:invoke() functions exposed to SJS and XQY.  
> 
> In other words, the C++ builtin functions happily throw an error with a call stack but the endpoint invocation of the same code doesn't support a way to return that callstack as the HTTP response.

However, If a developer really wants to inspect the stack trace coming from eval() et al., they can wrap their code in a try/catch themselves and return the error information (including the stack trace) as payload. This is the strategy taken in QConsole to display stack traces.

**Comment by jmakeig** [comment]
@wooldridge, do we have a separate task to capture the _remote_ error stack? If so, please link and we can close this one.

**Comment by wooldridge** [comment]
Additional work moved to https://github.com/marklogic/node-client-api/issues/357.

**Comment by wooldridge** [comment]
@ayuwono reviewed PR.
