### ISSUE TITLE
Support combined query with SPARQL

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#300]
Support combined query with SPARQL by adding functionality to the graphs.sparql() method.

Use the existing "documentQuery" parameter to pass in the qtext, structured query, and options information in the combined query form. 

The SPARQL part of the query would still be passed in via the "query" parameter on the graphs.sparql() method (not as a "sparql" property in the combined query). 

The Node.js queries end up as a combination queries under the hood eventually. So sending things in that way via "documentQuery" should involve a pass-through of sorts.

**Comment by wooldridge** [comment]
@ayuwono, it turns out this wasn't a feature to implement since if you put a combined query into the 'docQuery' parameter of graphs#sparql(), the combined query is handled correctly.

I added some tests for using combined query in test-basic, see caa8b4ad80baf67ba3b995dbdde032b08528dce9. I didn't see any such tests in test-complete. You should probably add some there if they aren't there already.

Note that this is related to #437, a documentation bug.

**Comment by ayuwono** [comment]
Verified passed and added tests
