### ISSUE TITLE
Support Node.js version 6.x for milestone 8.0-6

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#301]
Previously, we've been supporting relatively old versions, >=0.10.26.

Upping the package.json engine version to bring us in line with the current version of Node.js (6.8.0 as of 2016-10-12). 

@jmakeig @ehennum @ayuwono @kcoleman-marklogic

**Comment by wooldridge** [comment]
@ayuwono has been testing on 6.3.1 for the 8.0-6 milestone, so that's what we will guarantee via our package.json.

**Comment by wooldridge** [comment]
Fixed by commit 4add024be3c5c6373ec0c27895840abf0aa1ca17

**Comment by gvaidees** [comment]
Should this be in Test?

**Comment by kcoleman-marklogic** [comment]
FYI, the documentation portion of this is completed.

**Comment by wooldridge** [comment]
@ayuwono Can you please confirm tests pass on develop and 1.0-develop and then close this.

**Comment by ayuwono** [comment]
I have tested it on 10/12 and it's passed. Confirmed passed
