### ISSUE TITLE
Earlier versions of Client API should work with later versions of MarkLogic

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#303]
Version 1.x of the Node.js Client API (compatible with ML8) should also work with ML9, but not support new features available in ML9. (If developers need to use new ML9 features, they will be required to upgrade to 2.x.)

This task is to check 1.x compatibility with ML9 upon the release of ML9 to make sure this is the case. Per discussion with @jmakeig.

**Comment by jmakeig** [comment]
<table>
  <thead><tr><th>&nbsp;</th><th>Client 1.x</th><th>2.x</th></tr></thead>
  <tbody>
    <tr><th>MarkLogic 7</th><td>?</td><td>?</td></tr>
    <tr><th>MarkLogic 8</th><td>Full</td><td>1.x</td></tr>
    <tr><th>MarkLogic 9</th><td>1.x</td><td>Full</td></tr>
  </tbody>
</table>

**Comment by wooldridge** [comment]
Running test-basic suite on MarkLogic/Node.js Client API combinations. Should only see failures for incompatible tests.

**MarkLogic: 8.0-6.3**
**Node.js Client API: develop branch 2017-03-13 (2.x)**
17 test failures
All test failures can be explained by features supported in ML9 and not ML8:

1) document metadata write all except properties with one document should read back the metadata and content:
[TEST FAILED: Trying to write metadataValues properties, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-core.js#L478

2) document metadata write all with one document should read back the metadata and content:
[TEST FAILED: Expecting metadataValues property, which is new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-core.js#L601

3) document metadata write all with one document should read back default metadata
[TEST FAILED: Expecting metadataValues property, which is new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-core.js#L643

4) document metadata write without content "before all" hook:
[TEST FAILED: Trying to write metadataValues properties, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-core.js#L665

5) document patch for metadata should insert, replace, and delete with raw operations:
[TEST FAILED: Expecting metadataValues property, which is new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-patch.js#L241

6) document patch for metadata should insert, replace, and delete with built operations:
[TEST FAILED: Expecting metadataValues property, which is new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-patch.js#L320

7) document query for a built where clause should match no documents:
[TEST FAILED: Checking falseQuery(), which is new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-query.js#L217

8) temporal document should write a temporal document with a temporal URI:
[TEST FAILED: Temporal operations, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-temporal-document.js#L64

9) temporal document "after all" hook:
[HOOK FAILED: Temporal operations, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-temporal-document.js#L28

10) temporal patch "before all" hook
[HOOK FAILED: Temporal operations, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-temporal-patch.js#L30

11) temporal patch "after all" hook:
[HOOK FAILED: Temporal operations, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-temporal-patch.js#L50

12) temporal protect should protect a temporal document with duration and default level:
[TEST FAILED: Temporal operations, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-temporal-protect.js#L91

13) temporal protect should protect a temporal document with an expireTime and level:
[TEST FAILED: Temporal operations, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-temporal-protect.js#L115

14) temporal protect should protect a temporal document with a duration and archivePath:
[TEST FAILED: Temporal operations, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-temporal-protect.js#L144

15) temporal protect should protect a temporal document twice:
[TEST FAILED: Temporal operations, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-temporal-protect.js#L171

16) temporal protect "after all" hook:
[HOOK FAILED: Temporal operations, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-temporal-protect.js#L67

17) temporal wipe "before all" hook:
[HOOK FAILED: Temporal operations, which are new in ML9]
https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-temporal-wipe.js#L29

**Comment by wooldridge** [comment]
**MarkLogic: 9.0-20170113**
**Node.js Client API: tag 1.0.6**
1 test failure
Can be explained by capability in ML8 that was removed in ML9:

1) document content write a language-specified XML string should read back the content:
```
AssertionError: expected '<?xml version="1.0" encoding="UTF-8"?>\n<doc>oui</doc>\n' to contain '<doc xml:lang="fr">oui</doc>'
```

See https://github.com/marklogic/node-client-api/issues/344

**Comment by wooldridge** [comment]
**MarkLogic: 8.0-6.3**
**Node.js Client API: tag 1.0.6**
All tests passed

**Comment by wooldridge** [comment]
**MarkLogic: 9.0-20170113**
**Node.js Client API: develop branch 2017-03-13 (2.x)**
All tests passed

**Comment by wooldridge** [comment]
**MarkLogic: 7.0-20151104**
**Node.js Client API: develop branch 2017-03-13 (2.x)**
Failing at test setup:
```
MacPro-3170:node-client-api mwooldri$ node etc/test-setup.js
admin user (default=admin): 
admin password (default=admin): 

checking for REST users

/Users/mwooldri/node-client-api/node_modules/bluebird/js/release/async.js:61
        fn = function () { throw arg; };
                           ^
Error: POST /manage/v2/roles: cannot process response with 404 status
    at Operation.makeError (/Users/mwooldri/node-client-api/lib/operation.js:215:10)
    at Operation.isResponseStatusOkay (/Users/mwooldri/node-client-api/lib/responder.js:761:33)
    at Operation.responseDispatcher (/Users/mwooldri/node-client-api/lib/responder.js:29:29)
    at ClientRequest.callBackMethod (/Users/mwooldri/node-client-api/lib/mlutil.js:123:17)
    at ClientRequest.g (events.js:286:16)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:472:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
    at Socket.socketOnData (_http_client.js:361:20)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

**Comment by wooldridge** [comment]
**MarkLogic: 7.0-20151104**
**Node.js Client API: tag 1.0.6**
Failing at test setup:
```
MacPro-3170:node-client-api mwooldri$ node etc/test-setup.js
admin user (default=admin): 
admin password (default=admin): 

checking for REST users

/Users/mwooldri/node-client-api/node_modules/bluebird/js/main/async.js:43
        fn = function () { throw arg; };
                           ^
Error: POST /manage/v2/roles: cannot process response with 404 status
```

**Comment by wooldridge** [comment]
In summary, based on running test-basic suite on ML/Node.js combinations: 
<table>
  <thead><tr><th>&nbsp;</th><th>Client 1.x</th><th>2.x</th></tr></thead>
  <tbody>
    <tr><th>MarkLogic 7</th><td>Unable to<br/>run tests</td><td>Unable to<br/>run tests</td></tr>
    <tr><th>MarkLogic 8</th><td>Full</td><td>1.x</td></tr>
    <tr><th>MarkLogic 9</th><td>1.x</td><td>Full</td></tr>
  </tbody>
</table>

Note: For completeness, attempted to update my local ML7 but build process fails on my Mac.

**Comment by wooldridge** [comment]
@jmakeig, please review.

**Comment by jmakeig** [comment]
One major release in each direction for client and server is the requirement. The objective is to allow customers to upgrade clients and server serially, not at the same time. I’m OK with considering 7 “legacy” based on your findings above.

**Comment by kkanthet** [comment]
The expectation is 
- 1.0.6 full regression should pass on ML-8.0-6
- 1.0.6 & 2.0.0 full regression  should pass with marklogic-9.0-1
- for  ML-9.0-1,  1.0.6 full regression should pass in mixed mode (i.e one ML node with ML-9.0-1 and 2 nodes with ML-8.0-6)

**Comment by jmakeig** [comment]
If I'm reading @wooldridge’s table above correctly, we’ve met those requirements.

**Comment by wooldridge** [comment]
@kkanthet, version 1.0.6 of the Node.js Client API has a test in test-basic that does not pass on ML 9 because the REST API in ML 9 has removed support for a deprecated XML attribute, "lang":

https://github.com/marklogic/node-client-api/issues/303#issuecomment-286297394

See here for more details:

https://github.com/marklogic/node-client-api/issues/344

If full regression tests include tests for the "lang" attribute in 1.0.6, then those tests will fail when run on ML 9.

**Comment by wooldridge** [comment]
@jmakeig, I updated the README for 2.0.1 to specify compatibility info. Please review #397.
