### ISSUE TITLE
document protect with invalid path is not throwing any error

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#312]
document protect with invalid path is not throwing any error

```
    db.documents.protect({
      uri: 'someTemporalDoc.json',
      temporalCollection: 'temporalCollection',
      level: 'noUpdate',
      duration: 'P1D',
      archivePath: '/invalidFolder/invalidFile.json'
    })
```

This script is using a folder that doesn't exist. It should throw and error

**Comment by ayuwono** [comment]
Hi @wooldridge , it seems that after the change if I do document protect without any archivePath, the temporalArchiveRecords property is not shown on the metadataValues

```
 db.documents.protect({
      uri: docuri,
      temporalCollection: 'temporalCollection',
      level: 'noUpdate',
      duration: 'P1D'
    })
```

When you do document read, the metadataValues does not have temporalArchiveRecords

    metadataValues:
     { temporalProtectLevel: 'noUpdate',
       temporalDocURI: 'temporalUpdateDoc1.json',
       temporalProtectExTime: '2016-11-04T21:20:43.306197Z' }

**Comment by ayuwono** [comment]
Another test is breaking because of the change, it can't do sequential document protect

document protect for the first time is working

```
db.documents.protect({
      uri: docuri,
      temporalCollection: 'temporalCollection',
      level: 'noUpdate',
      duration: 'P1D'
    })
```

The second document protect failed (say I want to add the archivePath on it)

```
db.documents.protect({
      uri: docuri,
      temporalCollection: 'temporalCollection',
      level: 'noUpdate',
      duration: 'P1D',
      archivePath: '/tmp/archive1.json'
    })
```

{ [Error: protect document: response with invalid 400 status (on temporalUpdateDoc1.json)]
  message: 'protect document: response with invalid 400 status (on temporalUpdateDoc1.json)',
  statusCode: 400,
  body:
   { errorResponse:
      { statusCode: 400,
        status: 'Bad Request',
        messageCode: 'TEMPORAL-PROTECTED',
        message: 'TEMPORAL-PROTECTED: temporal:document-protect("temporalCollection", "temporalUpdateDoc1.json", <options xmlns="temporal:document-protect"><level>noUpdate</level>...</options>) -- The document temporalUpdateDoc1.json is protected noUpdate' } } }

**Comment by wooldridge** [comment]
@ayuwono thanks for testing. Re: the issue where temporalArchiveRecords is now not showing up if the archivePath is not defined. I'm looking at how the built-in functions work (e.g., temporal.documentProtect()), and they don't create a temporalArchiveRecords metadata property when the archivePath param is not specified. So I think the Node.js feature is working as it should be now in that case. I'm looking into the sequential protect issue.

**Comment by wooldridge** [comment]
@ayuwono sequential protect is working for me now, please test. I confirmed with Jane that protecting without an archive path should not result in path metadata values. Also, there have been changes to the archive path metadata property names. I've updated tests to reflect that:

https://github.com/marklogic/node-client-api/blob/develop/test-basic/documents-temporal-protect.js#L163

**Comment by ayuwono** [comment]
hi @wooldridge it seems that sequential protect is still not working

The second protect will thrown the error

```
    db.documents.protect({
      uri: docuri,
      temporalCollection: 'temporalCollection',
      level: 'noUpdate',
      duration: 'P1DT10H3M5S'
    })

db.documents.protect({
      uri: docuri,
      temporalCollection: 'temporalCollection',
      level: 'noUpdate',
      duration: 'P1D',
      archivePath: '/tmp/archiveDoc.json'
    })
```

**Comment by ayuwono** [comment]
I'm logging this on different issue so we don't get confused with the archivePath
