### ISSUE TITLE
Sequential document noUpdate protect is not working

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#326]
It seems that sequential noUpdate protect is still not working

The second protect will thrown the error

```
    db.documents.protect({
      uri: docuri,
      temporalCollection: 'temporalCollection',
      level: 'noUpdate',
      duration: 'P1DT10H3M5S'
    })

db.documents.protect({
      uri: docuri,
      temporalCollection: 'temporalCollection',
      level: 'noUpdate',
      duration: 'P1D',
      archivePath: '/tmp/archiveDoc.json'
    })
```

**Comment by wooldridge** [comment]
This appears to be due to the durations chosen in the test. The following work for me:
```
First protect: 'P1D'
Second protect: 'P1DT10H3M5S'

First protect: 'P1D'
Second protect: 'P1D'
```
The following (same as above test) throws an error:
```
First protect: 'P1DT10H3M5S'
Second protect: 'P1D'
```
Here is the error:
```
'TEMPORAL-PROTECTED: temporal:document-protect("temporalCollection", "tempDoc4.json", <options xmlns="temporal:document-protect"><level>noUpdate</level>...</options>) -- The document tempDoc4.json is protected noUpdate' } } }
```
I will check with Jane about constraints on durations based on previous protects to see whether this is a bug or not.

**Comment by wooldridge** [comment]
Jane said:

> The idea is that you can only extend a protection but cannot shorten it.

So if we're going to test sequential protects on a document, we should use something like the following for the durations:
```
First protect: 'P1D'
Second protect: 'P1DT10H3M5S'
```

**Comment by ayuwono** [comment]
Working fine with longer duration, added test on nodejs-temporal-protect-update.js
