### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#327]
* High-level description
* Most important new/changed functionality
* Detailed change log
* Links to docs, tutorials, MLU, etc.

**Comment by jmakeig** [comment]
@wooldridge Whose responsibility is this? Docs? QA? Dev?

**Comment by wooldridge** [comment]
@jmakeig, I can take a stab at this. Will solicit input from @kcoleman-marklogic.

**Comment by jmakeig** [comment]
It doesn't need a lot of details or “marketing”, just an accounting of what’s changed for developers. The [Data Hub Framework has a good example](https://github.com/marklogic/marklogic-data-hub/releases).

**Comment by kcoleman-marklogic** [comment]
You can take a look at the README from the Java Client API, too. It hasn't been updated for this release yet, but the past releases are entirely suitable references.

**Comment by jmakeig** [comment]
@wooldridge In the interest of operating more like other projects on GitHub, can we move the release-specific stuff out of the main README and put it into the release landing page? I wouldn’t expect the README to change much from release-to-release: 
- What is this thing? 
- How do I install it? 
- What’s the Day 0 “Hello, world!” interaction
- Where can I go for more information?
- Legal disclaimers

**Comment by wooldridge** [comment]
I created a draft release page for the 2.0.0 release:

https://github.com/marklogic/node-client-api/releases

I added the compatibility info and new features there. Also included a link to the complete changelog, which will work after 2.0.0 is cut

I updated the README to remove the compatilibility info for 2.0.0 and the new features, which were moved to the release page: 

https://github.com/marklogic/node-client-api/blob/develop/README.md

Also added new items to the resources list (e.g., MLU resources) and made minor edits across the board.

**Comment by kcoleman-marklogic** [comment]
Looks good to me, but I have one question:

Are we going to leave the EA releases on the Releases page? They seem more like internal detritus than anything else.

**Comment by wooldridge** [comment]
@kcoleman-marklogic I agree about the EA releases cluttering the release page. Makes sense to me to remove EA releases from that page once the corresponding public release has come out. Users can still access EAs via tags if they need to.

**Comment by jmakeig** [comment]
> Makes sense to me to remove EA releases from that page once the corresponding public release has come out.

@wooldridge, sounds prudent.

**Comment by wooldridge** [comment]
Sounds like we're OK with these release notes as they are currently, will close issue.
