### ISSUE TITLE
Near query not returning expected results

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#329]
From @MayankBhatnagar89:

I am working on the automation of Node.js Near Query. Here I am performing a search on two words “Bush” and “Atlantic”
There are total of five json documents which I have inserted and three of them have the words Bush and Atlantic in them.
The only difference in them is the distance which is “1”, “3” and “6”.
Now when I do near query in which I have mentioned distance as 1 . Only one document should be returned which has got distance between Bush and Atlantic as “1” but all three has been returned.
I am mentioning the code below, please have a look into it.
 
Query :
 
it('should do near query', function(done){
    db.documents.query(
      q.where(
        q.near(
          q.term('Bush'),
          q.term('Atlantic'),
          1,                                               #distance as 1
          true,
          q.weight(1)
        )
      )).result(function(response) {
        console.log(JSON.stringify(response, null, 4));
        var document = response[0];
        response.length.should.equal(1);
        response[0].content.id.should.equal('0011');
        done();
      }, done);
  });
 
Documents Inserted :
 
{
      uri: '/test/query/matchDir/doc2.json',
      collections: ['matchCollection1', 'matchCollection2'],
      contentType: 'application/json',
      content: {
        title: 'The Bush article',
        popularity: 4,
        id: '0012',
        date: '2006-02-02',
        price: {
             amt: 0.12
           },
        p: 'The Bush Atlantic article described a device called a Memex'                    #Here the distance is 1
        }
      },
{
      uri: '/test/query/matchDir/doc1.json',
      collections: ['matchCollection1'],
      contentType: 'application/json',
      content: {
        title: 'Vannevar Bush',
        popularity: 5,
        id: '0011',
        date: '2005-01-01',
        price: {
             amt: 0.1
           },
        p: 'Vannevar Bush wrote an article for The Atlantic Monthly'                          #Here the distance i6 6
        }
      },
{
      uri: '/test/query/matchDir/doc3.json',
      collections: ['matchCollection2'],
      contentType: 'application/json',
      content: {
        title: 'For 1945',
        popularity: 3,
        id: '0013',
        date: '2007-03-03',
        price: {
             amt: 1.23
           },
        p: 'For 1945, the thoughts expressed Bush in the Atlantic Monthly were groundbreaking'     #Here the distance is 3
        }
      },
{
      uri: '/test/query/matchDir/doc4.json',
      collections: [],
      contentType: 'application/json',
      content: {
        title: 'Vannevar served',
        popularity: 5,
        id: '0024',
        date: '2008-04-04',
        price: {
             amt: 12.34
           },
        p: 'Vannevar served as a prominent policymaker and public intellectual'
        }
      },
{
        uri: '/test/query/matchList/doc5.json',
        collections: ['matchList'],
        contentType: 'application/json',
        content: {
          title: 'The memex',
          popularity: 5,
          id: '0026',
          date: '2009-05-05',
          price: {
               amt: 123.45
             },
          p: 'The Memex, unfortunately, had no automated search feature policy'
          }
        }

**Comment by wooldridge** [comment]
@MayankBhatnagar89 thanks for discovering this. I suspect my recent commits aren't the culprit here, and that the near query wasn't working to begin with. In the nodejs-documents-query.js file on master, when I change the distance value here:

https://github.com/marklogic/node-client-api/blob/master/test-complete/nodejs-documents-query.js#L286

it has no impact on what results are returned. For example, if I change the distance to 1, the document that contains 'Bush' and 'Atlantic' 6 tokens away is still returned ('Vannevar Bush wrote an article for The Atlantic Monthly'). Can you confirm this (on the master branch)?

I will continue to investigate...

**Comment by wooldridge** [comment]
The test is failing because search queries are run unfiltered by default; also, the word positions index is not turned on.

The test should pass if you either add 'filtered' as a search option:
```
db.documents.query(
  q.where(
    q.near(
      q.term('Bush'),
      q.term('Atlantic'),
      1,
      true,
      q.weight(1)
    )
  ).withOptions({search:['filtered']}))
```
or turn on the word positions index for the database.

**Comment by MayankBhatnagar89** [comment]
Hi Mike,

Adding 'filtered' search option to query is giving desired results.Hence closing the issue.

Thanks,
Mayank
