### ISSUE TITLE
remove crosses, equals, and touches geo region operators from JSDoc

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#332]
The geo region query operators crosses, equals, and touches have been dropped from ML9. They need to be removed from the list of available operator values in the JSDoc for the `operator` param of  `queryBuilder.geospatialRegion`.

http://pubs.marklogic.com:8011/9.0/jsdoc/queryBuilder.html#geospatialRegion

I'm going to assign this to you for now, Mike. If I get around to it first, I'll steal it from you.

**Comment by wooldridge** [comment]
Thanks @kcoleman-marklogic, I will take care of it:

https://github.com/wooldridge/node-client-api/tree/ea4/issue-322-regiondoc
