### ISSUE TITLE
Correct sloppy JSDoc language wrt coordinates

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#333]
The JSDoc talks about coordinates in several places as if a point is a coordinate, rather than the components of a point being the coordinates.  It's like we took the terminology for a box (which is defined by 4 coordinates in ML) and ran with it for everything. A polygon, for example, is defined by a set of points, not just some random jumble of coordinates.

I see this going on in the following `queryBuilder` methods and types:
* latlon: "Specifies the latitude and longitude for a coordinate..." and returns "a coordinate ". 
* LatLon: "...for a coordinate of a queryBuilder.Region." 
* polygon: "Specifies a polygon region as a list of coordinate parameters or as a coordinate array where each coordinate is specified either by..." This is SO very confusing.

Points. It's all points, darnit! :)

It's unfortunate that some of the parameter/call object names propagate this model, but we can at least fix the language of the descriptions.

I'm assigning this one to myself since, if I'm going to be a picky witch about it, the least I can do is fix it myself.

**Comment by wooldridge** [comment]
@kcoleman-marklogic, I'm doing some issue cleanup and am moving this to 9.0.2.

**Comment by anu3990** [comment]
Creating a new Jira ticket.
