### ISSUE TITLE
REGR:Kerberos authentication is not working

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#334]
Using 9.0-EA4 build Dec 7, the authentication is failed with 401 Authorization error

Steps:
Use the steps from https://github.com/wooldridge/ml-kerberos to setup and to run the test

**Comment by ayuwono** [comment]
@wooldridge this is the error message:

```
Error: read documents: kerberos credentials failed (on /file.html)
Debug: deferred promise rejecting with 1 error messages
Debug: kerberos credentials retrieved
Debug: authenticated request for /v1/documents?format=json&uri=%2Ffile.html&category=content
Debug: kerberos authentication
error
{
  "message": "read documents: kerberos credentials failed (on /file.html)"
}
Error: read documents: kerberos credentials failed (on /file.html)
Error: read documents: response with invalid 401 status (on /file.html) { errorResponse:
   { statusCode: 401,
     status: 'Unauthorized',
     message: '401 Unauthorized' } }
Debug: deferred promise rejecting with 2 error messages

```

**Comment by ayuwono** [comment]
The doc is inserted using admin user as a part of setup and we try to read it as user1 (kerberos principal test1@MLTEST1.LOCAL

config.js:

```
var config = {};

config.path = "/space/ml-kerberos/"; // include trailing "/"

config.name = "ml-kerberos";
config.host = "ayuwono-z620.marklogic.com";
config.port = 8019;
//config.port2 = 8060;


config.auth = {
  user: 'admin',
  pass: 'admin',
  sendImmediately: false
};

config.appServer = {
  "server-name": config.name + "-http",
  "server-type": "http",
  "group-name": "Default",
  "root": "/",
  "port": config.port,
  "content-database": "Documents",
  "modules-database": "Modules",
  "authentication": "kerberos-ticket",
  "internal-security": false,
  "external-security": "mykerberos"
}

config.databaseSetup = {
  "database-name": config.name
};

config.forestSetup = {
  "forest-name": config.name + '-1',
  "database": config.name
}

config.restSetup = {
  "rest-api": {
    "name": config.name + "-rest",
    "database": config.name,
    "modules-database": config.name + "-modules",
    "port": config.port,
    "error-format": "json"
  }
}

if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
  module.exports = config;
}
```

**Comment by wooldridge** [comment]
I was able to confirm the bug, I see the same 401 response on my system. I can confirm that the Kerberos handshake is happening and I get the string to put in the negotiate header. Trying to debug further with Arthur.

**Comment by ayuwono** [comment]
If you set ssl-require-client-certificate to false on the external security and the app-server it will work. But I don't recall that we need to set it to false

**Comment by wooldridge** [comment]
I've updated the ml-kerberos project with changes in the following branch:

https://github.com/wooldridge/ml-kerberos/tree/ea4-updates

This includes the fix for setting ssl-require-client-certificate to false.

The one ML configuration step I wasn't able to script was creating external security. I've filed a bug here:

https://bugtrack.marklogic.com/43696

@ayuwono can you test this updated branch? If it works for you I will merge that branch into master. We should also be able to close this bug.

**Comment by wooldridge** [comment]
The `principal` property is not required for the database client setup for Kerberos. That property was extraneous and I removed it in the updated branch. The result you got above shows that the test succeeded.

**Comment by ayuwono** [comment]
The updated branch is working fine and @wooldridge has merged it to master. I'm using Dec 12 and tested more with documents write and query with kerberos client
