### ISSUE TITLE
Alerting via Node.js API?

### ISSUE THREAD

**Issue by tpiros** [marklogic/node-client-api#337]
Hi,

Do you have plans on adding the MarkLogic Alerting capabilities to the Node.js API anytime soon?

**Comment by jmakeig** [comment]
Yes, can you tell me more about your specific use case?

**Comment by tpiros** [comment]
@jmakeig If I remember correctly I have emailed you the requirements - would you like me to paste them here as well?

**Comment by tpiros** [comment]
Do we have any plans to support Alerting from Node.js?

**Comment by ehennum** [comment]
Expanding the description of the use case would be helpful.

**Comment by tpiros** [comment]
The information that I sent to Justin was pretty much saying that I'd like to execute matchmaking and reverse queries from a pure Node.js environment.
