### ISSUE TITLE
add support for true-query and false-query

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#342]
The cts layer grew two new queries last year, `cts:true-query` and `cts:false-query`. Erik has pushed them through to the Client layer by way of `true-query` and `false-query` elements for structured query. We should probably surface them through the `queryBuilder` inteface in the Node.js API.

**Comment by ayuwono** [comment]
Added test on nodejs-documents-query.js

**Comment by wooldridge** [comment]
@kcoleman-marklogic, if you could review the jsdoc stuff for this, that would be great.
