### ISSUE TITLE
Test connection

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#346]
As a developer I want to debug connection issues. I don't want to have to do any real work (i.e. run a dummy query or test the existence of a document) because that's extra work and potentially introduces other errors. I just want to see if my auth*n and network are configured correctly. 

As an ETL tool maker, I want to provide a "Test Connection" button in my UI.

The Client REST API has the undocumented (?) `/v1/ping` endpoint that might be related.

Related to marklogic/java-client-api#636.

**Comment by georgeajit** [comment]
Test runs fine.
