### ISSUE TITLE
Investigate adding tests for agents and connection pooling

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#348]
Our coverage in this area is minimal at the moment. We have the following test for a custom agent:

https://github.com/marklogic/node-client-api/blob/develop/test-basic/client.js#L100

See the following PRs for some background:

https://github.com/marklogic/node-client-api/pull/308 https://github.com/marklogic/node-client-api/pull/286

**Comment by wooldridge** [comment]
Related: #179

**Comment by georgeajit** [comment]
@wooldridge ,

Can you provide some input on what tests are needed for this?
