### ISSUE TITLE
Publish EA4 build to npm

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#349]
https://docs.npmjs.com/getting-started/using-tags

**Comment by jmakeig** [comment]
```shell
npm view marklogic
```

```javascript
{
// snip
'dist-tags': { latest: '1.0.6' },
versions: [ '1.0.0-ea3', '1.0.1', '1.0.2', '1.0.3', '1.0.4', '1.0.5', '1.0.6' ]
// snip
}
```

This looks correct, other than missing all of the `2.0.*` versions. (I had misinterpreted the meaning of `dist-tags` earlier. They are aliases that point to a version.) We might also consider an `ea` tag that points to the latest, non-GA release. 

As part of this, can you also document the publishing process in a document or wiki page here in the repo?

**Comment by wooldridge** [comment]
Thanks, @jmakeig. Yes, I'm in the process of documenting the publishing process.

**Comment by jmakeig** [comment]
Please also publish `2.0.0-ea4` as part of this task.

**Comment by wooldridge** [comment]
Version `2.0.0-ea4` has been published to npm. To accomplish this, cloned EA4 branch and ran:

`npm publish . --tag ea`

to publish with the 'ea' tag (and not the 'latest' tag). 

```
mwooldri$ npm view marklogic

{ name: 'marklogic',
  description: 'The official MarkLogic Node.js client API.',
  'dist-tags': { latest: '1.0.6', ea: '2.0.0-ea4' },
  versions: 
   [ '1.0.0-ea3',
     '1.0.1',
     '1.0.2',
     '1.0.3',
     '1.0.4',
     '1.0.5',
     '1.0.6',
     '2.0.0-ea4' ],
...
```

**Comment by wooldridge** [comment]
The Node.js Client API release procedure is documented here:

https://wiki.marklogic.com/display/ENGINEERING/MarkLogic+Node.js+Client+API+github+and+npm+Release+Procedure

I added additional information about EA releases based on our recent discussion.

**Comment by jmakeig** [comment]
This looks great. Thanks @wooldridge.
