### ISSUE TITLE
500 Internal Server Error when trying to read document with out-of-scoped variable uri

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#35]
If you try to read a document with out-of-scoped variable uri, you will get 500 Internal Error

// var uri is out of scope somewhere
var uri = '/test/write/somePdfFile.pdf';

it('should read the binary document metadata', function(done) {
  dbReader.documents.read({uris: uri, categories:['metadata']})
  .result(function(documents) {
    var document = documents[0];
    document.quality.should.equal(25);
    document.properties.prop1.should.equal('foo');
    done();
  }, done);
});

2014-08-28T20:14:01.068Z - error: read documents: cannot process response with 500 status (on /test/binary/somePdfFile.pdf) status-code=500, status=Internal Server Error, message-code=RESTAPI-INTERNAL
ERROR, message=RESTAPI-INTERNALERROR: (err:FOER0000) Internal error:  JSON build, unbalanced pairs:

**Comment by ehennum** [comment]
closed internally
