### ISSUE TITLE
Capture stack traces from remote errors

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#357]
When an error occurs in a call to `eval()`, `invoke()`, `xqueryEval()`, or a resource service, expose the stack trace from the server in the Node.js `MarkLogicError` object.

As @jmakeig said in https://github.com/marklogic/node-client-api/issues/297:

> We should get the stack trace from the **remote error** too, serialize it over the wire, and stash it in the `MarkLogicError` instance. As it is, it's difficult to figure out where errors happen on the server in custom code, like `eval` and `invoke` (and presumably resource extensions).

This will require C++ work on the server. From @ehennum: 

> These endpoints are implemented entirely in C++.  Most of the implementation is shared with the XDBC server.
> 
> The C++ code that would have to change is that endpoint code -- not the implementation of the builtin xdmp:eval() and xdmp:invoke() functions exposed to SJS and XQY.  
> 
> In other words, the C++ builtin functions happily throw an error with a call stack but the endpoint invocation of the same code doesn't support a way to return that callstack as the HTTP response.

QConsole is able to get stack information by wrapping executed code in try/catch statements. This may or may not be relevant. See: Apps/qconsole/endpoints/evaljs.sjs

**Comment by wooldridge** [comment]
@jmakeig, right, no work has been done to support this yet. Changed label back to "fix."

**Comment by georgeajit** [comment]
Test the conditions.
