### ISSUE TITLE
Apply npm shrinkwrap prior to release

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#358]
[npm shrinkwrap](https://docs.npmjs.com/cli/shrinkwrap) is a command line tool for npm that locks down the versions of a project’s dependencies. It lets you control exactly which versions of each dependency will be installed when a user runs `npm install`.

I researched shrinkwrap and presented to the API Team:

https://wiki.marklogic.com/display/~mwooldri/npm+shrinkwrap

The response from the team was positive. We've also implemented this in [Samplestack](https://github.com/marklogic/marklogic-samplestack).

Once our dependencies are locked down for this Node Client API release and the code is tested by QA, we will add `npm-shrinkwrap.json` file to lock down dependencies.

**Comment by wooldridge** [comment]
Related: https://github.com/marklogic/node-client-api/issues/343

**Comment by wooldridge** [comment]
@ayuwono, I've added an npm-shrinkwrap.json file to local down dependencies based on current package.json (after #394 dependencies were added). 

Please test. We can easily remove or regenerate this file (based on changed dependencies) if needed.

**Comment by ayuwono** [comment]
npm install and running test regression on test-complete are fine
