### ISSUE TITLE
Come up with forward and backward compatibility policy for node-client-api

### ISSUE THREAD

**Issue by kkanthet** [marklogic/node-client-api#359]

**Comment by jmakeig** [comment]
@kkanthet Is this done?

**Comment by kkanthet** [comment]
This can be closed , the basic rule is to support 
* Last client release of previous version with 
* Latest version of the server  with latest client release
EX: 1.0.6 with server 8.0-7 
      2.0.3 with 9.0-3
      2.1.1 with 9.0-4


Upgrade from 
* Last release of previous version of the client to latest version of the client(same upgrade path for server)
* previous version of the client to latest version of the client (same with server) 
Ex: 1.0.6 to 2.1.1
