### ISSUE TITLE
Deploy updated jsdocs to pubs and docs.marklogic.com

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#372]
Generate jsdocs content for the 2.0.0 release and deploy it to pubs and docs.marklogic.com. This should happen close to the time of the release so as to pick up all documentation changes for the release. 

The jsdocs libraries are being updated for this release so there may be bumps to smooth over, see #363. E.g., need to make sure inline JavaScript is extracted from template files.

**Comment by kcoleman-marklogic** [comment]
Once you merge your changes to the develop branch, they'll get picked up automatically by the doc build and we can see if there are problems.

**Comment by wooldridge** [comment]
Merged jsdoc updates in PR https://github.com/marklogic/node-client-api/pull/374.

**Comment by wooldridge** [comment]
When deployed to pubs, index.html page looks OK but clicking through to another page throws the following error:
```
docstrap.lib.js:formatted:2534 Uncaught DOMException: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document.
    at Function.buildFragment (http://pubs.marklogic.com:8011/9.0/jsdoc/scripts/docstrap.lib.js:2:20957)
    at Function._.parseHTML (http://pubs.marklogic.com:8011/9.0/jsdoc/scripts/docstrap.lib.js:3:16626)
    at _.fn.init (http://pubs.marklogic.com:8011/9.0/jsdoc/scripts/docstrap.lib.js:2:709)
    at _ (http://pubs.marklogic.com:8011/9.0/jsdoc/scripts/docstrap.lib.js:1:9644)
    at HTMLDivElement.<anonymous> (http://pubs.marklogic.com:8011/9.0/jsdoc/scripts/toc.js:151:16)
    at Function.each (http://pubs.marklogic.com:8011/9.0/jsdoc/scripts/docstrap.lib.js:1:12113)
    at _.fn.init.each (http://pubs.marklogic.com:8011/9.0/jsdoc/scripts/docstrap.lib.js:1:10090)
    at _.fn.init.$.fn.toc (http://pubs.marklogic.com:8011/9.0/jsdoc/scripts/toc.js:148:17)
    at XMLDocument.<anonymous> (http://pubs.marklogic.com:8011/9.0/jsdoc/scripts/extracted/highlight.js:43:15)
    at k (http://pubs.marklogic.com:8011/9.0/jsdoc/scripts/docstrap.lib.js:2:3465)buildFragment @ docstrap.lib.js:formatted:2534_.parseHTML @ docstrap.lib.js:formatted:3826_.fn.init @ docstrap.lib.js:formatted:1580_ @ docstrap.lib.js:formatted:493(anonymous function) @ toc.js:151each @ docstrap.lib.js:formatted:620each @ docstrap.lib.js:formatted:519$.fn.toc @ toc.js:148(anonymous function) @ highlight.js:43k @ docstrap.lib.js:formatted:1713fireWith @ docstrap.lib.js:formatted:1769ready @ docstrap.lib.js:formatted:1863g @ docstrap.lib.js:formatted:47
```
Note the error text `The provided markup is invalid XML`. Most likely need to rewrite some generated HTML (probably in `toc.js`) to make it conform to XML standards.

**Comment by wooldridge** [comment]
The error is being caused by HTML generation in the following script file:

https://github.com/docstrap/docstrap/blob/master/template/static/scripts/docstrap.lib.js

and not in a template or script file higher up that would be more straightforward to diagnose and edit.

My current plan is to try previous versions of the docstrap template. I hope to find a version that plays nicely with our system and its requirements for valid XML.

**Comment by jmakeig** [comment]
I still don't understand why docstrap is concerned with XML. Are you [serving the page as application/xhtml+xml](http://stackoverflow.com/a/27825917/563324)?

**Comment by kcoleman-marklogic** [comment]
Docstrap doesn't care about XML, but the app that hosts the docs is a MarkLogic app and it cares very much about XML.

**Comment by wooldridge** [comment]
Switched from v1.3.0 of the docstrap template to v1.1.4 and still see the exact same error from the pubs server. (Thanks so much @kcoleman-marklogic for helping with the pubs server setup.) Will try going back further.

**Comment by wooldridge** [comment]
Tried docstrap template v1.0.5, same error.

**Comment by wooldridge** [comment]
Tried docstrap template v0.5.4, this works. No invalid XML complaints.

**Comment by wooldridge** [comment]
docstrap template v1.0.0 works, docstrap template v1.0.1 fails with the invalid XML error. So we will work with template v1.0.0.

**Comment by wooldridge** [comment]
This commit is what generates the invalid XML, specifically the changes to how the sidebar is built in scripts/toc.js: https://github.com/docstrap/docstrap/commit/4a00a46b8afd3f8090696a8ad43390656b77c015#diff-47b5846bd13d172323b1ad8ca80495f1R74

**Comment by kcoleman-marklogic** [comment]
This looks good and the sidebar appears to be working now, which is great. Thanks!

There does seem to be something off about the content, though. What used to be a "DatabaseClient" entry in the namespace dropdown is now "marklogic~DatabaseClient" (which is weird, but probably OK) and is missing quite a lot of methods.

I only see eval, invoke, and and xqueryEval. It's missing all the stuff like read, write, probe, and queryCollection. 

This is unrelated to being hosted on pubs. I see the same thing locally, even with your original upgrade. Perhaps there's some change needed to the markup?

**Comment by wooldridge** [comment]
@kcoleman-marklogic thanks so much for reviewing. I will investigate the DatabaseClient doc issues.

**Comment by kcoleman-marklogic** [comment]
I spent some more time flipping through the new JSDoc. Most of it looks fine, AFAICT, but there are a couple more differences that caught my eye. Possibly, they're WAI from your perspective.

Under patchBuilder, I notice that "Members" all have a "#" prefix, both in the sidebar and in the rest of the page content. Is that intended? They didn't have that before, but I'm not familiar enough with JS to understand whether this is some well known convention.

The return type info is gone from all the functions. For example, queryBuilder.boost used to show it returns a queryBuilder.Query. Now there's no indication of what's returned. I'm guessing this was a victim of trying to tidy up the sidebar, but it is also gone from the function descriptions.

**Comment by jmakeig** [comment]
The `#` is part of JSDoc’s default string serialization of a `memberOf`-related property, i.e. `Person#name`.

**Comment by wooldridge** [comment]
Thanks for the help. Nothing I edited in the template should affect how the jsdoc is being interpreted and displayed in terms of the content. I mainly made CSS tweaks and moved some inline scripts to separate files. Looks like the new version of the jsdoc library is working differently than the previous. I will dig in and try to learn more about jsdoc. @kcoleman-marklogic and @jmakeig, feel free to post any other ideas or findings.

**Comment by wooldridge** [comment]
Working with @ehennum, recovered the missing methods on the marklogic module by tagging marklogic as a namespace instead of a module. This moves marklogic from the Modules top-nav menu to  the Namespaces top-nav menu. There no longer a Modules top-nav menu. 

Unfortunately, this buries the marklogic namespace in the middle of the Namespaces menu. At this point I see no other fix for the missing methods. We can address this by improving the jsdoc documentation (see #373), highlighting the logical "entry points" for using the Node.js Client API in the home page README information. 

Also set the (undocumented) methodHeadingReturns template option to true to display the missing return values in the method signatures.

**Comment by kcoleman-marklogic** [comment]
Looks much better. Thanks, Mike.

Just noticed a couple minor things on the landing page (index.html):
* Don't forget to remove the EA references before ship. It shows up in the Status subsec and you'll want to collapse the "New Features in ... EA*" subsecs into a single "New Features in 2.0.0".  Might want to make a task for that if there isn't already one. 
* Near the top of the Getting Started section are two bullet points that used to be links but now are not. Would be nice if they morphed back into links.

I think all the content on that page is sourced from the project README.md. I notice the bullet points ARE links on the project landing page, so IDK what JSDoc is doing. Obviously, it's not the end of the world if they don't get turned back into links in the JSDoc.

**Comment by kcoleman-marklogic** [comment]
Reassigning to @wooldridge to decide whether to address the README.md related issues above now, as part of this task, or later. (Mostly the EA thing. The links are a very minor issues, IMO, and need not be addressed for ship.)

From my perspective, there is no other action required, and this can be closed.

**Comment by wooldridge** [comment]
Thanks, @kcoleman-marklogic. I agree that this issue has been taken care of and can be closed. Moving the REAME tasks to #386.
