### ISSUE TITLE
REPL interface

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#39]
It's convenient to be able to perform interactive queries at the command line. Node.js provide its own [REPL](http://nodejs.org/api/repl.html). Developers should be able to specify a database and login credentials and then perform interactive calls against the Node API. 

An implementation might actually extend/mix-in the Node REPL with MarkLogic-specific functionality.

**Comment by georgeajit** [comment]
Will rely on Node REPL.
