### ISSUE TITLE
Update dependencies to latest

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#394]
Update the following bring dependencies up to date based on `npm outdated` run on 2017-03-23:

gulp-mocha 3.0.1 -> 4.1.0
should 11.2.0 -> 11.2.1
kerberos 0.0.22 -> 0.0.23

**Comment by wooldridge** [comment]
Addressed in PRs: #392, #393

**Comment by wooldridge** [comment]
@ayuwono, can you confirm that these dependency updates cause no problems with your tests? I ran the tests in `test-basic` on the develop branch after these updates and everything passed.

**Comment by ayuwono** [comment]
Regression on test-complete is passing too
