### ISSUE TITLE
Transition to semver

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#398]
Placeholder, for now.

**Comment by jmakeig** [comment]
Is there a plan to make this happen?

**Comment by kkanthet** [comment]
This should be happening now, is there anything in specific you are looking for ..?

**Comment by wooldridge** [comment]
This might be related, I need to revise the GitHub issue milestones so that issues are tracking on 2.1.1, etc., instead of on the server versions (9.0-4, etc.).

**Comment by jmakeig** [comment]
Version numbers should reflect the client version, not the server.

**Comment by wooldridge** [comment]
GitHub issue milestones have been updated to reflect semver for client version (i.e., 2.1.1 and 3.0.1). Release version numbers shall follow this.
