### ISSUE TITLE
Add krb5.conf info for Kerberos docs

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#401]
A krb5.conf configuration file is required for Kerberos setup. Let's add this to the documentation.

**Comment by wooldridge** [comment]
Here are the suggested edits for this section:

http://pubs.marklogic.com:8011/9.0/guide/node-dev/intro#id_12863

I added a second bullet for krb5.conf (with a link out to the Kerberos documentation). I also combined the trailing sentence with the now-third bullet, and added a link to the documentation for kinit.

------------

Follow these steps to make a TGT available to the client application:

- Install MIT Kerberos in your client environment if it is not already installed. You can dowload this software from http://www.kerberos.org/software/index.html.
- Save a `krb5.conf` [https://web.mit.edu/kerberos/krb5-1.15/doc/admin/conf_files/krb5_conf.html] configuration file on your client host.
- Use `kinit` [https://web.mit.edu/kerberos/krb5-1.15/doc/user/user_commands/kinit.html] on your client host to create and cache a TGT with the Kerberos Key Distribution Center. The principal supplied to `kinit` must be one you associated with a MarkLogic user when performing the steps in Configuring MarkLogic to Use Kerberos.

**Comment by kcoleman-marklogic** [comment]
I changed the labels because if you do not mark something as a new bug (or task...maybe), it does not propagate to bugtrack, and if it does not propagate to bugtrack, I have no bug against which to check in documentation. Docs are not maintained on github.

**Comment by wooldridge** [comment]
Updates look good. Thanks, @kcoleman-marklogic.
