### ISSUE TITLE
npm-shrinkwrap.json has hard coded file paths.

### ISSUE THREAD

**Issue by byrd1089** [marklogic/node-client-api#405]
The hard coded "resolved" file paths for "dependencies" in the npm-shrinkwrap.json causes multiple download errors when trying to install the marklogic "node-client-api" from an npm registry that is located on a private network.

Can you somehow lock down the dependencies version while respecting the "npm config set registry <registry url>"

**Comment by wooldridge** [comment]
Thanks, @byrd1089. We will look into this.

**Comment by wooldridge** [comment]
Related issue: https://github.com/npm/npm/issues/3522

This might help: https://www.npmjs.com/package/rewrite-shrinkwrap-urls

**Comment by byrd1089** [comment]
Thanks Mike, but I don't have access to the NPM registry, other than to
pull from it.

--Jeff

**Comment by jmakeig** [comment]
@byrd1089, I’ve never used a private npm repo. Do other dependencies have this same problem or is `marklogic` unique here? Any additional details on your set-up would be appreciated.

**Comment by jmakeig** [comment]
@byrd1089 Are there other projects that do this correctly with shrinkwrap that you could point me to? Do they not specify `resolve` properties in their shrinkwrap? Thanks for the info.

**Comment by byrd1089** [comment]
Not sure, this is the first time I've come across npm shrinkwrap.

However, I do have a work around.

I downloaded marklogic-2.0.2.tgz from npm.

I opened the archive and modified npm-shrinkwrap.json replacing the
standard npm registry url with my custom url.

Finally, I installed marklogic from my local (modified) tarball.

Works like a charm :-)

Please close the issue.

**Comment by jmakeig** [comment]
@byrd1089, glad you found a way to get it installed. I’m going to keep this issue open as a research task to see if we can make the out-of-the-box experience better. Thanks for your help.
