### ISSUE TITLE
Add support for advancing LSQT

### ISSUE THREAD

**Issue by wooldridge** [marklogic/node-client-api#412]
Background from the MarkLogic documentation: 

"A special timestamp, called the LSQT (Last Stable Query Time), can be enabled on a temporal collection to manage system start times across documents with different URIs. A temporal document with a system start time before the LSQT can only be queried and a document with a system start time after the LSQT can be updated / ingested, but not queried. You can advance the LSQT, either manually or automatically, to manage which documents are available to be queried and which documents can be updated."

The REST API has been updated thusly:

POST /v1/temporal/collections/COLLECTION_NAME?result=advance-lsqt&lag=SECONDS

where

* result is required and can only be "advance-lsqt"
* lag is optional and must be convertible to an xs:long

More background is here:

https://bugtrack.marklogic.com/30342

**Comment by jmakeig** [comment]
@wooldridge, can you please describe the proposed capability for those without BugTrack access?

**Comment by ayuwono** [comment]
Added tests on test-complete/nodejs-temporal-advance-lsqt.js
