### ISSUE TITLE
Receive "ETIMEDOUT" running DatabaseClient.xqueryEval

### ISSUE THREAD

**Issue by tademianhess** [marklogic/node-client-api#417]
Is there a way to specify how long the dbclient should wait for a response when calling  xqueryEval?

Problem:
Created database client and passed query to xqueryEval.
After 5 minutes, the call to xqueryEval() throws "ETIMEDOUT" error (originally thought the limit was 10 minutes, but retested).
Note queries that take less than 5 minutes complete correctly.

Set up:
Application server has Request Timeout and Max Time Limit, and Default Time Limit set to 1200
Running node v6.9.1 connecting to ML 8.0-5.
Should add: running on Windows 10

**Comment by tademianhess** [comment]
My mistake (as usual): I discovered that the code is NOT using the database client--it is posting its request directly to a module using an http library. Very sorry for wasting your time!

**Comment by jmakeig** [comment]
No time wasted. Good to know you figured out your problem. 

I am curious, though, why you’re using HTTP directly and not the Node client.

**Comment by tademianhess** [comment]
A vendor wrote a custom xquery module to handle an http request. Since the endpoint is not handled by ML REST API, we need to make a regular http post to it.

Most of the time I am setting up services using the REST API and so use the ML client—I forgot this was a different case and hence thought the timeout was coming from the node client until I drilled further down into the code.
