### ISSUE TITLE
Delete Multiple documents

### ISSUE THREAD

**Issue by dorlandode** [marklogic/node-client-api#42]
the document.write function allows the passing of an array of objects to write to the database.  It seems like there should be a way to delete an array of objects as well.  document.removeAll allows for the deletion of a directory or a collection, but I want to pass in an array of uris and get a response when the bulk deletion is done.

**Comment by ayuwono** [comment]
@ehennum , are you going to modify the spec and doc for this?

**Comment by ehennum** [comment]
Best to treat as a bug fix?  Supported requests:

db.documents.remove(name1, name2)
db.documents.remove([name1, name2])
db.documents.remove({uris: name1})
db.documents.remove({uris: [name1, name2]})

For backward compatibility, also supports deprecated requests: 

db.documents.remove({uri: name1})
db.documents.remove({uri: [name1, name2]})

Response to db.documents.remove():

{
    uri: name1, // for deprecated backward compatibility
    uris: [name1, name2]
    }

Response to db.remove() for deprecated backward compatibility:

    name1

**Comment by ehennum** [comment]
Because of backward compatibility provisions, the existing regression tests should continue to work unmodified.

**Comment by ayuwono** [comment]
Verified and added test cases on nodejs-documents-remove-multiple.js
