### ISSUE TITLE
db.documents.patch doesn't support patching of XML documents

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#45]
The Node.js API seems to only accept patches by way of bits of JavaScript generated by the patch builder. Whether created by the builder or not, the current "operation" parameters suffer from a fundamental problem: They're JavaScript/JSON. You can only use a JSON patch to patch a JSON document. Patching an XML document requires an XML patch.
 
It seems like we either need a builder or a variant of db.documents.patch that allows you to pass in a raw patch instead of just a series of builder-created operations. The latter would at least allow you to roll your own XML patch. As it stands now, you're just hosed if you're working with XML documents, AFAIK.

**Comment by ayuwono** [comment]
Closing backlog issue, the issue has regression test
