### ISSUE TITLE
improve JSDoc for Optic interfaces

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#450]
The JSDoc is imported from SJS / XQY documentation, so it won't be perfect, but it should at a minimum describe all of the Optic functions supported in the Node.js client.

**Comment by jmakeig** [comment]
You, sir, are a wizard.

**Comment by ehennum** [comment]
A true statement (with a Polish accent) -- in the Nola swamp band, my knickname was "Lizard"

**Comment by ayuwono** [comment]
Documentation looks good
