### ISSUE TITLE
Automatic URI generation

### ISSUE THREAD

**Issue by tpiros** [marklogic/node-client-api#452]
As per the [documentation](https://docs.marklogic.com/guide/node-dev/documents#id_97506) it's possible to automatically generate URIs for documents inserted by leaving out the 'uri' property of the document descriptor.

Where can I find the code that does the automatic URI generation?

**Comment by ehennum** [comment]
Either the uri or the extension property are required (but not both).  The extension identifies the document format and mime type via the mime type mapping table (which can be viewed through the Admin UI on the server).

**Comment by tpiros** [comment]
so let's assume that I specify the extension property to be 'json'. How does the actual URI get generated?

**Comment by ehennum** [comment]
The suffix is appended to a random unsigned long.  If the optional directory property is also set, that's prepended.

**Comment by ehennum** [comment]
By the way, it would be a reasonable request to use sem:uuid() instead of the random long.  There may even be an RFE on the REST API for that option.

**Comment by tpiros** [comment]
So is this random unsigned long generated via some code in the REST API or by the Node.js API?

**Comment by ehennum** [comment]
In the REST API.  That's the usual approach so that different clients don't have to reimplement the same features in a consistent way.

**Comment by tpiros** [comment]
Thanks @ehennum 🥇
