### ISSUE TITLE
different behavior on op.xpath between Optic SJS and Node.js

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#455]
On SJS, this part of the script is working fine:

.select(['uri', 'city', 'popularity', 'date', 'distance', 'point', op.as('nodes', op.fn.number(op.xpath('doc', '//latLonPair/lat')))])

On Node.js the same script will throw an error:
Error: arg argument at 0 of fn.number() must have type XsAnyAtomicType or PlanColumn or PlanParam

But if I don’t use op.fn.number() on Node.js, it will be fine:
.select(['uri', 'city', 'popularity', 'date', 'distance', 'point', op.as('nodes', op.xpath('doc', '//latLonPair/lat'))])

Setup:
1) node config-optic/setupqa.js

Script:
```
const plan1 =
      op.fromLexicons(
        {
          uri: op.cts.uriReference(),
          city: op.cts.jsonPropertyReference('city'),
          popularity: op.cts.jsonPropertyReference('popularity'),
          date: op.cts.jsonPropertyReference('date'),
          distance: op.cts.jsonPropertyReference('distance'),
          point: op.cts.jsonPropertyReference('latLonPoint')
        }, 'myCity'
      );
    const output =
      plan1
      .joinDoc(op.col('doc'), op.col('uri'))
      .orderBy(op.asc('uri'))
      .select(['uri', 'city', 'popularity', 'date', 'distance', 'point', op.as('nodes', op.fn.number(op.xpath('doc', '//latLonPair/lat')))])
      .where(op.isDefined(op.col('nodes')))
    db.rows.query(output, { format: 'json', structure: 'object', columnTypes: 'header' })
```

**Comment by ehennum** [comment]
Thanks for identifying the issue; confirmed with xs.date() on the unit test data set, but should also be fine with fn.number().

**Comment by ayuwono** [comment]
Verified passed and added tests
