### ISSUE TITLE
Unable to set dedup option on fromTriples()

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#457]
On SJS, we can set the dedup option by the following:
```
const output =
      op.fromTriples([
        op.pattern(idCol, bb('age'), ageCol),
        op.pattern(idCol, bb('name'), nameCol),
        op.pattern(idCol, bb('team'), teamCol)
      ], null, null, {dedup: 'on'})
```
The same script on Node.js will produce this error:
 Error: option argument at 3 of PlanBuilder.fromTriples() has invalid argument for PlanTripleOption value: [object Object]

Tried these and it still doesn't work:
{option: 'on'}
{options: 'on'}
{'on'}

**Comment by ehennum** [comment]
Good catch, should be good now.

**Comment by ayuwono** [comment]
Verified passed and added tests on dedup
