### ISSUE TITLE
readable stream for part throws multipart boundary error

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#46]
A request like:

  db.documents.write({
    uri:         '/countries/uv_flag_2004.gif',
    contentType: 'image/gif',
    collections: collections,
    content:     fs.createReadStream('./examples/data/uv_flag_2004.gif')
    })

throws XDMP-MULTIPART-BOUNDARY: xdmp:get-request-part-body(()) -- Ending of the boundary is incorrect.

However, saving a multipart/mixed payload:

curl --anyauth --user rest-reader:x -H "accept: multipart/mixed" -X GET "http://localhost:8015/v1/documents?uri=/countries/uv_flag_2004.gif&category=metadata&category=content" > /tmp/test.gif

and resending

curl --anyauth --user rest-writer:x -i -H "content-type: image/gif" --data "@/tmp/test.gif" -X PUT "http://localhost:8015/v1/documents?uri=/countries/uv_flag_2004.gif"

works fine.  So, the problem is likely a client error. Possibly the server stream ends before the
multipart builder ends.

**Comment by ayuwono** [comment]
Closing backlog issue, the issue has regression test
