### ISSUE TITLE
Confusing parameter name description on all join methods on Node.js Client API doc

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#466]
The name param on join documentation is confusing. For example, here is the Node.js reference for joinInner (/doc/planBuilder.ModifyPlan.html#joinInner): 

```
joinInner(right, keys, condition) → {planBuilder.ModifyPlan}

This method returns all rows from multiple tables where the join condition is met. In the output row set, each row concatenates one left row and one right row for each match between the keys in the left and right row sets. Provides a client interface to a server function. See op.joinInner

Name | Type | Argument | Description
-- | -- | -- | --
right | PlanModifyPlan | <optional> | The row set from the left view.
keys | PlanJoinKey | <optional> | The row set from the right view.
condition | XsBoolean | <optional> | The equijoin from one or more calls to the op:on function.
```

The parameter "right" description says: "The row set from the left view.". It should say the row set from the right view to be consistent with joinInner on docs.marklogic.com

http://docs.marklogic.com/AccessPlan.prototype.joinInner

```
AccessPlan.prototype.joinInner(
   $rightPlan as String,
   $ondef as String,
   [$condition as xs.boolean]
) as ModifyPlan
```

$rightPlan | The row set from the right view.

**Comment by ehennum** [comment]
Parameters should now align for chained methods.

This fix to the JSDoc shouldn't cause regressions.

**Comment by ayuwono** [comment]
Documentation is correct now
