### ISSUE TITLE
The link references are pointing to the wrong address on Node.js Client API doc

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#467]
For example:
The link "See op.joinInner" on joinInner method is pointing to nowhere on docs.marklogic.com (http://docs.marklogic.com/op.joinInner)

The actual link on docs.marklogic.com is: http://docs.marklogic.com/AccessPlan.prototype.joinInner

**Comment by kcoleman-marklogic** [comment]
I noticed today that the jsdoc on pubs is coming off the wrong branch. Tomorrow's build should the optic content and it'll be easier to confirm the correct reference (if that's needed).

**Comment by ehennum** [comment]
Thanks for the input.  The issue in this case is that the code generation is not taking account of the class for the method when building the documentation URIs.

**Comment by ehennum** [comment]
Links for class methods should now point to server-side documentation where it exists.

Functions without server-side documentation shouldn't have links to the server-side documentation.

The fix to the JSDoc shouldn't cause regressions.

**Comment by ayuwono** [comment]
Link references are pointing to the correct SJS doc now
