### ISSUE TITLE
Return total document count in queries

### ISSUE THREAD

**Issue by tpiros** [marklogic/node-client-api#474]
At the moment it's very difficult to work with any sort of pagination widget due to the fact that it's rather complex to retrieve the total number of documents matching a certain search. I'd welcome an optional parameter that we could pass in to the query that would return this information in an easier fashion. This is what I do at the moment:

```javascript
let query = qb.where(qb.collection('property')).withOptions({ queryPlan: true });
let page = 0;

  if (request.query.page && +request.query.page > 0) {
    page = +request.query.page;
  }

  db.documents.query(
    query
      .slice(page === 0 ? 0 : (10 * page))
      .result()
      .then(documents => {
        const data = {};
        // this is required because how queryPlan returns this information
        const total = +documents[0].total ? +documents[0].total : 0;
        if (total > 0) {
          // again this is a hack because of queryPlan's return data
          data.properties = documents.slice(1);
        } else {
          data.properties = [];
        }
        data.total = total;
        response.send(data);
      })
      .catch(error => console.error(error))
    );
```

I'd love to see something in place that works like:

```javascript
// total docs
let query = qb.where(qb.collection('property')).withOptions({ total: true });
// docs with scores
let query = qb.where(qb.collection('property')).withOptions({ score: true });
// or a mix:
let query = qb.where(qb.collection('property')).withOptions({ score: true, total: true });
```

**Comment by ehennum** [comment]
Hi, Tamas:  Thanks for the clear explanation of what you do currently and what you would like to see.

Can you expand on the comment that "this is required because how queryPlan returns this information"? 

What, precisely, makes the current total so difficult to work with? Wouldn't it be trivial to turn the ternary expression condition into the branch branch?

**Comment by tpiros** [comment]
So this is what I get when documents are returned

```
[ { 'snippet-format': 'snippet',
    total: 2400,
    start: 1001,
    'page-length': 10,
    results:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    plan: { 'query-plan': [Object] } },
  { uri: '/property/e0e67bd4-2845-4387-ba78-640d5da35fdb.json',
    category: 'content',
    format: 'json',
    contentType: 'application/json',
    contentLength: '726',
    content: { property: [Object] } },
  // etc
```
In this case I need to remove the first element of the array, which is a weird solution.

The ternary operator is fine but the whole thing could be a bit simpler :)

**Comment by ehennum** [comment]
The query is asking for a query plan.  A query plan is part of the summary. The query plan is not a document.

If the result processor should be able to work with or without a summary, it's going to have to have conditional logic one way or another.  

Making the summary look like a document could be very confusing and cause more problems than it solves.

**Comment by tpiros** [comment]
Couldn't we simplify that information returned by the queryPlan? I know I can do it from my code but we could have a smaller data transferred if we'd only return the 'total' for example.

So the following

```
let query = qb.where(qb.collection('property')).withOptions({ total: true });
```

should return
```
[ { total: 2400 },
  { uri: '/property/e0e67bd4-2845-4387-ba78-640d5da35fdb.json',
    category: 'content',
    format: 'json',
    contentType: 'application/json',
    contentLength: '726',
    content: { property: [Object] } },
  // etc
```

Or would this be too complicated to implement?

**Comment by ehennum** [comment]
The same argument could be made for every other branch within the summary.  "I just need the snippets, please show them at the top."

**Comment by tpiros** [comment]
True - so one last thing then, how to easily return score values for all the results?

Sample:
```
let query = qb.where(qb.collection('property')).withOptions({ score: true });
```

Would love to get:
```
{ uri: '/property/e0e67bd4-2845-4387-ba78-640d5da35fdb.json',
    category: 'content',
    score: 12345
    format: 'json',
    contentType: 'application/json',
    contentLength: '726',
    content: { property: [Object] } },
// etc
```

**Comment by ehennum** [comment]
If I recall correctly, it should be possible to add the score to the summary with

    qb.where(...).slice(0, 10, qb.snippet('empty'))

The result processing would then set the summary in a variable outside the callback and subsequently look up the result (including the score) from the summary for merging into the descriptor for the current document.

Admittedly, that could be cleaner, but that would require an RFE for a thoughtful design.

@wooldridge, any other suggestions?

**Comment by wooldridge** [comment]
@ehennum, your suggestion works for returning score values in the summary for the result documents. I have no better suggestion.

**Comment by tpiros** [comment]
Is this going to be implemented at some point?

**Comment by ehennum** [comment]
@tpiros , don't the comments above explain why things work the way they do and how to accomplish what you've asked about?
