### ISSUE TITLE
Rows queries not supporting database defined in client connection

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#478]
The /v1/rows REST endpoint supports a database parameter for specifying an alternative db, but the Node.js Client API currently does not pass along the db from the DatabaseClient connection configuration. It should.

To reproduce, just make an Optic query using a db client whose connection config specifies an alternative db. For example, set up the SQLdata db and content from the SQL quick start (http://docs.marklogic.com/guide/sql/setup) and then try to query it via port 8000 using Node.js. 

I used that setup and this query:
```
const marklogic = require('marklogic');
const my = require('./my-connection.js');

const db = marklogic.createDatabaseClient(my.connInfo);
const pb = marklogic.planBuilder;

db.rows.query(
  pb.fromView('main', 'employees')
    .select(['EmployeeID', 'FirstName', 'LastName'])
    .orderBy('EmployeeID')
    .limit(3)
).then( function(rows) {
    console.log(JSON.stringify(rows, null, 2));
}).catch(
  function(error) {
    console.log('ERROR:');
    console.log(JSON.stringify(error, null, 2));
});
```

Originally, my db config looked like this:
```
module.exports = {
  connInfo: {
    host: 'myhost',
    port: 8000,
    user: 'myuser',
    password: 'mypassword',
    database: 'SQLdata'
  }
};
```
If you try that, the server squawks that there is no suitable view because it is trying to use Documents. It only started working when I created a REST instance with the following config and changed my connection info to match in Node.js.
```
{"rest-api": {
  "name": "optic-test",
  "database": "SQLdata",
  "port": "8005"
}}
```
I had also confirmed that a raw rest call that included the equivalent plan and `database=SQLdata` worked fine.

(Sorry, @wooldridge , I had to tag this as 2.1.1 because there's not 2.1.2 milestone defined yet.)

**Comment by wooldridge** [comment]
Thanks, @kcoleman-marklogic. 

I can confirm that Optic rows queries in the Node.js Client API do not support the database parameter when it is defined during client creation. I tested by loading and running rows queries on the example data (which now loads a TDE template for the countries documents).

I also confirmed that specifying a database this way works for, for instance, documents.query() queries.

**Comment by ehennum** [comment]
Thanks, Kim and Mike.  The workaround is straightforward -- create an appserver for the database -- but we'll definitely want to fix this one in the next release to expectations are met.

**Comment by wooldridge** [comment]
It's a simple, one-line fix, and I have a branch and test created for it.

**Comment by kcoleman-marklogic** [comment]
Looks to me like it is working now. Thanks!

**Comment by wooldridge** [comment]
PR was approved by mrtriage and merged. Closing this issue.
