### ISSUE TITLE
stream() error handler

### ISSUE THREAD

**Issue by tpiros** [marklogic/node-client-api#479]
I am not sure on the behaviour of the stream() error handler.

Consider the following code with which I'm trying to serve images from the MarkLogic database:

```javascript
server.get('/(^\/$)|(\.(jpg)$)', (request, response) => {
  response.writeHead(200, { 'Content-type': 'image/jpeg' });
  const data = [];
  db.documents.read(request.url).stream('chunked')
  .on('data', chunk => {
    console.log(chunk);
    return data.push(chunk)
  })
  .on('error', error => console.error(error))
  .on('end', () => {
    let buffer = new Buffer(data.length).fill(0);
    buffer = Buffer.concat(data);
    console.log(buffer.toString());
    response.end(buffer);
  });
});
```

This assumes that I have URIs in my database such as `/test-0001.jpg`.

Now my problem is that if I supply a URI that does not exist the `.on('error', ...)` part of my code doesn't get executed. I can see the error in the `.on('end', ()...` handler but only if I convert my buffer to a string (as seen in the example above), which returns:

```
{"errorResponse":{"statusCode":404, "status":"Not Found", "messageCode":"RESTAPI-NODOCUMENT", "message":"RESTAPI-NODOCUMENT: (err:FOER0000) Resource or document does not exist:  category: content message: /test-0120.jpg"}}
```

Not sure how this is supposed to work behind the scenes but I'd expect the error handler to produce an error.

**Comment by tpiros** [comment]
The other problem is that having such logic in place is a bit borked:
```javascript
.on('end', () => {
    let buffer = new Buffer(data.length).fill(0);
    buffer = Buffer.concat(data);
    const bufferResponse = JSON.parse(buffer.toString());
    if (bufferResponse.errorResponse.statusCode === 404) {
      response.send(404);
    } else {
      response.writeHead(200, { 'Content-type': 'image/jpeg' });
      response.end(buffer);
    }
  });
```

That's because now if a valid image comes in the JSON.parse(buffer.toString()) breaks.
I'm still trying to figure out what the best way would be to achieve this. I'd like to return a 404 if a resource is not found in ML.

**Comment by ehennum** [comment]
It makes sense to me that sending the error response to the data event instead of the error event is a bug.

@wooldridge, what do you think?

**Comment by tpiros** [comment]
@ehennum @wooldridge 
Also note that at the moment I have to do this hack to make my code work:

```javascript
const data = [];
  db.documents.read(request.url).stream('chunked')
  .on('data', chunk => data.push(chunk))
  .on('error', error => console.error(error))
  .on('end', () => {
    let buffer = new Buffer(data.length).fill(0);
    buffer = Buffer.concat(data);
    if (buffer.toString('ascii', 0).length < 1000) {
      const bufferResponse = JSON.parse(buffer.toString());
      if (bufferResponse.errorResponse.statusCode === 404) {
        response.send(404);
      }
    } else {
      response.writeHead(200, { 'Content-type': 'image/jpeg' });
      response.end(buffer);
    }
  });
```

**Comment by tpiros** [comment]
Are there any updates on this please?

**Comment by ehennum** [comment]
@tpiros, nothing in plan yet, thanks for refreshing attention on it

**Comment by wooldridge** [comment]
Thanks for the note @tpiros, I will investigate.

**Comment by tpiros** [comment]
Thanks guys!

**Comment by wooldridge** [comment]
Was able to reproduce by loading images into MarkLogic and serving with Express 4.

**Comment by ehennum** [comment]
Digging by @anu3990  determined is that this behavior is specific to reading a non-existent document.

Other errors are correctly sent to the error handler.

A non-existent document is not an error in the request.  The document merely doesn't exist.

The end event code can determine an empty response by checking whether data.length === 0. 

Keeping the bug open for adding the unit test for streaming errors (which was missing).

**Comment by georgeajit** [comment]
Unit test available.
