### ISSUE TITLE
timestamp support missing from optic interfaces

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#480]
According to the func spec, there should be support for point in time queries on the optic interfaces. The spec calls it out a "timestamp" property on RowsOptions. If it was parallel to the way it is surfaced for documents.write, it'd be a param of `rows.query` or `rows.queryAsStream`. 

Either way, it appears to be missing from the JSDoc. I can't speak to whether the impl is supporting it or not.

Apologies in advance if I've simply overlooked it.

**Comment by ayuwono** [comment]
@kcoleman-marklogic, just to confirm that the timestamp implementation is there on rows, and we have some tests. I think it's we need to add it on RowOptions on JSDoc

**Comment by wooldridge** [comment]
The following PR should fix this:

https://github.com/marklogic/node-client-api/pull/481

As @ayuwono mentioned, the functionality was there, there was just a typo in the JSDoc comments (@param -> @property). I also tidied up some cross-links for the timestamp JSDoc references.

**Comment by kcoleman-marklogic** [comment]
I see it now. Thanks.
