### ISSUE TITLE
patch: unable to supply datatype for arg values passed to replace generator functions

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#49]
In a raw patch, you can specify the datatype with which to interpret a param value for a replacement content generator function, whether its builtin or user-defined. There does not seem to be a way to do so through the Node.js patch builder interface. Both the builtin builders like multiplyBy and the roll-your-own apply method seem to allow for just a value instead of a value/datatype pair.

Just to be clear, I'm talking about this sort of thing (of which this is a particularly lame example):
```json
{"patch": [
  {"replace": {
    "select": "/my/data",
    "apply": "ml.concat-between",
    "content": [
      { "$value" : "2013-03-15", $datatype: "date"}       <=======
    ]
  } }
] }
```
I'm tagging this a minor because it does have a workaround (use a raw patch) and probably doesn't come up all that often.

**Comment by ayuwono** [comment]
Verified and added test on nodejs-documents-patch-datatypes.js
