### ISSUE TITLE
Pause of Node.js process before terminating it when running a query

### ISSUE THREAD

**Issue by tpiros** [marklogic/node-client-api#490]
I can't really pinpoint this issue and I definitely haven't been able to figure out what's causing it.

I experience a pause after the query execution and the before termination of the Node.js process.

I am running this code:

```javascript
// app.js
console.time('start-app');
const marklogic = require('marklogic');
const settings = require('./settings');

const db = marklogic.createDatabaseClient(settings);
const qb = marklogic.queryBuilder;

db.documents.query(
  qb.where(
    qb.collection('reviews'),
    qb.term('film')
  )
).result()
.then(response => {
  console.time('db-response');
  const uris = response.map(r => r.uri)
  console.log(uris);
  console.timeEnd('db-response');
})
.catch(error => console.error(error));
process.on('exit', () => {
  console.info('exiting');
  console.timeEnd('start-app');
});
```

```javascript
// settings.js
const host = 'localhost';
const port = 8000;
const user = '';
const password = '';
module.exports = {
  host, port, user, password
};
```

I then run the application via `node app.js` and this is how the output looks like:

```
$ node test.js
[ '/reviews/review14',
  '/reviews/review15',
  '/reviews/review17',
  '/reviews/review18',
  '/reviews/review20',
  '/reviews/review0',
  '/reviews/review1',
  '/reviews/review8' ]
db-response: 1.358ms
exiting
start-app: 6110.513ms
```

Note that when executing this code there's a pause after the db-response: 1.358ms line and the "exiting" line. I'm not sure what's causing this, whether that's the MarkLogic Node.js Client API or Node.js itself.

**Comment by jmakeig** [comment]
Which version of Node, Client API, and MarkLogic?

**Comment by tpiros** [comment]
Node v9.2.1
Node Client API v2.0.3
MarkLogic v9.0-3

**Comment by ehennum** [comment]
I believe the response processing is completely finished when the promise resolves.

Does the timing of the shutdown change if you call db.release() at the end of the then() handler?

**Comment by tpiros** [comment]
uuohhh, nice! 

```javascript
console.time('start-app');
const marklogic = require('marklogic');
const settings = require('./settings');

const db = marklogic.createDatabaseClient(settings);
const qb = marklogic.queryBuilder;


db.documents.query(
  qb.where(
    qb.collection('reviews'),
    qb.term('film')
  )
).result()
.then(response => {
  console.time('db-response');
  const uris = response.map(r => r.uri)
  console.log(uris);
  console.timeEnd('db-response');
  db.release();
})
.catch(error => console.error(error));
process.on('exit', () => {
  console.info('exiting');
  console.timeEnd('start-app');
});

```
Results in:
```
node test.js
[ '/reviews/review14',
  '/reviews/review15',
  '/reviews/review17',
  '/reviews/review18',
  '/reviews/review20',
  '/reviews/review23',
  '/reviews/review0',
  '/reviews/review1',
  '/reviews/review8' ]
db-response: 1.366ms
exiting
start-app: 114.039ms
```

I didn't know we had a db.release() - I did assume that it's automatic. Are there any implications to using it in the `.then()` statement as seen above?

**Comment by ehennum** [comment]
The database client object does release all resources automatically when it is garbage collected.  

Calling the release() function releases resources immediately without having to wait for garbage collection to determine that the database client is no longer used and it is safe to release resources.

The only concern about calling release() is releasing the database client prematurely.  If the database client is used by multiple event handlers and one of them calls release() while another is still making use of the database client, that could have unpredictable and unfortunate effects.

If the application doesn't know whether the database client is still in use, the application should leave it to the garbage collector (and not try to replace the v8 garbage collector in JavaScript code).
