### ISSUE TITLE
parseBindings no longer works

### ISSUE THREAD

**Issue by tpiros** [marklogic/node-client-api#493]
MarkLogic v 9.0-4
Node v: 8.9.4
MarkLogic Node.js API v: 2.1.1

The following code works with the Node.js client API v 1.0.6:

```javascript
const marklogic = require('marklogic');
const dbConn = require('./connections');
const qb = marklogic.queryBuilder;

const dbRead = marklogic.createDatabaseClient(dbConn.restReader);
const dbWrite = marklogic.createDatabaseClient(dbConn.restWriter);
const dbAdmin = marklogic.createDatabaseClient(dbConn.restAdmin);

const qText = 'art:coldplay';

dbRead.documents.query(
    qb.where(
      qb.parsedFrom(qText,
        qb.parseBindings(
          qb.value('artist', qb.bind('art'))
        )
      )
    ).slice(1, 5, qb.extract({
        paths: ['//artist', '//title']
      }))
).result()
.then(matches => {
  matches.map(match => {
    console.log(`Artist: ${match.content.extracted[0].artist}`);
    console.log(`Title: ${match.content.extracted[1].title}`);
    console.log('-----');
  });
})
.catch(error => console.log(error));
```

Running the same code against 2.1.1 no longer returns any results. I also tried `'art:"coldplay"'`. Not sure if this is related to parseBindings or some other part of my code.

**Comment by kcoleman-marklogic** [comment]
While I don't imagine this is the cause of you getting no results (unless you expect only one result), your slice clause is probably not doing what you intend. The default semantics of slice changed for v2. See http://pubs.marklogic.com:8011/guide/relnotes/chap4#id_78125.

**Comment by tpiros** [comment]
@kcoleman-marklogic ahha!!!! this was it! :)
