### ISSUE TITLE
add ConfigurationManager to write configuration packages

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#495]
Administrators need to be able to apply configuration to a production system from a client. In addition, developers need a way to configure a development cluster or to inspect and adapt to the configured environment dynamically (as with reflection).

MarkLogic 9.0-5 is expected to add support for configuration packages.

After that lands, the Node.js API database client should add a configuration method that can write a JSON or XML configuration package. The caller must use a database client for port 8002 or limit the configurations to those accepted on a REST API server and must authenticate with a role having sufficient privileges for the operations.

See also:

https://github.com/marklogic/java-client-api/issues/910

**Comment by georgeajit** [comment]
Supported through ml-gradle
