### ISSUE TITLE
ability to use queryBuilder by itself

### ISSUE THREAD

**Issue by patrickmcelwee** [marklogic/node-client-api#496]
I find myself, in a Node middle-tier, wanting to use the queryBuilder to construct a combined search query, but without using a database client. Instead, I am POSTing it myself to MarkLogic.

(This may change in the future: I may switch to using a database client, though I am worried about connection pools in case my application has many concurrent users, each with their own database client.)

At the moment, it is difficult to get a usable combined query straight from the output of `qb.where()`, which is full of implementation details. But, it seems I can do this by exposing the `makeSearchBody()` function. Would you consider making makeSearchBody() part of the public API?

Or am I missing an easier way to use queryBuilder without a databaseClient?

**Comment by jmakeig** [comment]
I don’t understand your use case. Can you describe a little more what you’re trying to do?

**Comment by ehennum** [comment]
In particular, what's the motivation for avoiding use of the database client?

**Comment by georgeajit** [comment]
Closing the issue to keep API stable.
