### ISSUE TITLE
Allow setting or caching of nonce on a per-user basis

### ISSUE THREAD

**Issue by grtjn** [marklogic/node-client-api#498]
The topic was also raised in #159, but the title doesn't describe the goal desired here. We'd like to keep session state in the middle-tier, mainly to keep the connection with MarkLogic open, but don't want to cache actual credentials for security reasons. It is much nicer to cache the DIGEST nonce, and reuse that as long as possible (it could still expire at some point of course, but that would trigger a session timeout response, telling the user to login again).

Currently the only way to do so with node-client-api, is to cache the entire client object, but as mentioned in the other ticket as well, that is much heavier than really needed. Would it be possible to expose the DIGEST nonce, nc, and such somehow, so we can put that in a session, and pass that into some new client object constructor to continue the connection without actually requiring user pwd? Or perhaps node-client-api could provide some caching mechanism to help with this?

**Comment by ehennum** [comment]
Can reopen if needed.
