### ISSUE TITLE
Allow passing transaction object between services

### ISSUE THREAD

**Issue by g0liushi** [marklogic/node-client-api#499]
When (micro) services are passing transaction objects via http,  the transaction object became a plain JS object (loosing the Transaction class),  and will cause an error when used by the downstream service: `Error: can only undefined transaction with string or Transaction object identifier: object` (because `getTxidParam` in `lib/mlutil.js ` checks the `instanceof Transaction`)

My current solution is either just use the transaction string, or import `lib/mlutil.js` and initiate a new Transaction class locally. 

Is there a better way to handle this? Or is it possible to allow passing a plain JS object and do more sanity checks in `getTxidParam` etc.?

**Comment by ehennum** [comment]
I'm wondering whether the contexts that take a transaction object might do the following:

*  Sniff the type of the transaction object (as currently)
*  If the object doesn't have the transaction type, fall back to passing the object to the transaction object constructor

Possibly this checking logic might be put into a checker() function in the library with the transaction object constructor.

**Comment by georgeajit** [comment]
Works fine.
