### ISSUE TITLE
No API reference?

### ISSUE THREAD

**Issue by jamesgibson14** [marklogic/node-client-api#500]
The link in readme goes back to the home github page, the developer guide is only useful to a point, is there API Documentation?

**Comment by kcoleman-marklogic** [comment]
Like the Java Client API, the Node.js Client API is documented on docs.marklogic.com. Just like there's a dropdown for guides, java, REST, etc. there's one for Node.js. From which you can access:

* http://docs.marklogic.com/jsdoc/index.html
* http://docs.marklogic.com/guide/node-dev
