### ISSUE TITLE
"Expired" nonce not handled

### ISSUE THREAD

**Issue by malteseduck** [marklogic/node-client-api#503]
In cases where ML is clustered behind a load balancer we can have things configured so the same server always gets to the same ML instance, so when the client caches the digest info things are all good.  If that instance goes down and the balancer has to switch to a different DB then all we get from then on are 401s because the "cached" nonce is no longer valid (because it is not valid against the new DB we are pointing to). The ML server does send a challenge with a new nonce so the client could clear out the cache and resend, but it doesn't currently handle that case.  The Java client, or more specifically the HTTP client the Java client is using, does handle that case so we don't have this problem with our Java apps:

https://github.com/rburgst/okhttp-digest/blob/master/src/main/java/com/burgstaller/okhttp/AuthenticationCacheInterceptor.java

Would it be possible to handle this case so this client is more "cluster-friendly"?

**Comment by ehennum** [comment]
Thanks, Chris, for isolating the issue and for pointing at a useful precedent for the fix.
