### ISSUE TITLE
Test multistatement transactions against AWS ELB and ALB

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#505]
In general, we should confirm that multistatement transactions in the Node.js play well with AWS load balancers.

In particular, the Java API had a bug where it was not setting the cookie for the equivalent to this request, causing the request to break for ELB:

http://docs.marklogic.com/jsdoc/transactions.html#read

In addition, the Java API doesn't refresh cookie values after initially set, which apparently can be problematic for ALB:

https://github.com/marklogic/java-client-api/issues/988

The testing might require more effort than the fix.

**Comment by georgeajit** [comment]
Testing Node API in AWS env was done in a separte activity.
