### ISSUE TITLE
Nodejs does not support providing document properties as xml

### ISSUE THREAD

**Issue by peetkes** [marklogic/node-client-api#507]
At the moment document properties can only be supplied as Array.<object>.
When these get stored into MarkLogic you will always get that funny json xml format.
Is it possible to be able to add xml properties as that is currently the native format for document property fragments?

**Comment by anu3990** [comment]
Updated bug - https://bugtrack.marklogic.com/52768

**Comment by ehennum** [comment]
The internal bug identifies the part of the solution that requires a fix to the REST API.

**Comment by ehennum** [comment]
In 10.0-2 and 9.0-11, the REST API will support sending and receiving properties in the following format:
 
` {"properties":{"$ml.xml": "<prop:properties>...</prop:properties>"}}`

The Node.js implementation might not need to change, but a unit test would be useful.

**Comment by georgeajit** [comment]
New test committed on develop branch. See https://github.com/marklogic/node-client-api/commit/5a5075c08280160e31b716800ce82251db44caae
