### ISSUE TITLE
add beforeQuery() and afterQuery() query constructors to queryBuilder

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#508]
The signatures might be similar to:

    beforeQuery(timestamp) → {queryBuilder.Query}
    afterQuery(timestamp) → {queryBuilder.Query}

where timestamp is an unsigned long stated as a string, emitting 

    {"before-query":{"timestamp":"..."}}
    {"after-query":{"timestamp":"..."}}

respectively.

See server bug 50902 for the details.

**Comment by kcoleman-marklogic** [comment]
When this work gets done, please don't forget to notify TechPubs. Probably Eleanor Tesoro, but if in doubt, let Jane M. know.

**Comment by georgeajit** [comment]
Tests are running fine.
