### ISSUE TITLE
SAML authentication

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#513]
As a developer I want to be able to have something further up in the request stack handle user authentication and then pass my app a token that it can validate and pass on to authenticate into MarkLogic. SAML is an industry-standard way of doing this.

**Comment by jmakeig** [comment]
See also JAVA-17 (internal)

**Comment by georgeajit** [comment]
QA Tests using SAML auth were executed and found to be working fine. These tests will be checked into BitBucket and executed in CI mode later.

Shipping the issue.
