### ISSUE TITLE
gulpfile has not been updated

### ISSUE THREAD

**Issue by gfurbush** [marklogic/node-client-api#519]
The gulpfile has not been updated to work with Gulp 4 backward incompatibilities.

**Comment by ehennum** [comment]
Any of the following command lines should now work:

    gulp doc
    gulp lint
    gulp test
    gulp 

The last command (the default) is a synonym for gulp lint.

**Comment by georgeajit** [comment]
The following commands were executed on a system on ```develop``` and MarkLogic Server build 10.0.1 nightly build dated 07022019.
```
npm install --global gulp-cli <- machine did not have gulp installed
npm install --no-optional
node etc/test-setup.js -u admin:admin
gulp doc
gulp test
```
Tools versions on the system are:
```
ageorge@hpzbook-3884 MINGW64 /c/space/HEAD/node-client-api (develop)
$ gulp --version
CLI version: 2.2.0
Local version: 4.0.0

ageorge@hpzbook-3884 MINGW64 /c/space/HEAD/node-client-api (develop)
$ node --version
v10.15.3

ageorge@hpzbook-3884 MINGW64 /c/space/HEAD/node-client-api (develop)
$ npm --version
6.4.1
```

Shipping this issue.
