### ISSUE TITLE
SAML documentation

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#520]
On  createDatabaseClient(), document the token parameter and SAML value for the authType parameter

Document the setAuthToken() method of a DatabaseClient

**Comment by ehennum** [comment]
gulp doc should produce jsdoc that -- on the DatabaseClient page -- has the setAuthToken() method as well as the token parameter for createDatabaseClient()

**Comment by georgeajit** [comment]
Verified on ```develop``` branch. SAML auth details available.
