### ISSUE TITLE
Support for JavaScript modules

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#521]
Support modules with the *.mjs extension as well as with the *.sjs extension

**Comment by georgeajit** [comment]
Tests written and committed to internal repo.

------------------------------------------------------------------------
r306727 | ageorge | 2019-05-09 18:02:47 -0700 (Thu, 09 May 2019) | 1 line

52091 - Use ES6 modules for Optic
------------------------------------------------------------------------
