### ISSUE TITLE
fixup for Optic concat expression test 

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#523]
Because the enode Optic API is no longer sniffing for and enforcing data types but, instead, allowing implicit casts to occur, a string numeric in the concat test is turning into a numeric, which is causing an equality test to fail.

**Comment by ehennum** [comment]
Assigning for awareness and not because additional coverage is needed.

The API didn't change, only a unit test.

The error in the "expressions concat" unit test should be gone now.

If so, this issue can be closed.

**Comment by georgeajit** [comment]
No regressions seen. Verified on ```develop``` branch with 10.0.1 ML server build dated 07022019.
