### ISSUE TITLE
Bubble up xdmp.eval options to MarkLogicClient.prototype.eval

### ISSUE THREAD

**Issue by jmakeig** [marklogic/node-client-api#527]
Optionally allow the client to (at least) select the database and modules context to avoid things like https://github.com/mikrovvelle/mlxprs/blob/master/src/extension.ts#L228-L237.

**Comment by ehennum** [comment]
This request belongs at the REST API level.  The capability has to be exposed there before it can be available in client interfaces.

**Comment by georgeajit** [comment]
Closing the issue until capability is added to REST API.
