### ISSUE TITLE
Data services' errorMapping message not returned to client

### ISSUE THREAD

**Issue by georgeajit** [marklogic/node-client-api#542]
For a ```.api``` file such as
```
{
  "functionName" : "TestParamErrorMapping",
 
  "return" : {
    "datatype" : "float",
    "multiple" : false,
    "nullable" : true
  },
   "errorConditions":[
  {
    "errorCode": "XDMP-LEXVAL",
    "httpStatusCode": 482,
    "errorMessage":"QA LEXVAL Message For 482"
  }
  ]
}
```
and ```.sjs ``` module

```
function TestParamErrorMapping() {
var retDoubleValue;

fn.error(xs.QName("XDMP-LEXVAL"), "XDMP-LEXVAL", "Test for BT Issue 53992");
return encodeURI(10.0);
}

var t = TestParamErrorMapping();
t;
```

A node client call is made to module:
```
const fs = require('fs');
const util = require('util')

const expect = require('chai').expect;
const should = require('should');

const TestRequiredParam = require("./TestRequiredParam.js");

var testconfig = require('../etc/test-config-qa.js');

var marklogic = require('../');
var q = marklogic.queryBuilder;

var db = marklogic.createDatabaseClient(testconfig.restEvaluatorConnection);

describe('TestRequiredParam', function(){
  it('Error mapping', function(done){
    TestRequiredParam.on(db).TestParamErrorMapping().then(res => {
	   console.log("Return value is : %s", res);
          done();
   })
   .catch(err => {
          console.log(err.toString());
          done();
        });	
	});
});
```
The response ( from ```catch(err)``` ) is
```
Error: call to /qa/test/TestRequiredParam/TestParamErrorMapping.sjs: cannot process response with 482 status
```
App Server Access Log:
```
72.31.251.151 - - [01/Apr/2020:14:59:19 -0700] "POST /qa/test/TestRequiredParam/TestParamErrorMapping.sjs HTTP/1.1" 401 104 - -
172.31.251.151 - rest-evaluator [01/Apr/2020:14:59:19 -0700] "POST /qa/test/TestRequiredParam/TestParamErrorMapping.sjs HTTP/1.1" 482 319 - -
```

cURL command 
```
curl --anyauth -v -u admin:admin -X GET "http://localhost:8015/qa/test/TestRequiredParam/TestParamErrorMapping.sjs"
```
to same .sjs module yeilds:
```
{"errorResponse":{"statusCode":482, "status":"QA LEXVAL Message For 482", "messageCode":"XDMP-LEXVAL", "message":"XDMP-LEXVAL: fn.error(xs.QName(\"XDMP-LEXVAL\"), \"XDMP-LEXVAL\", \"Test for BT Issue 53992\"); -- Invalid lexical value Test for BT Issue 53992", "messageDetail":{"messageTitle":"Invalid lexical value"}}}
```
App Server Access Log for cURL command is
```
::1 - - [01/Apr/2020:15:01:03 -0700] "GET /qa/test/TestRequiredParam/TestParamErrorMapping.sjs HTTP/1.1" 401 104 - "curl/7.55.1"
::1 - admin [01/Apr/2020:15:01:03 -0700] "GET /qa/test/TestRequiredParam/TestParamErrorMapping.sjs HTTP/1.1" 482 319 - "curl/7.55.1
```

Issue seen: Don't see ```statusCode":482, "status":"QA LEXVAL Message For 482", "messageCode":"XDMP-LEXVAL", ``` when called using data services.

**Comment by ehennum** [comment]
The full error message is in the structure of the error object.  I'll check in a unit test that demonstrates.

**Comment by ehennum** [comment]
test-basic-proxy/ml-modules/negative/badExecution = a simple example of error mapping

test-basic-proxy/lib/negative/badExecutionTest.js = a simple example of inspecting the mapped error

Note that the badExecutionTest.js depends on the generated badExecution.js client interface to the Data Service endpoint.

The full error message structure looks like this:

`{
  "message": "call to /dbf/test/badExecution/errorMapping.sjs: cannot process response with 418 status",
  "statusCode": 418,
  "body": {
    "errorResponse": {
      "statusCode": 418,
      "status": "Status Message For 418",
      "messageCode": "ERROR_MAPPING",
      "message": "ERROR_MAPPING: fn.error(null, \"ERROR_MAPPING\", \"Test of error mapping\"); --  Test of error mapping",
      "messageDetail": {
        "messageTitle": "ERROR_MAPPING"
      }
    }
  }
}`

That is, the expectation is that the application will look into the error structure instead of just calling toString() on the structure.

**Comment by georgeajit** [comment]
This is a test issue and the following works as demonstrated in unit test.
```
it('Error mapping', function(done){
    TestRequiredParam.on(db).TestParamErrorMapping().then(res => {
	   console.log("Return value is : %s", res);
          done();
   })
   .catch(err => {
          console.log(JSON.stringify(err));
		  //expect.fail(err.toString());
          done();
        });	
	});
```

**Comment by ehennum** [comment]
While console.log(JSON.stringify(err, null, 2)) is a good way to debug, tests can use dot notation to inspect the structure of the object.

See these lines in the unit test for an example of the technique:

https://github.com/marklogic/node-client-api/blob/2eb064fcca980430f0c4db43d0f2822a6467f703/test-basic-proxy/lib/negative/badExecutionTest.js#L17-L22
