### ISSUE TITLE
full outer join

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#555]
Expose support for full outer join in the Optic builder.

**Comment by ehennum** [comment]
See also internal Bug 55200.  Needs no more test coverage than left outer join -- minimal risk, since we're sending the request with the same AST structure with a different string name to apply different join semantics during execution of the plan on the server.

**Comment by georgeajit** [comment]
Performed a manual test on from-views. Does not cause any blow-up and we have a test on Java Client API for this feature.
