### ISSUE TITLE
fixup on JSDoc generated for Optic plan

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#556]
Identified under internal bugs 53912, 53936, 53946, 53945, 54892

**Comment by ehennum** [comment]
Issues for /jsdoc/ reported in internal bugs should be gone once the documentation build picks up the JS doc generated from this fix.

**Comment by georgeajit** [comment]
Built JSDoc locally and navigated to file:///C:/space/b_10/qa/node-client-api/doc/planBuilder.json.html page and then clicked on the "see" links. The resulting page comes up fine and has the SJS contents.
