### ISSUE TITLE
validate *.api when generating Node.js JavaScript interface

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#558]
Validate against the JSON schema when generating the Node.js JavaScript interface for a *.api file

Internal bug: 53357

**Comment by ehennum** [comment]
The code generation of the Data Service unit tests under test-basic-proxy/lib/generated uses the validation and 
thus provides positive cases.

This unit test provides negative cases:

    test-basic-proxy/lib/negative/badGenerationTest.js

I'm thinking that's sufficient confirmation that the JSON schema validation works -- see any need for additional coverage?

**Comment by georgeajit** [comment]
Unit tests run fine on Jenkins. NodeAPIUnitTests_develop-b10_0 job.
