### ISSUE TITLE
accept other raw formats in rows.query()

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#560]
In support of the of new query inputs for the /v1/rows endpoint that were implemented under internal bug 55547....

Add a constructor function that wraps a raw query with an object that declares its format to be an Optic AST as a stringified or JavaScript literal JSON object, SQL as a string, SPARQL SELECT as a string, or a QBV XML plan as a string.

Modify the rows explain(), query(), and queryAsStream() methods to support any of these wrapped raw queries.

**Comment by ehennum** [comment]
I see from the unit tests that this was implemented but never sent to test:

https://github.com/marklogic/node-client-api/blob/develop/test-basic/rows.js#L159

**Comment by georgeajit** [comment]
Tests and QA sanity tests are working as expected.
