### ISSUE TITLE
client interface for Optic enhancements

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#561]
The enhancements are as follows.

fromSearch() accessor
fromSearchDocs() convenience

groupByUnion() and groupToArrays() modifiers
facetBy() convenience
group(), rollup(), cube(), and namedGroup() helpers
hasGroupKey() aggregate

bind-as() modifier

in() operator

**Comment by ehennum** [comment]
Includes unit tests for new builder methods

SQL and Query DSL payloads on rows.query() still to come

**Comment by ehennum** [comment]
Should have full parity with Java now.

**Comment by georgeajit** [comment]
All new optic enhancements are working as expected.
