### ISSUE TITLE
Upgrade node-client-api to use node 14

### ISSUE THREAD

**Issue by anu3990** [marklogic/node-client-api#565]
Currently, the node-client-api uses node version -10. We are introducing compatibility with node version -14 to make use of new node features.

**Comment by ehennum** [comment]
Here's the Node.js timeline:

https://nodejs.org/en/about/releases/

**Comment by georgeajit** [comment]
Verified on 06/22/21 : https://jenkins.marklogic.com/view/Node%20API/job/NodeAPIUnitTests_develop_b10_0/3467/console

```
+ which node
/bin/node
+ node --version
v14.16.1
+ node etc/test-setup.js -u admin:admin
checking for REST users
```
