### ISSUE TITLE
Jenkins failure - Tests in probe.js

### ISSUE THREAD

**Issue by anu3990** [marklogic/node-client-api#579]
Two tests in probe.js with title "probe in transaction using param list.should find written doc in same transaction"-  throw 403 exception in Jenkins. The user - rest-writer need xdmp-invoke privilege in order to run these tests. 
As a fix, rest-evaluator role (this internally has xdmp-invoke priviledge), needs to be added to the user - rest-writer

**Comment by georgeajit** [comment]
No failures seen.
