### ISSUE TITLE
BiTemporal write using Node APIs results in a document that is not in the "latest" collection

### ISSUE THREAD

**Issue by gvaidees** [marklogic/node-client-api#58]
I am doing a bitemporal write such as 

```javascript
db.documents.write({
      uri: docuri,
      collections: ['coll0', 'coll1'],
      temporalCollection: 'temporalCollection',
      contentType: 'application/json',
      quality: 10,
      permissions: [
        {'role-name':'app-user', capabilities:['read']},
        {'role-name':'app-builder', capabilities:['read', 'update']}
      ],
      properties: {prop1:'foo', prop2:25},
      content: {
        'System': {
          'systemStartTime' : "",
          'systemEndTime' : "",
        },
        'Valid': {
          'validStartTime': "2001-01-01T00:00:00",
          'validEndTime': "2011-12-31T23:59:59"
        },
        'Address': "999 Skyway Park",
        'uri': "javaSingleDoc1.json",
        id: 12, 
        name: 'Jason'
      }
    })
```
And I am seeing that the document is created and is under the right temporal collection and also belongs to doc uri collection. But, it does not have "latest" collection associated with it. I am not sure how the server is letting us do this. 

When I update the temporal document using `xdmp:document-insert`, I get an error from the server - "Cannot perform non-temporal operation on document in temporal collection". So, it looks like the server knows that it is a bitemporal document. But, the document should belong to latest collection.

At this point this is a blocker since further testing around temporal document 'update', delete depends on latest collection check. 

Subscribing @grechaw and @fxue

**Comment by ehennum** [comment]
closing because shipped
