### ISSUE TITLE
documentation for ctsQuery functions  

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#595]
The documentation for the namespaces in the CtsQueryBuilder don't list the functions -- by contrast with PlanBuilder,

For instance compare these two pages:

- https://docs.marklogic.com/jsdoc/ctsQueryBuilder.cts.html
- https://docs.marklogic.com/jsdoc/planBuilder.cts.html

or these two pages:

- https://docs.marklogic.com/jsdoc/ctsQueryBuilder.fn.html
- https://docs.marklogic.com/jsdoc/planBuilder.fn.html 

In the past, we've solved this problem with the JSDoc @borrow instruction.  

For example, ValuesBuilder borrows some function documentation from QueryBuilder:

    https://github.com/marklogic/node-client-api/blob/master/lib/values-builder.js#L52

It would be useful to investigate whether JSDoc has introduced anything that would require less effort to maintain.

Alternatively, maybe the code generation for the namespaces of PlanBuilder could generate some artifacts for CtsQueryBuilder.

**Comment by anu3990** [comment]
Creating a new Jira ticket.
