### ISSUE TITLE
refactor to eliminate through2 dependency

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#596]
Enhancements to the core Node.js API have made the through2 dependency unnecessary.  See:

https://github.com/rvagg/through2#do-you-need-this

and the "simplified constructor approach" discussion under 

https://nodejs.org/api/stream.html#stream_new_stream_transform_options

as well as the stream.PassThrough class.

The simplified constructor approach was added in Node.js v1.2.0 according to this section:

https://nodejs.org/api/stream.html#stream_simplified_construction

Thus, the simplified constructor approach should be supported by the minimum version of Node.js required by the MarkLogic Node.js API.

As with all changes of dependencies, this refactoring will be best to do at the start of a new release cycle.

**Comment by anu3990** [comment]
Creating a new Jira ticket.
