### ISSUE TITLE
Parameters "start" and "length" have no effect for db.graphs.sparql call

### ISSUE THREAD

**Issue by lifan0127** [marklogic/node-client-api#638]
node-client-api version: 2.8.0

I am following the 3rd example in this documentation, with a `callObject` as argument for the `db.graphs.sparql` method.

https://docs.marklogic.com/guide/node-dev/semantics#id_59472.

Below is a minimal example. 

```js
const marklogic = require('marklogic')

const db = marklogic.createDatabaseClient({
    host: 'localhost',
    port: 8000,
    authType: 'digest',
    user: 'admin',
    password: 'admin',
})

db.graphs.sparql({
  contentType: 'application/sparql-results+json', 
  query: 'SELECT * WHERE { ?s ?p ?o .}',
  start: 10,
  length: 10
}).result().then(console.log)
```

It seems no matter what `start` and `length` I set, it always returns all the triples.

Is this a bug or have I misunderstood the method signature? Thanks!

**Comment by anu3990** [comment]
Hi @lifan0127 
can you please try the below -
const marklogic = require('marklogic')

const db = marklogic.createDatabaseClient({
    host: 'localhost',
    port: 8000,
    authType: 'digest',
    user: 'admin',
    password: 'admin',
})

db.graphs.sparql({
  contentType: 'application/sparql-results+json', 
  query: 'SELECT * WHERE { ?s ?p ?o .}',
  begin: 10,
  end: 20
}).result().then(console.log)

**Comment by anu3990** [comment]
Changes are - 
1. "start" word is replaced by "begin".
2. "length" word is replaced by "end". This is not the length but the begin value plus the length of documents needed. So in the above case 10 values should be returned.

**Comment by lifan0127** [comment]
Okay. Thank. I will give it a try. I guess the documentation is outdated then.

**Comment by georgeajit** [comment]
Test is available and runs fine on Jenkins environment.
