### ISSUE TITLE
Expose op.columnInfo on Client API

### ISSUE THREAD

**Issue by anu3990** [marklogic/node-client-api#654]
Related server bug: 57080 - Expose op.columnInfo on Client API
Corresponding issue on Java Client Api - https://github.com/marklogic/java-client-api/issues/1329

**Comment by llinggit** [comment]
Confirmed with Erik that this API is not auto-generated. In Java Client API, this method is implemented in RowManager.java, not PlanBuilder.java.

**Comment by anu3990** [comment]
Creating a new Jira ticket.
