### ISSUE TITLE
Generate and test the 3rd parameter of op.xpath

### ISSUE THREAD

**Issue by anu3990** [marklogic/node-client-api#655]
Newly added optic APIs including

op.columnInfo (TBD)
3rd parameter for op.xpath

Corresponding issue in Java Client Api - https://github.com/marklogic/java-client-api/issues/1328

**Comment by llinggit** [comment]
op.coumnInfo will be implemented and tested in issue #654.

The new op.xpath needs to be regenerated.
Need to modify optic-defs.json under xdmp/src/makefiles/optic first.
Then run code generation again to refresh the change in Node Client API.
Assign the task to me to do the code generation.

**Comment by anu3990** [comment]
Creating a new Jira ticket.
