### ISSUE TITLE
Unable to extract array value

### ISSUE THREAD

**Issue by ayuwono** [marklogic/node-client-api#66]
Steps:
======
1) Insert this document:
       uri: '/test/query/matchList/doc5.json',
        collections: ['matchList'],
        contentType: 'application/json',
        content: {
          title: 'The memex',
          popularity: 5,
          id: '0026',
          date: '2009-05-05',
          price: {
               amt: 123.45
             },
          p: 'The Memex, unfortunately, had no automated search feature',
          category: ['history', 'america', 'president']
          }

2) Perform document query and extract the array value. It gives 400 error message that says invalid path

  it('should do extract with back level up', function(done){
    db.documents.query(
      q.where(
        q.word('title', 'The memex')
      ).
      slice(1, 10,
        q.extract({
          selected:'include-with-ancestors',
          paths:[
            '/node("category")/node()[2]'
          ]
        })
      )
    ).result(function(response) {
      console.log(JSON.stringify(response, null, 4));
      done();
    }, done);
  });

**Comment by ehennum** [comment]
closing because shipped
