### ISSUE TITLE
How to parse string query in Plan Builder (Optic API)?

### ISSUE THREAD

**Issue by lifan0127** [marklogic/node-client-api#683]
How to use `cts.parse` in Plan Builder (Optic API), or what other mechanisms exist to parse string-query?

The documentation states that we can use `pb.cts.*` to access server-side cts query constructors.

https://docs.marklogic.com/guide/node-dev/optic#id_93000

> The planBuilder interface includes namespaces that expose proxies for many server-side operations. For example, you can call cts query constructors ...

I see a list of `pb.cts.*` proxies defined here but it does not include the `cts.parse` function: https://github.com/marklogic/node-client-api/blob/master/lib/plan-builder-generated.js

Thanks!

**Comment by anu3990** [comment]
@lifan0127 would you like to try "unquote" function - https://github.com/marklogic/node-client-api/blob/master/lib/plan-builder-generated.js#L6125 
Here is a unit test for reference - https://github.com/marklogic/node-client-api/blob/master/test-basic/plan-builder-generated.js#L2110

**Comment by rjrudin** [comment]
Closing due to no response.
