### ISSUE TITLE
add return-query to queryBuilder.withOptions

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#69]
For debugging purposes, it would be very nice to have this option supported by queryBuilder. Right now, I have to fall back on the REST API to find out what the server sees. It's pretty annoying. 

IDC if the query comes back as XML in the search results. At least I can examine what the server is executing. Between the builder and the lack of return-query, it's thoroughly obscured by the API right now.

**Comment by wooldridge** [comment]
+1 

I agree that having the return-query option available would be helpful.

**Comment by ehennum** [comment]
The counter argument is that return query doesn't report the query in the constructs of the builder.

In other words, it is worth discussing whether it would be useful to the target audience:  Node.js developers who don't know the Search API.

**Comment by kcoleman-marklogic** [comment]
My two cents:

When I am debugging something, I'll grab any floating plank I can find, even if it is a poorly understood one. For example, I would rather have a stacktrace full of frames that I know nothing about than just a "Haha, sucks to be you" error message. I might glean just enough info from the trace to put me on the right path.

I believe the same thing applies here. I might not know how to write a `cts:json-property-value-query`, but I can probably still connect the dots well enough to have an "ah ha" moment if I thought I was building a word query.

I don't see "Thank you for playing. Please try again, blindly" as better, and I'd rather have a simple, imperfect solution soon than wait indefinitely for a fancy solution in the right vernacular.

Or do you see some other alternative, Erik?

**Comment by georgeajit** [comment]
Closing the issue to keep API stable.
