### ISSUE TITLE
MarkLogic module v 2.9.1 for Node.js at Windows OS does not work

### ISSUE THREAD

**Issue by nishantsingh1** [marklogic/node-client-api#694]
(Created for request from Ming Tsao)
The latest version(2.9.1) of the MarkLogic module for Node.js on Windows OS does not work.

Following are the steps to verify:
   Go to a Windows OS, Node.js environment
  > **npm view marklogic versions**
[

  '1.0.0-ea3', '1.0.1',     '1.0.2',

  '1.0.3',     '1.0.4',     '1.0.5',

  '1.0.6',     '2.0.0-ea4', '2.0.2',

  '2.0.3',     '2.1.1',     '2.2.0',

  '2.3.0',     '2.3.1',     '2.3.2',

  '2.4.0',     '2.4.1',     '2.4.2',

  '2.5.0',     '2.6.0',     '2.7.0',

  '2.8.0',     '2.9.0',     '**2.9.1**'

]

 

_# the latest version is 2.9.1, failed._

> **npm install marklogic --save**

npm ERR! code 1

npm ERR! path C:\projects\node\srv\ml_user\node_modules\marklogic

npm ERR! command failed

npm ERR! command C:\Windows\system32\cmd.exe /d /s /c ([ ! -f package-lock.json ] && npm install --package-lock-only --ignore-scripts); yes | npx npm-force-resolutions

npm ERR! yes was unexpected at this time.

 

#previous version 2.9.0 works, but with high vulnerabilities including critical. This module has not been properly maintained.

> npm install [marklogic@2.9.0](mailto:marklogic@2.9.0) --save

 

added 639 packages, changed 4 packages, and audited 645 packages in 11s

 

2 packages are looking for funding

  run `npm fund` for details

 

34 vulnerabilities (11 moderate, 20 high, 3 critical)

 

To address issues that do not require attention, run:

  npm audit fix

 

Some issues need review, and may require choosing

a different dependency.

 

Run `npm audit` for details.

_____
WORKAROUND is to run with the ' --ignore-scripts' option,
_npm install marklogic --save --ignore-scripts_

However, that is not fully solving the problem as the vulnerabilities are still there.
That is not fully solving the problem.   

Following show the runs. The module dependency situation is not ideal. This module really requires someone to look into.

> **npm install marklogic --save --ignore-scripts**
added 62 packages, removed 618 packages, changed 1 package, and audited 89 packages in 7s
17 packages are looking for funding
  run `npm fund` for details
2 high severity vulnerabilities
Some issues need review, and may require choosing
a different dependency.
 

Run `npm audit` for details.
>**npm audit --ignore-scripts**

# npm audit report
dicer  *
Severity: high
Crash in HeaderParser in dicer - https://github.com/advisories/GHSA-wm7h-9275-46v2
No fix available
node_modules/dicer
  marklogic  *
  Depends on vulnerable versions of dicer
  node_modules/marklogic
2 high severity vulnerabilities

Some issues need review and may require choosing a different dependency.

Env:
Node v16.18.0
Windows 10 Enterprise and Windows server 2019

**Comment by anu3990** [comment]
Hi Nishant -
1. If the user is using Windows OS, please use "npm install marklogic --save --ignore-scripts" instead of "npm install marklogic --save". We will add it to READme file in the next release.
2. Regarding the  vulnerability, for 2.9.1 release we fixed the critical, few high and medium vulnerabilities except one - "dicer" (since the vulnerability was not fixed even in the latest version of dicer "0.3.1"). We did find a replacement for it and it is currently in the "develop" branch and will be going out in the next release.

**Comment by anu3990** [comment]
Assigning to @mariusmarklogic  for testing. Thanks.!

**Comment by mariusmarklogic** [comment]
On my Windows machine it works fine.

**Comment by wesley3295** [comment]
What's the ETA on this @mariusmarklogic?

**Comment by anu3990** [comment]
@wesley3295 this issue has been fixed in Node Client 3.0.0 release. Please let us know if you run into any problem. Thanks.!

**Comment by wesley3295** [comment]
@anu3990 Documentation says if you are on windows os to run 2.9.1. This is related to dicer dep 

When running 3.0 on windows os I get a SSL Certificate Expiration Error

**Comment by anu3990** [comment]
Hi @wesley3295 , please use "npm install marklogic --save --ignore-scripts" if you have a Windows OS and would like to use Node Client 2.9.1.
But if you want to use Node Client 3.0 , "npm install marklogic --save" should work fine for all Operating Systems.

**Comment by anu3990** [comment]
@wesley3295  closing this ticket. Please open a new issue if you are still facing any issues. Thanks.!
