### ISSUE TITLE
Improve error checking query builder

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#70]
It is remarkably easy to construct invalid queries with the queryBuilder. "Invalid combined search" is quickly becoming my most hated phrase in the English language. WHY is it invalid? What did it even look like?

When this happens to me, I engage in this daftness:
- In node, dump the queryBuilder.where output to the console
- Tote the query portion over to QC and run it through sut:handle-text to get the XML
- Feed the XML to search:resolve so I can examine the real errors
- Tinker with the XML or JSON until it works
- Work backwards from there to the correct query build invocation

Gonna go out on a limb here and assert that's not really an option for the average user. :)

I'm not sure how fixable this is since I think it is a somewhat inevitable result of so many layers between user and sever. The old "Telephone" game in action. However, it seems like it could be partly addressed by beefing up error checking in the query builder so it isn't quite so easy to shoot yourself in the foot. What's the point of a builder if it lets you create invalid queries?

Alternatively, I suppose we could offer some validation hook, but it needs to return the actual errors instead of devolving to REST-INVALIDPARAM like it does now. The difficulty is that the bad queries created by the builder can cause the Search API to throw an exception, and by the time that filters back out through the REST API, you end up with something unhelpful like this:

`REST-INVALIDPARAM: Invalid parameter: Invalid combined search`

I doubt there's much to be done about that, which is why I think queryBuilder needs to get smarter.

**Comment by georgeajit** [comment]
Will keep the API stable.
