### ISSUE TITLE
proxy-generator fails due to lack of dependencies

### ISSUE THREAD

**Issue by filetvignon** [marklogic/node-client-api#743]
When using /lib/proxy-generator.js in a gulp file to generate data services files, it fails due to lack of 2 dependencies:

- ast-types
- astring

These are listed as `devDependencies` but maybe they should be regular dependencies since users are supposed to run this.

**Comment by anu3990** [comment]
@filetvignon can you please provide steps to recreate this issue

**Comment by anu3990** [comment]
Closing this. Please open a new issue if you still run into this. Thanks.!
