### ISSUE TITLE
Get a Node stream from a REST endpoint response

### ISSUE THREAD

**Issue by fgeorges** [marklogic/node-client-api#781]
I am trying to retrieve a log file from the REST API, and plug the response straight to a Node read stream (as the file can be very large.)  But I am not sure how to get a read stream from the response using the MarkLogic Node API.

Here is how I retrieve a JSON object (here the endpoint to get the list of log files):

```js
const options = mlutil.copyProperties(client.getConnectionParams());
options.port     = 8002;
options.authType = 'DIGEST';
options.method   = 'GET';
options.headers  = {'Accept': 'application/json'};
options.path     = '/manage/v2/logs';
const oper = new Operation('list log files', client, options, 'empty', 'single');
const resp = await requester.startRequest(oper);
const obj  = await resp.result();
```

What would be the best way to retrieve the read stream directly from the response (if I add the params `filename` and `host`, and change `Accept` to `text/plain`)?

**Comment by fgeorges** [comment]
I've just realized that for a response body, it would probably be a write stream instead, on which to set up the proper event handlers, rather than a read stream. The goal is really to access the underlying stream from the HTTP layer, in order to avoid buffering.

**Comment by fgeorges** [comment]
Hi @anu3990 , thank you for the response!  My goal is simply to invoke `/manage/v2/logs?filename=ErrorLog.txt&host=xxx&format=text`, and stream the result (which could be very large.)

The above code is how I invoke a Manage endpoint.  there might be a simpler, built-in way that I missing, though.

For streaming, I guess I need to use `ResultProvider.stream()`, but I cannot seem to find the right way to use it :(

**Comment by fgeorges** [comment]
Well, that's embarrassing.  I've just figured out that, in my simple repro, I called `client.release()` right after piping, instead of calling it into the stream's `destroy()`.  So now, piping the result of `stream()` to a `Writable` actually works! :+1:

**Comment by anu3990** [comment]
Perfect.! Glad it is working for you.! Please let us know if there is anything else we can assist you with. Thanks.!

**Comment by fgeorges** [comment]
It's fine for me, so I am going to close the ticket.  Thank you1
