### ISSUE TITLE
DocumentDescriptor.contentType ignored in documents.write()

### ISSUE THREAD

**Issue by fgeorges** [marklogic/node-client-api#784]
I am using `client.documents.write()` to ingest documents in the database.  The documents are provided as read streams.  I use `contentType` on the document descriptors to force the content to be stored as JSON.  There is one specific case where it is not taken into account though: it stores the document as a binary node.

Here is a piece of code to reproduce the problem (adapt the connection details as needed, and maybe adapt the path `./package.json` to any JSON file):

```js
"use strict";

const fs  = require('node:fs');
const ml  = require('marklogic');

async function main()
{
    const client = ml.createDatabaseClient({
        host:     'localhost',
        port:     '8000',
        database: 'Documents',
        user:     'admin',
        password: 'admin',
        authType: 'DIGEST',
    });
    // /uri works, /uri.ext fails
    // 2 docs in the array works, 1 doc fails
    const res = client.documents.write([{
        content:     fs.createReadStream('./package.json'),
        uri:         '/uri.ext',
        contentType: 'application/json',
    }]);
    console.dir(await res.result());
    client.release();
}

main();
```

This will store the document as a binary node, instead of a JSON document.  Two interesting points to note:
- if you change the URI from `/uri.ext` to `/uri`, it stores it as JSON (the "extension" seems to be the difference that matters, here, `.123` or `.abc` reproduce the problem as well)
- if you add a second document descriptor in the array (e.g. by duplicating the one above and changing the URI to `/uri2.ext`), it stores both documents as JSON

**Comment by anu3990** [comment]
Looking into this. Thanks.!

**Comment by anu3990** [comment]
This is might be a REST Api issue.

**Comment by rjrudin** [comment]
This is working as designed based on the docs at https://docs.marklogic.com/guide/rest-dev/intro#id_49079 - we will track internally if that's not the case.
