### ISSUE TITLE
replace-insert operation for property in document patch

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#80]
We need an operation to replace the value of a key if it exists or insert the property if it doesn't.

**Comment by dmcassel** [comment]
The [replaceInsert documentation](http://docs.marklogic.com/guide/node-dev/partial-update#id_36747) suggests that this can now be done. 

> If select targets a property and content is an object, the operation replaces the entire target property. Otherwise, the operation replaces just the value.

Is that correct?

**Comment by kcoleman-marklogic** [comment]
Nothing has changed. The same limitations apply now as when 8.0-1 came out. Off the top of my head, I don't recall what they all are any longer, but that's probably worded poorly.

**Comment by dmcassel** [comment]
I just submitted a [PR to Geophoto](https://github.com/marklogic/Geophoto/pull/4) that does this, so I think it must have gotten implemented at some point. In that PR, I'm doing a patch request like this:

    pb.replaceInsert(
      '/title',
      '/',
      'last-child',
      update.title
    )

where update.title is a simple string. If title does not exist in the target document, it gets added with the simple string value. If title does exist, the value gets updated with the new string.

**Comment by georgeajit** [comment]
This can be done using separate insert and replace operations with different predicates.
