### ISSUE TITLE
Data Service Proxy Gen Doesn't Allow "anyDocument" `datatype` Property

### ISSUE THREAD

**Issue by rjdew-progress** [marklogic/node-client-api#908]
When working with Bulk Data Services in Java, there is the anyDocument data type for endpoints that you customize the handling of input and output documents.

> For the anyDocument data type, us the onHandles() factory method instead of the on() factory method to construct the caller. The input or output must be sent or received as handle instances of the same BufferableContentHandle subclass passed to the onHandles() factory method. In particular, each input handle must declare the format of the input document (for instance, by calling the withFormat() fluent setter). - https://github.com/marklogic/java-client-api/wiki/Data-Services-for-IO

Attempting to generate a proxy with the anyDocument datatype property value fails with the node client. There might be a larger discussion to be had about what level of support the Node Client has for Bulk Data Services.

**Comment by rjrudin** [comment]
Will discuss this internally.
