### ISSUE TITLE
Function links in JSDoc jump to after the function name

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#91]
I'm not sure we can anything about this, but it is worth investigating as it is undeniably annoying. From Dave Cassel:

When I click a link on the right to go to a particular function, the anchor is off. The name of the function is off the top of the screen.

**Comment by wooldridge** [comment]
@kcoleman-marklogic would you like to review this fix?

**Comment by kcoleman-marklogic** [comment]
I just spot checked a dozen or so methods, in various "namespaces", on pubs. I checked both v8 and v9. I found no problems. 

In fact, it looks so terrific that I could weep for joy! Thank you, Mike.

**Comment by wooldridge** [comment]
Thanks for reviewing, @kcoleman-marklogic -- I'm going to enjoy this fix, too!
