### ISSUE TITLE
JSDoc: Highlight color on dropdown menus makes text unreadable

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#92]
From Dave Cassel:

When I click on Namespaces at the top, I get a drop-down menu. Hovering over a menu item highlights it with a color close enough to the text color as to make it almost unreadable (at least on my monitor). Perhaps the highlighting could include making the text a dark color to balance the light highlighting.

I'm sure this can be addressed by mucking with the template. It's probably something I screwed up when I changed from the default colors to more MarkLogic-y colors.

**Comment by wooldridge** [comment]
@kcoleman-marklogic would you like to review this fix?

**Comment by kcoleman-marklogic** [comment]
Sorry, I somehow failed to notice you asked me to look at this. I just checked it on pubs and it looks great. Shipping.
