### ISSUE TITLE
improve completeness and flow of the top level README

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic/node-client-api#93]
Feedback from Dave Cassel:
* Missing: if I want to use the Node Client API, I need to "npm install marklogic". 
* The getting started stuff appears to assume that I want to go through the examples. Maybe separate these things: Getting Started vs. Learning to Use? Compare with Gulp's Getting Started page

At minimum, the README needs a cleanup pass before final release to make sure the setup instructions are correct and the flow is where we want it to be. This'll probably end up as a joint effort between Erik and I, with review by Justin, but I'll assign it to myself for now as Erik probably has bigger fish to fry.

**Comment by kcoleman-marklogic** [comment]
README definitely needs revision before 8.0-1. It is all EA centric atm.

**Comment by kcoleman-marklogic** [comment]
Erik fixed up the README on the develop branch. It looks OK to me. Passing to Justin for a final nod.

**Comment by jmakeig** [comment]
Made some modifications in 9b7089cf5ab3c10aa471b07b9963f46f67b48ea5.
