### ISSUE TITLE
manage JSON parse errors

### ISSUE THREAD

**Issue by ehennum** [marklogic/node-client-api#99]
The API should provide a wrapper function with a try / catch around a JSON parse() call, passing any errors to a dispatcher callback. The wrapper should be as small as possible to minimize deoptimization taint.

**Comment by gvaidees** [comment]
The document object on read looks like - 

{ content: 'This is a text document',
  uri: 'issue99.json',
  category: [ 'content' ],
  format: 'json',
  contentType: 'application/json' }

format is json and contentType is  application/json. I am assuming these are derived from the extension. I was able to read the document successfully. I am still working on creating user with minimal set of privileges needed to eval and xdmp.documentInsert. I will check test in once that is done
